"""epic_004_retailer_schema

Revision ID: 4b6f649c3409
Revises: 'ee967465dc62'
Create Date: 2026-07-28 17:29:59.514179

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6f649c3409'
down_revision: Union[str, None] = 'ee967465dc62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retailer',
    sa.Column('retailer_code', sa.String(length=50), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('business_category', sa.String(length=100), nullable=False),
    sa.Column('store_type', sa.String(length=50), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mapped_distributor_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mapped_distributor_id'], ['distributor.public_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'retailer_code', name='uq_retailer_tenant_code')
    )
    op.create_index(op.f('ix_retailer_company_id'), 'retailer', ['company_id'], unique=False)
    op.create_index(op.f('ix_retailer_is_active'), 'retailer', ['is_active'], unique=False)
    op.create_index(op.f('ix_retailer_is_deleted'), 'retailer', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_retailer_mapped_distributor_id'), 'retailer', ['mapped_distributor_id'], unique=False)
    op.create_index(op.f('ix_retailer_organization_id'), 'retailer', ['organization_id'], unique=False)
    op.create_index(op.f('ix_retailer_public_id'), 'retailer', ['public_id'], unique=True)
    op.create_index(op.f('ix_retailer_retailer_code'), 'retailer', ['retailer_code'], unique=False)
    op.create_index(op.f('ix_retailer_status'), 'retailer', ['status'], unique=False)
    op.create_index(op.f('ix_retailer_tenant_id'), 'retailer', ['tenant_id'], unique=False)
    op.create_table('retailer_address',
    sa.Column('retailer_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_address_company_id'), 'retailer_address', ['company_id'], unique=False)
    op.create_index(op.f('ix_retailer_address_is_active'), 'retailer_address', ['is_active'], unique=False)
    op.create_index(op.f('ix_retailer_address_is_deleted'), 'retailer_address', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_retailer_address_organization_id'), 'retailer_address', ['organization_id'], unique=False)
    op.create_index(op.f('ix_retailer_address_public_id'), 'retailer_address', ['public_id'], unique=True)
    op.create_index(op.f('ix_retailer_address_retailer_id'), 'retailer_address', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_retailer_address_tenant_id'), 'retailer_address', ['tenant_id'], unique=False)
    op.create_table('retailer_approval',
    sa.Column('retailer_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('reviewer_email', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_approval_company_id'), 'retailer_approval', ['company_id'], unique=False)
    op.create_index(op.f('ix_retailer_approval_is_active'), 'retailer_approval', ['is_active'], unique=False)
    op.create_index(op.f('ix_retailer_approval_is_deleted'), 'retailer_approval', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_retailer_approval_organization_id'), 'retailer_approval', ['organization_id'], unique=False)
    op.create_index(op.f('ix_retailer_approval_public_id'), 'retailer_approval', ['public_id'], unique=True)
    op.create_index(op.f('ix_retailer_approval_retailer_id'), 'retailer_approval', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_retailer_approval_status'), 'retailer_approval', ['status'], unique=False)
    op.create_index(op.f('ix_retailer_approval_tenant_id'), 'retailer_approval', ['tenant_id'], unique=False)
    op.create_table('retailer_bank',
    sa.Column('retailer_id', sa.UUID(), nullable=False),
    sa.Column('settlement_bank_name', sa.String(length=150), nullable=False),
    sa.Column('account_holder', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('ifsc', sa.String(length=11), nullable=False),
    sa.Column('branch', sa.String(length=150), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_bank_company_id'), 'retailer_bank', ['company_id'], unique=False)
    op.create_index(op.f('ix_retailer_bank_is_active'), 'retailer_bank', ['is_active'], unique=False)
    op.create_index(op.f('ix_retailer_bank_is_deleted'), 'retailer_bank', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_retailer_bank_organization_id'), 'retailer_bank', ['organization_id'], unique=False)
    op.create_index(op.f('ix_retailer_bank_public_id'), 'retailer_bank', ['public_id'], unique=True)
    op.create_index(op.f('ix_retailer_bank_retailer_id'), 'retailer_bank', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_retailer_bank_tenant_id'), 'retailer_bank', ['tenant_id'], unique=False)
    op.create_table('retailer_contact',
    sa.Column('retailer_id', sa.UUID(), nullable=False),
    sa.Column('primary_contact', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_contact_company_id'), 'retailer_contact', ['company_id'], unique=False)
    op.create_index(op.f('ix_retailer_contact_email'), 'retailer_contact', ['email'], unique=False)
    op.create_index(op.f('ix_retailer_contact_is_active'), 'retailer_contact', ['is_active'], unique=False)
    op.create_index(op.f('ix_retailer_contact_is_deleted'), 'retailer_contact', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_retailer_contact_mobile'), 'retailer_contact', ['mobile'], unique=False)
    op.create_index(op.f('ix_retailer_contact_organization_id'), 'retailer_contact', ['organization_id'], unique=False)
    op.create_index(op.f('ix_retailer_contact_public_id'), 'retailer_contact', ['public_id'], unique=True)
    op.create_index(op.f('ix_retailer_contact_retailer_id'), 'retailer_contact', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_retailer_contact_tenant_id'), 'retailer_contact', ['tenant_id'], unique=False)
    op.create_table('retailer_kyc',
    sa.Column('retailer_id', sa.UUID(), nullable=False),
    sa.Column('aadhaar_hash', sa.String(length=255), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('business_proof_url', sa.String(length=500), nullable=True),
    sa.Column('aadhaar_front_url', sa.String(length=500), nullable=True),
    sa.Column('aadhaar_back_url', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_kyc_company_id'), 'retailer_kyc', ['company_id'], unique=False)
    op.create_index(op.f('ix_retailer_kyc_gst_number'), 'retailer_kyc', ['gst_number'], unique=False)
    op.create_index(op.f('ix_retailer_kyc_is_active'), 'retailer_kyc', ['is_active'], unique=False)
    op.create_index(op.f('ix_retailer_kyc_is_deleted'), 'retailer_kyc', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_retailer_kyc_organization_id'), 'retailer_kyc', ['organization_id'], unique=False)
    op.create_index(op.f('ix_retailer_kyc_pan_number'), 'retailer_kyc', ['pan_number'], unique=False)
    op.create_index(op.f('ix_retailer_kyc_public_id'), 'retailer_kyc', ['public_id'], unique=True)
    op.create_index(op.f('ix_retailer_kyc_retailer_id'), 'retailer_kyc', ['retailer_id'], unique=True)
    op.create_index(op.f('ix_retailer_kyc_tenant_id'), 'retailer_kyc', ['tenant_id'], unique=False)
    op.create_table('retailer_status_history',
    sa.Column('retailer_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=False),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by_email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_status_history_company_id'), 'retailer_status_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_retailer_status_history_is_active'), 'retailer_status_history', ['is_active'], unique=False)
    op.create_index(op.f('ix_retailer_status_history_is_deleted'), 'retailer_status_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_retailer_status_history_organization_id'), 'retailer_status_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_retailer_status_history_public_id'), 'retailer_status_history', ['public_id'], unique=True)
    op.create_index(op.f('ix_retailer_status_history_retailer_id'), 'retailer_status_history', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_retailer_status_history_tenant_id'), 'retailer_status_history', ['tenant_id'], unique=False)
    op.create_table('retailer_wallet',
    sa.Column('retailer_id', sa.UUID(), nullable=False),
    sa.Column('wallet_balance', sa.Float(), nullable=False),
    sa.Column('daily_transaction_limit', sa.Float(), nullable=False),
    sa.Column('single_transaction_limit', sa.Float(), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('freeze_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_wallet_company_id'), 'retailer_wallet', ['company_id'], unique=False)
    op.create_index(op.f('ix_retailer_wallet_is_active'), 'retailer_wallet', ['is_active'], unique=False)
    op.create_index(op.f('ix_retailer_wallet_is_deleted'), 'retailer_wallet', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_retailer_wallet_organization_id'), 'retailer_wallet', ['organization_id'], unique=False)
    op.create_index(op.f('ix_retailer_wallet_public_id'), 'retailer_wallet', ['public_id'], unique=True)
    op.create_index(op.f('ix_retailer_wallet_retailer_id'), 'retailer_wallet', ['retailer_id'], unique=True)
    op.create_index(op.f('ix_retailer_wallet_tenant_id'), 'retailer_wallet', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retailer_wallet_tenant_id'), table_name='retailer_wallet')
    op.drop_index(op.f('ix_retailer_wallet_retailer_id'), table_name='retailer_wallet')
    op.drop_index(op.f('ix_retailer_wallet_public_id'), table_name='retailer_wallet')
    op.drop_index(op.f('ix_retailer_wallet_organization_id'), table_name='retailer_wallet')
    op.drop_index(op.f('ix_retailer_wallet_is_deleted'), table_name='retailer_wallet')
    op.drop_index(op.f('ix_retailer_wallet_is_active'), table_name='retailer_wallet')
    op.drop_index(op.f('ix_retailer_wallet_company_id'), table_name='retailer_wallet')
    op.drop_table('retailer_wallet')
    op.drop_index(op.f('ix_retailer_status_history_tenant_id'), table_name='retailer_status_history')
    op.drop_index(op.f('ix_retailer_status_history_retailer_id'), table_name='retailer_status_history')
    op.drop_index(op.f('ix_retailer_status_history_public_id'), table_name='retailer_status_history')
    op.drop_index(op.f('ix_retailer_status_history_organization_id'), table_name='retailer_status_history')
    op.drop_index(op.f('ix_retailer_status_history_is_deleted'), table_name='retailer_status_history')
    op.drop_index(op.f('ix_retailer_status_history_is_active'), table_name='retailer_status_history')
    op.drop_index(op.f('ix_retailer_status_history_company_id'), table_name='retailer_status_history')
    op.drop_table('retailer_status_history')
    op.drop_index(op.f('ix_retailer_kyc_tenant_id'), table_name='retailer_kyc')
    op.drop_index(op.f('ix_retailer_kyc_retailer_id'), table_name='retailer_kyc')
    op.drop_index(op.f('ix_retailer_kyc_public_id'), table_name='retailer_kyc')
    op.drop_index(op.f('ix_retailer_kyc_pan_number'), table_name='retailer_kyc')
    op.drop_index(op.f('ix_retailer_kyc_organization_id'), table_name='retailer_kyc')
    op.drop_index(op.f('ix_retailer_kyc_is_deleted'), table_name='retailer_kyc')
    op.drop_index(op.f('ix_retailer_kyc_is_active'), table_name='retailer_kyc')
    op.drop_index(op.f('ix_retailer_kyc_gst_number'), table_name='retailer_kyc')
    op.drop_index(op.f('ix_retailer_kyc_company_id'), table_name='retailer_kyc')
    op.drop_table('retailer_kyc')
    op.drop_index(op.f('ix_retailer_contact_tenant_id'), table_name='retailer_contact')
    op.drop_index(op.f('ix_retailer_contact_retailer_id'), table_name='retailer_contact')
    op.drop_index(op.f('ix_retailer_contact_public_id'), table_name='retailer_contact')
    op.drop_index(op.f('ix_retailer_contact_organization_id'), table_name='retailer_contact')
    op.drop_index(op.f('ix_retailer_contact_mobile'), table_name='retailer_contact')
    op.drop_index(op.f('ix_retailer_contact_is_deleted'), table_name='retailer_contact')
    op.drop_index(op.f('ix_retailer_contact_is_active'), table_name='retailer_contact')
    op.drop_index(op.f('ix_retailer_contact_email'), table_name='retailer_contact')
    op.drop_index(op.f('ix_retailer_contact_company_id'), table_name='retailer_contact')
    op.drop_table('retailer_contact')
    op.drop_index(op.f('ix_retailer_bank_tenant_id'), table_name='retailer_bank')
    op.drop_index(op.f('ix_retailer_bank_retailer_id'), table_name='retailer_bank')
    op.drop_index(op.f('ix_retailer_bank_public_id'), table_name='retailer_bank')
    op.drop_index(op.f('ix_retailer_bank_organization_id'), table_name='retailer_bank')
    op.drop_index(op.f('ix_retailer_bank_is_deleted'), table_name='retailer_bank')
    op.drop_index(op.f('ix_retailer_bank_is_active'), table_name='retailer_bank')
    op.drop_index(op.f('ix_retailer_bank_company_id'), table_name='retailer_bank')
    op.drop_table('retailer_bank')
    op.drop_index(op.f('ix_retailer_approval_tenant_id'), table_name='retailer_approval')
    op.drop_index(op.f('ix_retailer_approval_status'), table_name='retailer_approval')
    op.drop_index(op.f('ix_retailer_approval_retailer_id'), table_name='retailer_approval')
    op.drop_index(op.f('ix_retailer_approval_public_id'), table_name='retailer_approval')
    op.drop_index(op.f('ix_retailer_approval_organization_id'), table_name='retailer_approval')
    op.drop_index(op.f('ix_retailer_approval_is_deleted'), table_name='retailer_approval')
    op.drop_index(op.f('ix_retailer_approval_is_active'), table_name='retailer_approval')
    op.drop_index(op.f('ix_retailer_approval_company_id'), table_name='retailer_approval')
    op.drop_table('retailer_approval')
    op.drop_index(op.f('ix_retailer_address_tenant_id'), table_name='retailer_address')
    op.drop_index(op.f('ix_retailer_address_retailer_id'), table_name='retailer_address')
    op.drop_index(op.f('ix_retailer_address_public_id'), table_name='retailer_address')
    op.drop_index(op.f('ix_retailer_address_organization_id'), table_name='retailer_address')
    op.drop_index(op.f('ix_retailer_address_is_deleted'), table_name='retailer_address')
    op.drop_index(op.f('ix_retailer_address_is_active'), table_name='retailer_address')
    op.drop_index(op.f('ix_retailer_address_company_id'), table_name='retailer_address')
    op.drop_table('retailer_address')
    op.drop_index(op.f('ix_retailer_tenant_id'), table_name='retailer')
    op.drop_index(op.f('ix_retailer_status'), table_name='retailer')
    op.drop_index(op.f('ix_retailer_retailer_code'), table_name='retailer')
    op.drop_index(op.f('ix_retailer_public_id'), table_name='retailer')
    op.drop_index(op.f('ix_retailer_organization_id'), table_name='retailer')
    op.drop_index(op.f('ix_retailer_mapped_distributor_id'), table_name='retailer')
    op.drop_index(op.f('ix_retailer_is_deleted'), table_name='retailer')
    op.drop_index(op.f('ix_retailer_is_active'), table_name='retailer')
    op.drop_index(op.f('ix_retailer_company_id'), table_name='retailer')
    op.drop_table('retailer')
    # ### end Alembic commands ###
