"""epic_003_organization_schema

Revision ID: ee967465dc62
Revises: '3f03ac5d344d'
Create Date: 2026-07-28 17:12:59.258757

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee967465dc62'
down_revision: Union[str, None] = '3f03ac5d344d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_company_id'), 'entity', ['company_id'], unique=False)
    op.create_index(op.f('ix_entity_is_active'), 'entity', ['is_active'], unique=False)
    op.create_index(op.f('ix_entity_is_deleted'), 'entity', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_entity_organization_id'), 'entity', ['organization_id'], unique=False)
    op.create_index(op.f('ix_entity_public_id'), 'entity', ['public_id'], unique=True)
    op.create_index(op.f('ix_entity_tenant_id'), 'entity', ['tenant_id'], unique=False)
    op.create_table('organization_attachment',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_attachment_company_id'), 'organization_attachment', ['company_id'], unique=False)
    op.create_index(op.f('ix_organization_attachment_entity_id'), 'organization_attachment', ['entity_id'], unique=False)
    op.create_index(op.f('ix_organization_attachment_entity_type'), 'organization_attachment', ['entity_type'], unique=False)
    op.create_index(op.f('ix_organization_attachment_is_active'), 'organization_attachment', ['is_active'], unique=False)
    op.create_index(op.f('ix_organization_attachment_is_deleted'), 'organization_attachment', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_organization_attachment_organization_id'), 'organization_attachment', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_attachment_public_id'), 'organization_attachment', ['public_id'], unique=True)
    op.create_index(op.f('ix_organization_attachment_tenant_id'), 'organization_attachment', ['tenant_id'], unique=False)
    op.create_table('organization_hierarchy',
    sa.Column('parent_entity_type', sa.String(length=50), nullable=False),
    sa.Column('parent_entity_id', sa.UUID(), nullable=False),
    sa.Column('child_entity_type', sa.String(length=50), nullable=False),
    sa.Column('child_entity_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_hierarchy_child_entity_id'), 'organization_hierarchy', ['child_entity_id'], unique=False)
    op.create_index(op.f('ix_organization_hierarchy_child_entity_type'), 'organization_hierarchy', ['child_entity_type'], unique=False)
    op.create_index(op.f('ix_organization_hierarchy_company_id'), 'organization_hierarchy', ['company_id'], unique=False)
    op.create_index(op.f('ix_organization_hierarchy_is_active'), 'organization_hierarchy', ['is_active'], unique=False)
    op.create_index(op.f('ix_organization_hierarchy_is_deleted'), 'organization_hierarchy', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_organization_hierarchy_organization_id'), 'organization_hierarchy', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_hierarchy_parent_entity_id'), 'organization_hierarchy', ['parent_entity_id'], unique=False)
    op.create_index(op.f('ix_organization_hierarchy_parent_entity_type'), 'organization_hierarchy', ['parent_entity_type'], unique=False)
    op.create_index(op.f('ix_organization_hierarchy_public_id'), 'organization_hierarchy', ['public_id'], unique=True)
    op.create_index(op.f('ix_organization_hierarchy_tenant_id'), 'organization_hierarchy', ['tenant_id'], unique=False)
    op.create_table('organization_history',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('performed_by', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_history_company_id'), 'organization_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_organization_history_entity_id'), 'organization_history', ['entity_id'], unique=False)
    op.create_index(op.f('ix_organization_history_entity_type'), 'organization_history', ['entity_type'], unique=False)
    op.create_index(op.f('ix_organization_history_is_active'), 'organization_history', ['is_active'], unique=False)
    op.create_index(op.f('ix_organization_history_is_deleted'), 'organization_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_organization_history_organization_id'), 'organization_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_history_public_id'), 'organization_history', ['public_id'], unique=True)
    op.create_index(op.f('ix_organization_history_tenant_id'), 'organization_history', ['tenant_id'], unique=False)
    op.create_table('organization_note',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_note_company_id'), 'organization_note', ['company_id'], unique=False)
    op.create_index(op.f('ix_organization_note_entity_id'), 'organization_note', ['entity_id'], unique=False)
    op.create_index(op.f('ix_organization_note_entity_type'), 'organization_note', ['entity_type'], unique=False)
    op.create_index(op.f('ix_organization_note_is_active'), 'organization_note', ['is_active'], unique=False)
    op.create_index(op.f('ix_organization_note_is_deleted'), 'organization_note', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_organization_note_organization_id'), 'organization_note', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_note_public_id'), 'organization_note', ['public_id'], unique=True)
    op.create_index(op.f('ix_organization_note_tenant_id'), 'organization_note', ['tenant_id'], unique=False)
    op.create_table('organization_transfer',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('old_parent_type', sa.String(length=50), nullable=False),
    sa.Column('old_parent_id', sa.UUID(), nullable=False),
    sa.Column('new_parent_type', sa.String(length=50), nullable=False),
    sa.Column('new_parent_id', sa.UUID(), nullable=False),
    sa.Column('transfer_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_transfer_company_id'), 'organization_transfer', ['company_id'], unique=False)
    op.create_index(op.f('ix_organization_transfer_entity_id'), 'organization_transfer', ['entity_id'], unique=False)
    op.create_index(op.f('ix_organization_transfer_entity_type'), 'organization_transfer', ['entity_type'], unique=False)
    op.create_index(op.f('ix_organization_transfer_is_active'), 'organization_transfer', ['is_active'], unique=False)
    op.create_index(op.f('ix_organization_transfer_is_deleted'), 'organization_transfer', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_organization_transfer_organization_id'), 'organization_transfer', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_transfer_public_id'), 'organization_transfer', ['public_id'], unique=True)
    op.create_index(op.f('ix_organization_transfer_status'), 'organization_transfer', ['status'], unique=False)
    op.create_index(op.f('ix_organization_transfer_tenant_id'), 'organization_transfer', ['tenant_id'], unique=False)
    op.create_table('regional_manager',
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('reporting_manager_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('kyc_status', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_rm_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'employee_code', name='uq_rm_tenant_employee_code'),
    sa.UniqueConstraint('tenant_id', 'mobile', name='uq_rm_tenant_mobile')
    )
    op.create_index(op.f('ix_regional_manager_company_id'), 'regional_manager', ['company_id'], unique=False)
    op.create_index(op.f('ix_regional_manager_email'), 'regional_manager', ['email'], unique=False)
    op.create_index(op.f('ix_regional_manager_employee_code'), 'regional_manager', ['employee_code'], unique=False)
    op.create_index(op.f('ix_regional_manager_is_active'), 'regional_manager', ['is_active'], unique=False)
    op.create_index(op.f('ix_regional_manager_is_deleted'), 'regional_manager', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_regional_manager_mobile'), 'regional_manager', ['mobile'], unique=False)
    op.create_index(op.f('ix_regional_manager_organization_id'), 'regional_manager', ['organization_id'], unique=False)
    op.create_index(op.f('ix_regional_manager_public_id'), 'regional_manager', ['public_id'], unique=True)
    op.create_index(op.f('ix_regional_manager_status'), 'regional_manager', ['status'], unique=False)
    op.create_index(op.f('ix_regional_manager_tenant_id'), 'regional_manager', ['tenant_id'], unique=False)
    op.create_table('super_distributor',
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc', sa.String(length=11), nullable=True),
    sa.Column('wallet_balance', sa.Float(), nullable=False),
    sa.Column('credit_limit', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mapped_rm_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mapped_rm_id'], ['regional_manager.public_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_sd_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'mobile', name='uq_sd_tenant_mobile')
    )
    op.create_index(op.f('ix_super_distributor_company_id'), 'super_distributor', ['company_id'], unique=False)
    op.create_index(op.f('ix_super_distributor_email'), 'super_distributor', ['email'], unique=False)
    op.create_index(op.f('ix_super_distributor_gst_number'), 'super_distributor', ['gst_number'], unique=False)
    op.create_index(op.f('ix_super_distributor_is_active'), 'super_distributor', ['is_active'], unique=False)
    op.create_index(op.f('ix_super_distributor_is_deleted'), 'super_distributor', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_super_distributor_mapped_rm_id'), 'super_distributor', ['mapped_rm_id'], unique=False)
    op.create_index(op.f('ix_super_distributor_mobile'), 'super_distributor', ['mobile'], unique=False)
    op.create_index(op.f('ix_super_distributor_organization_id'), 'super_distributor', ['organization_id'], unique=False)
    op.create_index(op.f('ix_super_distributor_pan_number'), 'super_distributor', ['pan_number'], unique=False)
    op.create_index(op.f('ix_super_distributor_public_id'), 'super_distributor', ['public_id'], unique=True)
    op.create_index(op.f('ix_super_distributor_status'), 'super_distributor', ['status'], unique=False)
    op.create_index(op.f('ix_super_distributor_tenant_id'), 'super_distributor', ['tenant_id'], unique=False)
    op.create_table('distributor',
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc', sa.String(length=11), nullable=True),
    sa.Column('wallet_balance', sa.Float(), nullable=False),
    sa.Column('credit_limit', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mapped_super_distributor_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mapped_super_distributor_id'], ['super_distributor.public_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_distributor_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'mobile', name='uq_distributor_tenant_mobile')
    )
    op.create_index(op.f('ix_distributor_company_id'), 'distributor', ['company_id'], unique=False)
    op.create_index(op.f('ix_distributor_email'), 'distributor', ['email'], unique=False)
    op.create_index(op.f('ix_distributor_gst_number'), 'distributor', ['gst_number'], unique=False)
    op.create_index(op.f('ix_distributor_is_active'), 'distributor', ['is_active'], unique=False)
    op.create_index(op.f('ix_distributor_is_deleted'), 'distributor', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_distributor_mapped_super_distributor_id'), 'distributor', ['mapped_super_distributor_id'], unique=False)
    op.create_index(op.f('ix_distributor_mobile'), 'distributor', ['mobile'], unique=False)
    op.create_index(op.f('ix_distributor_organization_id'), 'distributor', ['organization_id'], unique=False)
    op.create_index(op.f('ix_distributor_pan_number'), 'distributor', ['pan_number'], unique=False)
    op.create_index(op.f('ix_distributor_public_id'), 'distributor', ['public_id'], unique=True)
    op.create_index(op.f('ix_distributor_status'), 'distributor', ['status'], unique=False)
    op.create_index(op.f('ix_distributor_tenant_id'), 'distributor', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distributor_tenant_id'), table_name='distributor')
    op.drop_index(op.f('ix_distributor_status'), table_name='distributor')
    op.drop_index(op.f('ix_distributor_public_id'), table_name='distributor')
    op.drop_index(op.f('ix_distributor_pan_number'), table_name='distributor')
    op.drop_index(op.f('ix_distributor_organization_id'), table_name='distributor')
    op.drop_index(op.f('ix_distributor_mobile'), table_name='distributor')
    op.drop_index(op.f('ix_distributor_mapped_super_distributor_id'), table_name='distributor')
    op.drop_index(op.f('ix_distributor_is_deleted'), table_name='distributor')
    op.drop_index(op.f('ix_distributor_is_active'), table_name='distributor')
    op.drop_index(op.f('ix_distributor_gst_number'), table_name='distributor')
    op.drop_index(op.f('ix_distributor_email'), table_name='distributor')
    op.drop_index(op.f('ix_distributor_company_id'), table_name='distributor')
    op.drop_table('distributor')
    op.drop_index(op.f('ix_super_distributor_tenant_id'), table_name='super_distributor')
    op.drop_index(op.f('ix_super_distributor_status'), table_name='super_distributor')
    op.drop_index(op.f('ix_super_distributor_public_id'), table_name='super_distributor')
    op.drop_index(op.f('ix_super_distributor_pan_number'), table_name='super_distributor')
    op.drop_index(op.f('ix_super_distributor_organization_id'), table_name='super_distributor')
    op.drop_index(op.f('ix_super_distributor_mobile'), table_name='super_distributor')
    op.drop_index(op.f('ix_super_distributor_mapped_rm_id'), table_name='super_distributor')
    op.drop_index(op.f('ix_super_distributor_is_deleted'), table_name='super_distributor')
    op.drop_index(op.f('ix_super_distributor_is_active'), table_name='super_distributor')
    op.drop_index(op.f('ix_super_distributor_gst_number'), table_name='super_distributor')
    op.drop_index(op.f('ix_super_distributor_email'), table_name='super_distributor')
    op.drop_index(op.f('ix_super_distributor_company_id'), table_name='super_distributor')
    op.drop_table('super_distributor')
    op.drop_index(op.f('ix_regional_manager_tenant_id'), table_name='regional_manager')
    op.drop_index(op.f('ix_regional_manager_status'), table_name='regional_manager')
    op.drop_index(op.f('ix_regional_manager_public_id'), table_name='regional_manager')
    op.drop_index(op.f('ix_regional_manager_organization_id'), table_name='regional_manager')
    op.drop_index(op.f('ix_regional_manager_mobile'), table_name='regional_manager')
    op.drop_index(op.f('ix_regional_manager_is_deleted'), table_name='regional_manager')
    op.drop_index(op.f('ix_regional_manager_is_active'), table_name='regional_manager')
    op.drop_index(op.f('ix_regional_manager_employee_code'), table_name='regional_manager')
    op.drop_index(op.f('ix_regional_manager_email'), table_name='regional_manager')
    op.drop_index(op.f('ix_regional_manager_company_id'), table_name='regional_manager')
    op.drop_table('regional_manager')
    op.drop_index(op.f('ix_organization_transfer_tenant_id'), table_name='organization_transfer')
    op.drop_index(op.f('ix_organization_transfer_status'), table_name='organization_transfer')
    op.drop_index(op.f('ix_organization_transfer_public_id'), table_name='organization_transfer')
    op.drop_index(op.f('ix_organization_transfer_organization_id'), table_name='organization_transfer')
    op.drop_index(op.f('ix_organization_transfer_is_deleted'), table_name='organization_transfer')
    op.drop_index(op.f('ix_organization_transfer_is_active'), table_name='organization_transfer')
    op.drop_index(op.f('ix_organization_transfer_entity_type'), table_name='organization_transfer')
    op.drop_index(op.f('ix_organization_transfer_entity_id'), table_name='organization_transfer')
    op.drop_index(op.f('ix_organization_transfer_company_id'), table_name='organization_transfer')
    op.drop_table('organization_transfer')
    op.drop_index(op.f('ix_organization_note_tenant_id'), table_name='organization_note')
    op.drop_index(op.f('ix_organization_note_public_id'), table_name='organization_note')
    op.drop_index(op.f('ix_organization_note_organization_id'), table_name='organization_note')
    op.drop_index(op.f('ix_organization_note_is_deleted'), table_name='organization_note')
    op.drop_index(op.f('ix_organization_note_is_active'), table_name='organization_note')
    op.drop_index(op.f('ix_organization_note_entity_type'), table_name='organization_note')
    op.drop_index(op.f('ix_organization_note_entity_id'), table_name='organization_note')
    op.drop_index(op.f('ix_organization_note_company_id'), table_name='organization_note')
    op.drop_table('organization_note')
    op.drop_index(op.f('ix_organization_history_tenant_id'), table_name='organization_history')
    op.drop_index(op.f('ix_organization_history_public_id'), table_name='organization_history')
    op.drop_index(op.f('ix_organization_history_organization_id'), table_name='organization_history')
    op.drop_index(op.f('ix_organization_history_is_deleted'), table_name='organization_history')
    op.drop_index(op.f('ix_organization_history_is_active'), table_name='organization_history')
    op.drop_index(op.f('ix_organization_history_entity_type'), table_name='organization_history')
    op.drop_index(op.f('ix_organization_history_entity_id'), table_name='organization_history')
    op.drop_index(op.f('ix_organization_history_company_id'), table_name='organization_history')
    op.drop_table('organization_history')
    op.drop_index(op.f('ix_organization_hierarchy_tenant_id'), table_name='organization_hierarchy')
    op.drop_index(op.f('ix_organization_hierarchy_public_id'), table_name='organization_hierarchy')
    op.drop_index(op.f('ix_organization_hierarchy_parent_entity_type'), table_name='organization_hierarchy')
    op.drop_index(op.f('ix_organization_hierarchy_parent_entity_id'), table_name='organization_hierarchy')
    op.drop_index(op.f('ix_organization_hierarchy_organization_id'), table_name='organization_hierarchy')
    op.drop_index(op.f('ix_organization_hierarchy_is_deleted'), table_name='organization_hierarchy')
    op.drop_index(op.f('ix_organization_hierarchy_is_active'), table_name='organization_hierarchy')
    op.drop_index(op.f('ix_organization_hierarchy_company_id'), table_name='organization_hierarchy')
    op.drop_index(op.f('ix_organization_hierarchy_child_entity_type'), table_name='organization_hierarchy')
    op.drop_index(op.f('ix_organization_hierarchy_child_entity_id'), table_name='organization_hierarchy')
    op.drop_table('organization_hierarchy')
    op.drop_index(op.f('ix_organization_attachment_tenant_id'), table_name='organization_attachment')
    op.drop_index(op.f('ix_organization_attachment_public_id'), table_name='organization_attachment')
    op.drop_index(op.f('ix_organization_attachment_organization_id'), table_name='organization_attachment')
    op.drop_index(op.f('ix_organization_attachment_is_deleted'), table_name='organization_attachment')
    op.drop_index(op.f('ix_organization_attachment_is_active'), table_name='organization_attachment')
    op.drop_index(op.f('ix_organization_attachment_entity_type'), table_name='organization_attachment')
    op.drop_index(op.f('ix_organization_attachment_entity_id'), table_name='organization_attachment')
    op.drop_index(op.f('ix_organization_attachment_company_id'), table_name='organization_attachment')
    op.drop_table('organization_attachment')
    op.drop_index(op.f('ix_entity_tenant_id'), table_name='entity')
    op.drop_index(op.f('ix_entity_public_id'), table_name='entity')
    op.drop_index(op.f('ix_entity_organization_id'), table_name='entity')
    op.drop_index(op.f('ix_entity_is_deleted'), table_name='entity')
    op.drop_index(op.f('ix_entity_is_active'), table_name='entity')
    op.drop_index(op.f('ix_entity_company_id'), table_name='entity')
    op.drop_table('entity')
    # ### end Alembic commands ###
