"""epic_008_compliance_schema

Revision ID: 3104b8b99397
Revises: '444a26cc85da'
Create Date: 2026-07-28 17:48:50.711234

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3104b8b99397'
down_revision: Union[str, None] = '444a26cc85da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_export_job',
    sa.Column('export_reference', sa.String(length=50), nullable=False),
    sa.Column('filter_criteria', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_export_job_company_id'), 'audit_export_job', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_export_job_export_reference'), 'audit_export_job', ['export_reference'], unique=False)
    op.create_index(op.f('ix_audit_export_job_is_active'), 'audit_export_job', ['is_active'], unique=False)
    op.create_index(op.f('ix_audit_export_job_is_deleted'), 'audit_export_job', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_audit_export_job_organization_id'), 'audit_export_job', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_export_job_public_id'), 'audit_export_job', ['public_id'], unique=True)
    op.create_index(op.f('ix_audit_export_job_status'), 'audit_export_job', ['status'], unique=False)
    op.create_index(op.f('ix_audit_export_job_tenant_id'), 'audit_export_job', ['tenant_id'], unique=False)
    op.create_table('compliance_report',
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('tax_period', sa.String(length=20), nullable=False),
    sa.Column('total_txns_count', sa.Integer(), nullable=False),
    sa.Column('total_taxable_value', sa.Float(), nullable=False),
    sa.Column('total_gst_amount', sa.Float(), nullable=False),
    sa.Column('total_tds_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'report_number', name='uq_rep_tenant_number')
    )
    op.create_index(op.f('ix_compliance_report_company_id'), 'compliance_report', ['company_id'], unique=False)
    op.create_index(op.f('ix_compliance_report_is_active'), 'compliance_report', ['is_active'], unique=False)
    op.create_index(op.f('ix_compliance_report_is_deleted'), 'compliance_report', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_compliance_report_organization_id'), 'compliance_report', ['organization_id'], unique=False)
    op.create_index(op.f('ix_compliance_report_public_id'), 'compliance_report', ['public_id'], unique=True)
    op.create_index(op.f('ix_compliance_report_report_number'), 'compliance_report', ['report_number'], unique=False)
    op.create_index(op.f('ix_compliance_report_report_type'), 'compliance_report', ['report_type'], unique=False)
    op.create_index(op.f('ix_compliance_report_status'), 'compliance_report', ['status'], unique=False)
    op.create_index(op.f('ix_compliance_report_tax_period'), 'compliance_report', ['tax_period'], unique=False)
    op.create_index(op.f('ix_compliance_report_tenant_id'), 'compliance_report', ['tenant_id'], unique=False)
    op.create_table('gst_filing_summary',
    sa.Column('tax_period', sa.String(length=20), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=False),
    sa.Column('sgst_amount', sa.Float(), nullable=False),
    sa.Column('igst_amount', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gst_filing_summary_company_id'), 'gst_filing_summary', ['company_id'], unique=False)
    op.create_index(op.f('ix_gst_filing_summary_is_active'), 'gst_filing_summary', ['is_active'], unique=False)
    op.create_index(op.f('ix_gst_filing_summary_is_deleted'), 'gst_filing_summary', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_gst_filing_summary_organization_id'), 'gst_filing_summary', ['organization_id'], unique=False)
    op.create_index(op.f('ix_gst_filing_summary_public_id'), 'gst_filing_summary', ['public_id'], unique=True)
    op.create_index(op.f('ix_gst_filing_summary_tax_period'), 'gst_filing_summary', ['tax_period'], unique=False)
    op.create_index(op.f('ix_gst_filing_summary_tenant_id'), 'gst_filing_summary', ['tenant_id'], unique=False)
    op.create_table('system_alert_policy',
    sa.Column('policy_name', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('recipient_emails', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_alert_policy_company_id'), 'system_alert_policy', ['company_id'], unique=False)
    op.create_index(op.f('ix_system_alert_policy_is_active'), 'system_alert_policy', ['is_active'], unique=False)
    op.create_index(op.f('ix_system_alert_policy_is_deleted'), 'system_alert_policy', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_system_alert_policy_organization_id'), 'system_alert_policy', ['organization_id'], unique=False)
    op.create_index(op.f('ix_system_alert_policy_public_id'), 'system_alert_policy', ['public_id'], unique=True)
    op.create_index(op.f('ix_system_alert_policy_tenant_id'), 'system_alert_policy', ['tenant_id'], unique=False)
    op.create_table('system_health_log',
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_health_log_company_id'), 'system_health_log', ['company_id'], unique=False)
    op.create_index(op.f('ix_system_health_log_component_name'), 'system_health_log', ['component_name'], unique=False)
    op.create_index(op.f('ix_system_health_log_is_active'), 'system_health_log', ['is_active'], unique=False)
    op.create_index(op.f('ix_system_health_log_is_deleted'), 'system_health_log', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_system_health_log_organization_id'), 'system_health_log', ['organization_id'], unique=False)
    op.create_index(op.f('ix_system_health_log_public_id'), 'system_health_log', ['public_id'], unique=True)
    op.create_index(op.f('ix_system_health_log_tenant_id'), 'system_health_log', ['tenant_id'], unique=False)
    op.create_table('tenant_configuration',
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'config_key', name='uq_tenant_config_key')
    )
    op.create_index(op.f('ix_tenant_configuration_company_id'), 'tenant_configuration', ['company_id'], unique=False)
    op.create_index(op.f('ix_tenant_configuration_config_key'), 'tenant_configuration', ['config_key'], unique=False)
    op.create_index(op.f('ix_tenant_configuration_is_active'), 'tenant_configuration', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenant_configuration_is_deleted'), 'tenant_configuration', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tenant_configuration_organization_id'), 'tenant_configuration', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tenant_configuration_public_id'), 'tenant_configuration', ['public_id'], unique=True)
    op.create_index(op.f('ix_tenant_configuration_tenant_id'), 'tenant_configuration', ['tenant_id'], unique=False)
    op.create_table('compliance_report_item',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('entity_code', sa.String(length=100), nullable=False),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('gstin', sa.String(length=30), nullable=True),
    sa.Column('gross_volume', sa.Float(), nullable=False),
    sa.Column('mdr_value', sa.Float(), nullable=False),
    sa.Column('gst_value', sa.Float(), nullable=False),
    sa.Column('tds_value', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['compliance_report.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_report_item_company_id'), 'compliance_report_item', ['company_id'], unique=False)
    op.create_index(op.f('ix_compliance_report_item_is_active'), 'compliance_report_item', ['is_active'], unique=False)
    op.create_index(op.f('ix_compliance_report_item_is_deleted'), 'compliance_report_item', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_compliance_report_item_organization_id'), 'compliance_report_item', ['organization_id'], unique=False)
    op.create_index(op.f('ix_compliance_report_item_public_id'), 'compliance_report_item', ['public_id'], unique=True)
    op.create_index(op.f('ix_compliance_report_item_report_id'), 'compliance_report_item', ['report_id'], unique=False)
    op.create_index(op.f('ix_compliance_report_item_tenant_id'), 'compliance_report_item', ['tenant_id'], unique=False)
    op.create_table('tds_deduction_record',
    sa.Column('retailer_id', sa.UUID(), nullable=False),
    sa.Column('assessment_year', sa.String(length=20), nullable=False),
    sa.Column('section_code', sa.String(length=30), nullable=False),
    sa.Column('gross_payment_amount', sa.Float(), nullable=False),
    sa.Column('tds_rate_pct', sa.Float(), nullable=False),
    sa.Column('tds_amount', sa.Float(), nullable=False),
    sa.Column('filing_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tds_deduction_record_company_id'), 'tds_deduction_record', ['company_id'], unique=False)
    op.create_index(op.f('ix_tds_deduction_record_is_active'), 'tds_deduction_record', ['is_active'], unique=False)
    op.create_index(op.f('ix_tds_deduction_record_is_deleted'), 'tds_deduction_record', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tds_deduction_record_organization_id'), 'tds_deduction_record', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tds_deduction_record_public_id'), 'tds_deduction_record', ['public_id'], unique=True)
    op.create_index(op.f('ix_tds_deduction_record_retailer_id'), 'tds_deduction_record', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_tds_deduction_record_tenant_id'), 'tds_deduction_record', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tds_deduction_record_tenant_id'), table_name='tds_deduction_record')
    op.drop_index(op.f('ix_tds_deduction_record_retailer_id'), table_name='tds_deduction_record')
    op.drop_index(op.f('ix_tds_deduction_record_public_id'), table_name='tds_deduction_record')
    op.drop_index(op.f('ix_tds_deduction_record_organization_id'), table_name='tds_deduction_record')
    op.drop_index(op.f('ix_tds_deduction_record_is_deleted'), table_name='tds_deduction_record')
    op.drop_index(op.f('ix_tds_deduction_record_is_active'), table_name='tds_deduction_record')
    op.drop_index(op.f('ix_tds_deduction_record_company_id'), table_name='tds_deduction_record')
    op.drop_table('tds_deduction_record')
    op.drop_index(op.f('ix_compliance_report_item_tenant_id'), table_name='compliance_report_item')
    op.drop_index(op.f('ix_compliance_report_item_report_id'), table_name='compliance_report_item')
    op.drop_index(op.f('ix_compliance_report_item_public_id'), table_name='compliance_report_item')
    op.drop_index(op.f('ix_compliance_report_item_organization_id'), table_name='compliance_report_item')
    op.drop_index(op.f('ix_compliance_report_item_is_deleted'), table_name='compliance_report_item')
    op.drop_index(op.f('ix_compliance_report_item_is_active'), table_name='compliance_report_item')
    op.drop_index(op.f('ix_compliance_report_item_company_id'), table_name='compliance_report_item')
    op.drop_table('compliance_report_item')
    op.drop_index(op.f('ix_tenant_configuration_tenant_id'), table_name='tenant_configuration')
    op.drop_index(op.f('ix_tenant_configuration_public_id'), table_name='tenant_configuration')
    op.drop_index(op.f('ix_tenant_configuration_organization_id'), table_name='tenant_configuration')
    op.drop_index(op.f('ix_tenant_configuration_is_deleted'), table_name='tenant_configuration')
    op.drop_index(op.f('ix_tenant_configuration_is_active'), table_name='tenant_configuration')
    op.drop_index(op.f('ix_tenant_configuration_config_key'), table_name='tenant_configuration')
    op.drop_index(op.f('ix_tenant_configuration_company_id'), table_name='tenant_configuration')
    op.drop_table('tenant_configuration')
    op.drop_index(op.f('ix_system_health_log_tenant_id'), table_name='system_health_log')
    op.drop_index(op.f('ix_system_health_log_public_id'), table_name='system_health_log')
    op.drop_index(op.f('ix_system_health_log_organization_id'), table_name='system_health_log')
    op.drop_index(op.f('ix_system_health_log_is_deleted'), table_name='system_health_log')
    op.drop_index(op.f('ix_system_health_log_is_active'), table_name='system_health_log')
    op.drop_index(op.f('ix_system_health_log_component_name'), table_name='system_health_log')
    op.drop_index(op.f('ix_system_health_log_company_id'), table_name='system_health_log')
    op.drop_table('system_health_log')
    op.drop_index(op.f('ix_system_alert_policy_tenant_id'), table_name='system_alert_policy')
    op.drop_index(op.f('ix_system_alert_policy_public_id'), table_name='system_alert_policy')
    op.drop_index(op.f('ix_system_alert_policy_organization_id'), table_name='system_alert_policy')
    op.drop_index(op.f('ix_system_alert_policy_is_deleted'), table_name='system_alert_policy')
    op.drop_index(op.f('ix_system_alert_policy_is_active'), table_name='system_alert_policy')
    op.drop_index(op.f('ix_system_alert_policy_company_id'), table_name='system_alert_policy')
    op.drop_table('system_alert_policy')
    op.drop_index(op.f('ix_gst_filing_summary_tenant_id'), table_name='gst_filing_summary')
    op.drop_index(op.f('ix_gst_filing_summary_tax_period'), table_name='gst_filing_summary')
    op.drop_index(op.f('ix_gst_filing_summary_public_id'), table_name='gst_filing_summary')
    op.drop_index(op.f('ix_gst_filing_summary_organization_id'), table_name='gst_filing_summary')
    op.drop_index(op.f('ix_gst_filing_summary_is_deleted'), table_name='gst_filing_summary')
    op.drop_index(op.f('ix_gst_filing_summary_is_active'), table_name='gst_filing_summary')
    op.drop_index(op.f('ix_gst_filing_summary_company_id'), table_name='gst_filing_summary')
    op.drop_table('gst_filing_summary')
    op.drop_index(op.f('ix_compliance_report_tenant_id'), table_name='compliance_report')
    op.drop_index(op.f('ix_compliance_report_tax_period'), table_name='compliance_report')
    op.drop_index(op.f('ix_compliance_report_status'), table_name='compliance_report')
    op.drop_index(op.f('ix_compliance_report_report_type'), table_name='compliance_report')
    op.drop_index(op.f('ix_compliance_report_report_number'), table_name='compliance_report')
    op.drop_index(op.f('ix_compliance_report_public_id'), table_name='compliance_report')
    op.drop_index(op.f('ix_compliance_report_organization_id'), table_name='compliance_report')
    op.drop_index(op.f('ix_compliance_report_is_deleted'), table_name='compliance_report')
    op.drop_index(op.f('ix_compliance_report_is_active'), table_name='compliance_report')
    op.drop_index(op.f('ix_compliance_report_company_id'), table_name='compliance_report')
    op.drop_table('compliance_report')
    op.drop_index(op.f('ix_audit_export_job_tenant_id'), table_name='audit_export_job')
    op.drop_index(op.f('ix_audit_export_job_status'), table_name='audit_export_job')
    op.drop_index(op.f('ix_audit_export_job_public_id'), table_name='audit_export_job')
    op.drop_index(op.f('ix_audit_export_job_organization_id'), table_name='audit_export_job')
    op.drop_index(op.f('ix_audit_export_job_is_deleted'), table_name='audit_export_job')
    op.drop_index(op.f('ix_audit_export_job_is_active'), table_name='audit_export_job')
    op.drop_index(op.f('ix_audit_export_job_export_reference'), table_name='audit_export_job')
    op.drop_index(op.f('ix_audit_export_job_company_id'), table_name='audit_export_job')
    op.drop_table('audit_export_job')
    # ### end Alembic commands ###
