"""epic_001_002_unified_schema

Revision ID: 3f03ac5d344d
Revises: None
Create Date: 2026-07-28 09:32:06.622447

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f03ac5d344d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_admin_user_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_admin_user_tenant_username')
    )
    op.create_index(op.f('ix_admin_user_company_id'), 'admin_user', ['company_id'], unique=False)
    op.create_index(op.f('ix_admin_user_email'), 'admin_user', ['email'], unique=False)
    op.create_index(op.f('ix_admin_user_is_active'), 'admin_user', ['is_active'], unique=False)
    op.create_index(op.f('ix_admin_user_is_deleted'), 'admin_user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_admin_user_organization_id'), 'admin_user', ['organization_id'], unique=False)
    op.create_index(op.f('ix_admin_user_public_id'), 'admin_user', ['public_id'], unique=True)
    op.create_index(op.f('ix_admin_user_tenant_id'), 'admin_user', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_admin_user_username'), 'admin_user', ['username'], unique=False)
    op.create_table('audit_log',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_company_id'), 'audit_log', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_public_id'), 'audit_log', ['public_id'], unique=True)
    op.create_index(op.f('ix_audit_log_resource_type'), 'audit_log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('permission',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_code'), 'permission', ['code'], unique=True)
    op.create_index(op.f('ix_permission_company_id'), 'permission', ['company_id'], unique=False)
    op.create_index(op.f('ix_permission_is_active'), 'permission', ['is_active'], unique=False)
    op.create_index(op.f('ix_permission_is_deleted'), 'permission', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_permission_module'), 'permission', ['module'], unique=False)
    op.create_index(op.f('ix_permission_organization_id'), 'permission', ['organization_id'], unique=False)
    op.create_index(op.f('ix_permission_public_id'), 'permission', ['public_id'], unique=True)
    op.create_index(op.f('ix_permission_tenant_id'), 'permission', ['tenant_id'], unique=False)
    op.create_table('role',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_role_tenant_code')
    )
    op.create_index(op.f('ix_role_code'), 'role', ['code'], unique=False)
    op.create_index(op.f('ix_role_company_id'), 'role', ['company_id'], unique=False)
    op.create_index(op.f('ix_role_is_active'), 'role', ['is_active'], unique=False)
    op.create_index(op.f('ix_role_is_deleted'), 'role', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_role_organization_id'), 'role', ['organization_id'], unique=False)
    op.create_index(op.f('ix_role_public_id'), 'role', ['public_id'], unique=True)
    op.create_index(op.f('ix_role_tenant_id'), 'role', ['tenant_id'], unique=False)
    op.create_table('system_configuration',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_system_config_tenant_key')
    )
    op.create_index(op.f('ix_system_configuration_company_id'), 'system_configuration', ['company_id'], unique=False)
    op.create_index(op.f('ix_system_configuration_is_active'), 'system_configuration', ['is_active'], unique=False)
    op.create_index(op.f('ix_system_configuration_is_deleted'), 'system_configuration', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_system_configuration_key'), 'system_configuration', ['key'], unique=False)
    op.create_index(op.f('ix_system_configuration_organization_id'), 'system_configuration', ['organization_id'], unique=False)
    op.create_index(op.f('ix_system_configuration_public_id'), 'system_configuration', ['public_id'], unique=True)
    op.create_index(op.f('ix_system_configuration_tenant_id'), 'system_configuration', ['tenant_id'], unique=False)
    op.create_table('tenant',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_code'), 'tenant', ['code'], unique=True)
    op.create_index(op.f('ix_tenant_company_id'), 'tenant', ['company_id'], unique=False)
    op.create_index(op.f('ix_tenant_is_active'), 'tenant', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenant_is_deleted'), 'tenant', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tenant_organization_id'), 'tenant', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tenant_public_id'), 'tenant', ['public_id'], unique=True)
    op.create_index(op.f('ix_tenant_tenant_id'), 'tenant', ['tenant_id'], unique=False)
    op.create_table('api_key',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_company_id'), 'api_key', ['company_id'], unique=False)
    op.create_index(op.f('ix_api_key_is_deleted'), 'api_key', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_api_key_key_prefix'), 'api_key', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_key_organization_id'), 'api_key', ['organization_id'], unique=False)
    op.create_index(op.f('ix_api_key_public_id'), 'api_key', ['public_id'], unique=True)
    op.create_index(op.f('ix_api_key_tenant_id'), 'api_key', ['tenant_id'], unique=False)
    op.create_table('company',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_code', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('tenant_code', sa.String(length=50), nullable=False),
    sa.Column('company_type', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('business_category', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('cin_number', sa.String(length=21), nullable=True),
    sa.Column('msme_number', sa.String(length=50), nullable=True),
    sa.Column('tan_number', sa.String(length=10), nullable=True),
    sa.Column('fssai_number', sa.String(length=20), nullable=True),
    sa.Column('business_registration_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'company_code', name='uq_company_tenant_code')
    )
    op.create_index(op.f('ix_company_cin_number'), 'company', ['cin_number'], unique=False)
    op.create_index(op.f('ix_company_company_code'), 'company', ['company_code'], unique=False)
    op.create_index(op.f('ix_company_company_id'), 'company', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_gst_number'), 'company', ['gst_number'], unique=False)
    op.create_index(op.f('ix_company_is_active'), 'company', ['is_active'], unique=False)
    op.create_index(op.f('ix_company_is_deleted'), 'company', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_organization_id'), 'company', ['organization_id'], unique=False)
    op.create_index(op.f('ix_company_pan_number'), 'company', ['pan_number'], unique=False)
    op.create_index(op.f('ix_company_public_id'), 'company', ['public_id'], unique=True)
    op.create_index(op.f('ix_company_status'), 'company', ['status'], unique=False)
    op.create_index(op.f('ix_company_tenant_code'), 'company', ['tenant_code'], unique=False)
    op.create_index(op.f('ix_company_tenant_id'), 'company', ['tenant_id'], unique=False)
    op.create_table('password_reset_token',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_token_company_id'), 'password_reset_token', ['company_id'], unique=False)
    op.create_index(op.f('ix_password_reset_token_is_active'), 'password_reset_token', ['is_active'], unique=False)
    op.create_index(op.f('ix_password_reset_token_is_deleted'), 'password_reset_token', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_password_reset_token_organization_id'), 'password_reset_token', ['organization_id'], unique=False)
    op.create_index(op.f('ix_password_reset_token_public_id'), 'password_reset_token', ['public_id'], unique=True)
    op.create_index(op.f('ix_password_reset_token_tenant_id'), 'password_reset_token', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_password_reset_token_token_hash'), 'password_reset_token', ['token_hash'], unique=True)
    op.create_table('role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permission_company_id'), 'role_permission', ['company_id'], unique=False)
    op.create_index(op.f('ix_role_permission_is_active'), 'role_permission', ['is_active'], unique=False)
    op.create_index(op.f('ix_role_permission_is_deleted'), 'role_permission', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_role_permission_organization_id'), 'role_permission', ['organization_id'], unique=False)
    op.create_index(op.f('ix_role_permission_public_id'), 'role_permission', ['public_id'], unique=True)
    op.create_index(op.f('ix_role_permission_tenant_id'), 'role_permission', ['tenant_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_role_company_id'), 'user_role', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_role_is_active'), 'user_role', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_role_is_deleted'), 'user_role', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_role_organization_id'), 'user_role', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_role_public_id'), 'user_role', ['public_id'], unique=True)
    op.create_index(op.f('ix_user_role_tenant_id'), 'user_role', ['tenant_id'], unique=False)
    op.create_table('user_session',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_jti', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_session_company_id'), 'user_session', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_session_is_active'), 'user_session', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_session_is_deleted'), 'user_session', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_session_is_revoked'), 'user_session', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_user_session_organization_id'), 'user_session', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_session_public_id'), 'user_session', ['public_id'], unique=True)
    op.create_index(op.f('ix_user_session_tenant_id'), 'user_session', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_session_token_jti'), 'user_session', ['token_jti'], unique=True)
    op.create_table('company_address',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_address_company_id'), 'company_address', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_address_is_active'), 'company_address', ['is_active'], unique=False)
    op.create_index(op.f('ix_company_address_is_deleted'), 'company_address', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_address_organization_id'), 'company_address', ['organization_id'], unique=False)
    op.create_index(op.f('ix_company_address_public_id'), 'company_address', ['public_id'], unique=True)
    op.create_index(op.f('ix_company_address_tenant_id'), 'company_address', ['tenant_id'], unique=False)
    op.create_table('company_approval',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('reviewer_email', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_approval_company_id'), 'company_approval', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_approval_is_active'), 'company_approval', ['is_active'], unique=False)
    op.create_index(op.f('ix_company_approval_is_deleted'), 'company_approval', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_approval_organization_id'), 'company_approval', ['organization_id'], unique=False)
    op.create_index(op.f('ix_company_approval_public_id'), 'company_approval', ['public_id'], unique=True)
    op.create_index(op.f('ix_company_approval_status'), 'company_approval', ['status'], unique=False)
    op.create_index(op.f('ix_company_approval_tenant_id'), 'company_approval', ['tenant_id'], unique=False)
    op.create_table('company_bank',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('settlement_bank_name', sa.String(length=150), nullable=False),
    sa.Column('account_holder', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('ifsc', sa.String(length=11), nullable=False),
    sa.Column('branch', sa.String(length=150), nullable=True),
    sa.Column('cancelled_cheque_url', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_bank_company_id'), 'company_bank', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_bank_is_active'), 'company_bank', ['is_active'], unique=False)
    op.create_index(op.f('ix_company_bank_is_deleted'), 'company_bank', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_bank_organization_id'), 'company_bank', ['organization_id'], unique=False)
    op.create_index(op.f('ix_company_bank_public_id'), 'company_bank', ['public_id'], unique=True)
    op.create_index(op.f('ix_company_bank_tenant_id'), 'company_bank', ['tenant_id'], unique=False)
    op.create_table('company_branding',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('primary_colour', sa.String(length=20), nullable=False),
    sa.Column('secondary_colour', sa.String(length=20), nullable=False),
    sa.Column('email_template', sa.Text(), nullable=True),
    sa.Column('sms_template', sa.Text(), nullable=True),
    sa.Column('invoice_header', sa.Text(), nullable=True),
    sa.Column('receipt_footer', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_branding_company_id'), 'company_branding', ['company_id'], unique=True)
    op.create_index(op.f('ix_company_branding_is_active'), 'company_branding', ['is_active'], unique=False)
    op.create_index(op.f('ix_company_branding_is_deleted'), 'company_branding', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_branding_organization_id'), 'company_branding', ['organization_id'], unique=False)
    op.create_index(op.f('ix_company_branding_public_id'), 'company_branding', ['public_id'], unique=True)
    op.create_index(op.f('ix_company_branding_tenant_id'), 'company_branding', ['tenant_id'], unique=False)
    op.create_table('company_configuration',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_configuration_company_id'), 'company_configuration', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_configuration_is_active'), 'company_configuration', ['is_active'], unique=False)
    op.create_index(op.f('ix_company_configuration_is_deleted'), 'company_configuration', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_configuration_organization_id'), 'company_configuration', ['organization_id'], unique=False)
    op.create_index(op.f('ix_company_configuration_public_id'), 'company_configuration', ['public_id'], unique=True)
    op.create_index(op.f('ix_company_configuration_tenant_id'), 'company_configuration', ['tenant_id'], unique=False)
    op.create_table('company_contact',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('primary_contact', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('support_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_contact_company_id'), 'company_contact', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_contact_email'), 'company_contact', ['email'], unique=False)
    op.create_index(op.f('ix_company_contact_is_active'), 'company_contact', ['is_active'], unique=False)
    op.create_index(op.f('ix_company_contact_is_deleted'), 'company_contact', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_contact_mobile'), 'company_contact', ['mobile'], unique=False)
    op.create_index(op.f('ix_company_contact_organization_id'), 'company_contact', ['organization_id'], unique=False)
    op.create_index(op.f('ix_company_contact_public_id'), 'company_contact', ['public_id'], unique=True)
    op.create_index(op.f('ix_company_contact_tenant_id'), 'company_contact', ['tenant_id'], unique=False)
    op.create_table('company_document',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_document_company_id'), 'company_document', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_document_is_active'), 'company_document', ['is_active'], unique=False)
    op.create_index(op.f('ix_company_document_is_deleted'), 'company_document', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_document_organization_id'), 'company_document', ['organization_id'], unique=False)
    op.create_index(op.f('ix_company_document_public_id'), 'company_document', ['public_id'], unique=True)
    op.create_index(op.f('ix_company_document_tenant_id'), 'company_document', ['tenant_id'], unique=False)
    op.create_table('company_setting',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('number_format', sa.String(length=20), nullable=False),
    sa.Column('financial_year_start', sa.String(length=10), nullable=False),
    sa.Column('gst_enabled', sa.Boolean(), nullable=False),
    sa.Column('tds_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_settlement', sa.Boolean(), nullable=False),
    sa.Column('auto_payout', sa.Boolean(), nullable=False),
    sa.Column('approval_workflow', sa.Boolean(), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('otp_expiry_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_setting_company_id'), 'company_setting', ['company_id'], unique=True)
    op.create_index(op.f('ix_company_setting_is_active'), 'company_setting', ['is_active'], unique=False)
    op.create_index(op.f('ix_company_setting_is_deleted'), 'company_setting', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_setting_organization_id'), 'company_setting', ['organization_id'], unique=False)
    op.create_index(op.f('ix_company_setting_public_id'), 'company_setting', ['public_id'], unique=True)
    op.create_index(op.f('ix_company_setting_tenant_id'), 'company_setting', ['tenant_id'], unique=False)
    op.create_table('company_status_history',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=False),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by_email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_status_history_company_id'), 'company_status_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_status_history_is_active'), 'company_status_history', ['is_active'], unique=False)
    op.create_index(op.f('ix_company_status_history_is_deleted'), 'company_status_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_status_history_organization_id'), 'company_status_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_company_status_history_public_id'), 'company_status_history', ['public_id'], unique=True)
    op.create_index(op.f('ix_company_status_history_tenant_id'), 'company_status_history', ['tenant_id'], unique=False)
    op.create_table('company_subscription',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('maximum_retailers', sa.Integer(), nullable=False),
    sa.Column('maximum_machines', sa.Integer(), nullable=False),
    sa.Column('maximum_admin_users', sa.Integer(), nullable=False),
    sa.Column('storage_limit_gb', sa.Integer(), nullable=False),
    sa.Column('api_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_subscription_company_id'), 'company_subscription', ['company_id'], unique=True)
    op.create_index(op.f('ix_company_subscription_is_active'), 'company_subscription', ['is_active'], unique=False)
    op.create_index(op.f('ix_company_subscription_is_deleted'), 'company_subscription', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_subscription_organization_id'), 'company_subscription', ['organization_id'], unique=False)
    op.create_index(op.f('ix_company_subscription_public_id'), 'company_subscription', ['public_id'], unique=True)
    op.create_index(op.f('ix_company_subscription_tenant_id'), 'company_subscription', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_subscription_tenant_id'), table_name='company_subscription')
    op.drop_index(op.f('ix_company_subscription_public_id'), table_name='company_subscription')
    op.drop_index(op.f('ix_company_subscription_organization_id'), table_name='company_subscription')
    op.drop_index(op.f('ix_company_subscription_is_deleted'), table_name='company_subscription')
    op.drop_index(op.f('ix_company_subscription_is_active'), table_name='company_subscription')
    op.drop_index(op.f('ix_company_subscription_company_id'), table_name='company_subscription')
    op.drop_table('company_subscription')
    op.drop_index(op.f('ix_company_status_history_tenant_id'), table_name='company_status_history')
    op.drop_index(op.f('ix_company_status_history_public_id'), table_name='company_status_history')
    op.drop_index(op.f('ix_company_status_history_organization_id'), table_name='company_status_history')
    op.drop_index(op.f('ix_company_status_history_is_deleted'), table_name='company_status_history')
    op.drop_index(op.f('ix_company_status_history_is_active'), table_name='company_status_history')
    op.drop_index(op.f('ix_company_status_history_company_id'), table_name='company_status_history')
    op.drop_table('company_status_history')
    op.drop_index(op.f('ix_company_setting_tenant_id'), table_name='company_setting')
    op.drop_index(op.f('ix_company_setting_public_id'), table_name='company_setting')
    op.drop_index(op.f('ix_company_setting_organization_id'), table_name='company_setting')
    op.drop_index(op.f('ix_company_setting_is_deleted'), table_name='company_setting')
    op.drop_index(op.f('ix_company_setting_is_active'), table_name='company_setting')
    op.drop_index(op.f('ix_company_setting_company_id'), table_name='company_setting')
    op.drop_table('company_setting')
    op.drop_index(op.f('ix_company_document_tenant_id'), table_name='company_document')
    op.drop_index(op.f('ix_company_document_public_id'), table_name='company_document')
    op.drop_index(op.f('ix_company_document_organization_id'), table_name='company_document')
    op.drop_index(op.f('ix_company_document_is_deleted'), table_name='company_document')
    op.drop_index(op.f('ix_company_document_is_active'), table_name='company_document')
    op.drop_index(op.f('ix_company_document_company_id'), table_name='company_document')
    op.drop_table('company_document')
    op.drop_index(op.f('ix_company_contact_tenant_id'), table_name='company_contact')
    op.drop_index(op.f('ix_company_contact_public_id'), table_name='company_contact')
    op.drop_index(op.f('ix_company_contact_organization_id'), table_name='company_contact')
    op.drop_index(op.f('ix_company_contact_mobile'), table_name='company_contact')
    op.drop_index(op.f('ix_company_contact_is_deleted'), table_name='company_contact')
    op.drop_index(op.f('ix_company_contact_is_active'), table_name='company_contact')
    op.drop_index(op.f('ix_company_contact_email'), table_name='company_contact')
    op.drop_index(op.f('ix_company_contact_company_id'), table_name='company_contact')
    op.drop_table('company_contact')
    op.drop_index(op.f('ix_company_configuration_tenant_id'), table_name='company_configuration')
    op.drop_index(op.f('ix_company_configuration_public_id'), table_name='company_configuration')
    op.drop_index(op.f('ix_company_configuration_organization_id'), table_name='company_configuration')
    op.drop_index(op.f('ix_company_configuration_is_deleted'), table_name='company_configuration')
    op.drop_index(op.f('ix_company_configuration_is_active'), table_name='company_configuration')
    op.drop_index(op.f('ix_company_configuration_company_id'), table_name='company_configuration')
    op.drop_table('company_configuration')
    op.drop_index(op.f('ix_company_branding_tenant_id'), table_name='company_branding')
    op.drop_index(op.f('ix_company_branding_public_id'), table_name='company_branding')
    op.drop_index(op.f('ix_company_branding_organization_id'), table_name='company_branding')
    op.drop_index(op.f('ix_company_branding_is_deleted'), table_name='company_branding')
    op.drop_index(op.f('ix_company_branding_is_active'), table_name='company_branding')
    op.drop_index(op.f('ix_company_branding_company_id'), table_name='company_branding')
    op.drop_table('company_branding')
    op.drop_index(op.f('ix_company_bank_tenant_id'), table_name='company_bank')
    op.drop_index(op.f('ix_company_bank_public_id'), table_name='company_bank')
    op.drop_index(op.f('ix_company_bank_organization_id'), table_name='company_bank')
    op.drop_index(op.f('ix_company_bank_is_deleted'), table_name='company_bank')
    op.drop_index(op.f('ix_company_bank_is_active'), table_name='company_bank')
    op.drop_index(op.f('ix_company_bank_company_id'), table_name='company_bank')
    op.drop_table('company_bank')
    op.drop_index(op.f('ix_company_approval_tenant_id'), table_name='company_approval')
    op.drop_index(op.f('ix_company_approval_status'), table_name='company_approval')
    op.drop_index(op.f('ix_company_approval_public_id'), table_name='company_approval')
    op.drop_index(op.f('ix_company_approval_organization_id'), table_name='company_approval')
    op.drop_index(op.f('ix_company_approval_is_deleted'), table_name='company_approval')
    op.drop_index(op.f('ix_company_approval_is_active'), table_name='company_approval')
    op.drop_index(op.f('ix_company_approval_company_id'), table_name='company_approval')
    op.drop_table('company_approval')
    op.drop_index(op.f('ix_company_address_tenant_id'), table_name='company_address')
    op.drop_index(op.f('ix_company_address_public_id'), table_name='company_address')
    op.drop_index(op.f('ix_company_address_organization_id'), table_name='company_address')
    op.drop_index(op.f('ix_company_address_is_deleted'), table_name='company_address')
    op.drop_index(op.f('ix_company_address_is_active'), table_name='company_address')
    op.drop_index(op.f('ix_company_address_company_id'), table_name='company_address')
    op.drop_table('company_address')
    op.drop_index(op.f('ix_user_session_token_jti'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_tenant_id'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_public_id'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_organization_id'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_is_revoked'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_is_deleted'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_is_active'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_company_id'), table_name='user_session')
    op.drop_table('user_session')
    op.drop_index(op.f('ix_user_role_tenant_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_public_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_organization_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_is_deleted'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_is_active'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_company_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_role_permission_tenant_id'), table_name='role_permission')
    op.drop_index(op.f('ix_role_permission_public_id'), table_name='role_permission')
    op.drop_index(op.f('ix_role_permission_organization_id'), table_name='role_permission')
    op.drop_index(op.f('ix_role_permission_is_deleted'), table_name='role_permission')
    op.drop_index(op.f('ix_role_permission_is_active'), table_name='role_permission')
    op.drop_index(op.f('ix_role_permission_company_id'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_password_reset_token_token_hash'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_tenant_id'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_public_id'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_organization_id'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_is_deleted'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_is_active'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_company_id'), table_name='password_reset_token')
    op.drop_table('password_reset_token')
    op.drop_index(op.f('ix_company_tenant_id'), table_name='company')
    op.drop_index(op.f('ix_company_tenant_code'), table_name='company')
    op.drop_index(op.f('ix_company_status'), table_name='company')
    op.drop_index(op.f('ix_company_public_id'), table_name='company')
    op.drop_index(op.f('ix_company_pan_number'), table_name='company')
    op.drop_index(op.f('ix_company_organization_id'), table_name='company')
    op.drop_index(op.f('ix_company_is_deleted'), table_name='company')
    op.drop_index(op.f('ix_company_is_active'), table_name='company')
    op.drop_index(op.f('ix_company_gst_number'), table_name='company')
    op.drop_index(op.f('ix_company_company_id'), table_name='company')
    op.drop_index(op.f('ix_company_company_code'), table_name='company')
    op.drop_index(op.f('ix_company_cin_number'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_api_key_tenant_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_public_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_organization_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_key_prefix'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_is_deleted'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_company_id'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_index(op.f('ix_tenant_tenant_id'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_public_id'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_organization_id'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_is_deleted'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_is_active'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_company_id'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_code'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_system_configuration_tenant_id'), table_name='system_configuration')
    op.drop_index(op.f('ix_system_configuration_public_id'), table_name='system_configuration')
    op.drop_index(op.f('ix_system_configuration_organization_id'), table_name='system_configuration')
    op.drop_index(op.f('ix_system_configuration_key'), table_name='system_configuration')
    op.drop_index(op.f('ix_system_configuration_is_deleted'), table_name='system_configuration')
    op.drop_index(op.f('ix_system_configuration_is_active'), table_name='system_configuration')
    op.drop_index(op.f('ix_system_configuration_company_id'), table_name='system_configuration')
    op.drop_table('system_configuration')
    op.drop_index(op.f('ix_role_tenant_id'), table_name='role')
    op.drop_index(op.f('ix_role_public_id'), table_name='role')
    op.drop_index(op.f('ix_role_organization_id'), table_name='role')
    op.drop_index(op.f('ix_role_is_deleted'), table_name='role')
    op.drop_index(op.f('ix_role_is_active'), table_name='role')
    op.drop_index(op.f('ix_role_company_id'), table_name='role')
    op.drop_index(op.f('ix_role_code'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_tenant_id'), table_name='permission')
    op.drop_index(op.f('ix_permission_public_id'), table_name='permission')
    op.drop_index(op.f('ix_permission_organization_id'), table_name='permission')
    op.drop_index(op.f('ix_permission_module'), table_name='permission')
    op.drop_index(op.f('ix_permission_is_deleted'), table_name='permission')
    op.drop_index(op.f('ix_permission_is_active'), table_name='permission')
    op.drop_index(op.f('ix_permission_company_id'), table_name='permission')
    op.drop_index(op.f('ix_permission_code'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_resource_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_public_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_company_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_admin_user_username'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_tenant_id'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_public_id'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_organization_id'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_is_deleted'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_is_active'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_email'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_company_id'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
