"""epic_006_settlement_schema

Revision ID: 402ca8d1a0be
Revises: '8742dae676d0'
Create Date: 2026-07-28 17:39:48.948399

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402ca8d1a0be'
down_revision: Union[str, None] = '8742dae676d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mdr_fee_plan',
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=False),
    sa.Column('mdr_percentage', sa.Float(), nullable=False),
    sa.Column('fixed_fee', sa.Float(), nullable=False),
    sa.Column('gst_percentage', sa.Float(), nullable=False),
    sa.Column('distributor_share_pct', sa.Float(), nullable=False),
    sa.Column('sd_share_pct', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mdr_fee_plan_company_id'), 'mdr_fee_plan', ['company_id'], unique=False)
    op.create_index(op.f('ix_mdr_fee_plan_is_active'), 'mdr_fee_plan', ['is_active'], unique=False)
    op.create_index(op.f('ix_mdr_fee_plan_is_deleted'), 'mdr_fee_plan', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_mdr_fee_plan_organization_id'), 'mdr_fee_plan', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mdr_fee_plan_payment_mode'), 'mdr_fee_plan', ['payment_mode'], unique=False)
    op.create_index(op.f('ix_mdr_fee_plan_public_id'), 'mdr_fee_plan', ['public_id'], unique=True)
    op.create_index(op.f('ix_mdr_fee_plan_tenant_id'), 'mdr_fee_plan', ['tenant_id'], unique=False)
    op.create_table('reconciliation_report',
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('gateway_volume', sa.Float(), nullable=False),
    sa.Column('settled_volume', sa.Float(), nullable=False),
    sa.Column('discrepancy_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_report_company_id'), 'reconciliation_report', ['company_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_report_is_active'), 'reconciliation_report', ['is_active'], unique=False)
    op.create_index(op.f('ix_reconciliation_report_is_deleted'), 'reconciliation_report', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_reconciliation_report_organization_id'), 'reconciliation_report', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_report_public_id'), 'reconciliation_report', ['public_id'], unique=True)
    op.create_index(op.f('ix_reconciliation_report_report_date'), 'reconciliation_report', ['report_date'], unique=False)
    op.create_index(op.f('ix_reconciliation_report_tenant_id'), 'reconciliation_report', ['tenant_id'], unique=False)
    op.create_table('settlement_batch',
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('batch_date', sa.Date(), nullable=False),
    sa.Column('gross_volume', sa.Float(), nullable=False),
    sa.Column('total_mdr', sa.Float(), nullable=False),
    sa.Column('total_gst', sa.Float(), nullable=False),
    sa.Column('net_payout_amount', sa.Float(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'batch_number', name='uq_batch_tenant_number')
    )
    op.create_index(op.f('ix_settlement_batch_batch_number'), 'settlement_batch', ['batch_number'], unique=False)
    op.create_index(op.f('ix_settlement_batch_company_id'), 'settlement_batch', ['company_id'], unique=False)
    op.create_index(op.f('ix_settlement_batch_is_active'), 'settlement_batch', ['is_active'], unique=False)
    op.create_index(op.f('ix_settlement_batch_is_deleted'), 'settlement_batch', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_settlement_batch_organization_id'), 'settlement_batch', ['organization_id'], unique=False)
    op.create_index(op.f('ix_settlement_batch_public_id'), 'settlement_batch', ['public_id'], unique=True)
    op.create_index(op.f('ix_settlement_batch_status'), 'settlement_batch', ['status'], unique=False)
    op.create_index(op.f('ix_settlement_batch_tenant_id'), 'settlement_batch', ['tenant_id'], unique=False)
    op.create_table('payout_instruction',
    sa.Column('payout_reference', sa.String(length=50), nullable=False),
    sa.Column('retailer_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_number', sa.String(length=50), nullable=False),
    sa.Column('ifsc', sa.String(length=11), nullable=False),
    sa.Column('payout_method', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('utr_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'payout_reference', name='uq_payout_tenant_reference')
    )
    op.create_index(op.f('ix_payout_instruction_company_id'), 'payout_instruction', ['company_id'], unique=False)
    op.create_index(op.f('ix_payout_instruction_is_active'), 'payout_instruction', ['is_active'], unique=False)
    op.create_index(op.f('ix_payout_instruction_is_deleted'), 'payout_instruction', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payout_instruction_organization_id'), 'payout_instruction', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payout_instruction_payout_reference'), 'payout_instruction', ['payout_reference'], unique=False)
    op.create_index(op.f('ix_payout_instruction_public_id'), 'payout_instruction', ['public_id'], unique=True)
    op.create_index(op.f('ix_payout_instruction_retailer_id'), 'payout_instruction', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_payout_instruction_status'), 'payout_instruction', ['status'], unique=False)
    op.create_index(op.f('ix_payout_instruction_tenant_id'), 'payout_instruction', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_payout_instruction_utr_number'), 'payout_instruction', ['utr_number'], unique=False)
    op.create_table('transaction_record',
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('rrn', sa.String(length=30), nullable=False),
    sa.Column('auth_code', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=False),
    sa.Column('card_number_masked', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('settlement_status', sa.String(length=30), nullable=False),
    sa.Column('mapped_tid', sa.String(length=20), nullable=False),
    sa.Column('mapped_retailer_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mapped_retailer_id'], ['retailer.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'rrn', name='uq_txn_tenant_rrn'),
    sa.UniqueConstraint('tenant_id', 'transaction_id', name='uq_txn_tenant_txnid')
    )
    op.create_index(op.f('ix_transaction_record_company_id'), 'transaction_record', ['company_id'], unique=False)
    op.create_index(op.f('ix_transaction_record_is_active'), 'transaction_record', ['is_active'], unique=False)
    op.create_index(op.f('ix_transaction_record_is_deleted'), 'transaction_record', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_transaction_record_mapped_retailer_id'), 'transaction_record', ['mapped_retailer_id'], unique=False)
    op.create_index(op.f('ix_transaction_record_mapped_tid'), 'transaction_record', ['mapped_tid'], unique=False)
    op.create_index(op.f('ix_transaction_record_organization_id'), 'transaction_record', ['organization_id'], unique=False)
    op.create_index(op.f('ix_transaction_record_public_id'), 'transaction_record', ['public_id'], unique=True)
    op.create_index(op.f('ix_transaction_record_rrn'), 'transaction_record', ['rrn'], unique=False)
    op.create_index(op.f('ix_transaction_record_settlement_status'), 'transaction_record', ['settlement_status'], unique=False)
    op.create_index(op.f('ix_transaction_record_status'), 'transaction_record', ['status'], unique=False)
    op.create_index(op.f('ix_transaction_record_tenant_id'), 'transaction_record', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_transaction_record_transaction_id'), 'transaction_record', ['transaction_id'], unique=False)
    op.create_table('wallet_ledger',
    sa.Column('retailer_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('credit_amount', sa.Float(), nullable=False),
    sa.Column('debit_amount', sa.Float(), nullable=False),
    sa.Column('balance_before', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_ledger_company_id'), 'wallet_ledger', ['company_id'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_is_active'), 'wallet_ledger', ['is_active'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_is_deleted'), 'wallet_ledger', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_organization_id'), 'wallet_ledger', ['organization_id'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_public_id'), 'wallet_ledger', ['public_id'], unique=True)
    op.create_index(op.f('ix_wallet_ledger_retailer_id'), 'wallet_ledger', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_tenant_id'), 'wallet_ledger', ['tenant_id'], unique=False)
    op.create_table('settlement_item',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['settlement_batch.public_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction_record.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_item_batch_id'), 'settlement_item', ['batch_id'], unique=False)
    op.create_index(op.f('ix_settlement_item_company_id'), 'settlement_item', ['company_id'], unique=False)
    op.create_index(op.f('ix_settlement_item_is_active'), 'settlement_item', ['is_active'], unique=False)
    op.create_index(op.f('ix_settlement_item_is_deleted'), 'settlement_item', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_settlement_item_organization_id'), 'settlement_item', ['organization_id'], unique=False)
    op.create_index(op.f('ix_settlement_item_public_id'), 'settlement_item', ['public_id'], unique=True)
    op.create_index(op.f('ix_settlement_item_tenant_id'), 'settlement_item', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_settlement_item_transaction_id'), 'settlement_item', ['transaction_id'], unique=False)
    op.create_table('transaction_fee_split',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('mdr_fee', sa.Float(), nullable=False),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('total_deduction', sa.Float(), nullable=False),
    sa.Column('net_retailer_payout', sa.Float(), nullable=False),
    sa.Column('platform_retention', sa.Float(), nullable=False),
    sa.Column('distributor_commission', sa.Float(), nullable=False),
    sa.Column('sd_commission', sa.Float(), nullable=False),
    sa.Column('rm_commission', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction_record.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_fee_split_company_id'), 'transaction_fee_split', ['company_id'], unique=False)
    op.create_index(op.f('ix_transaction_fee_split_is_active'), 'transaction_fee_split', ['is_active'], unique=False)
    op.create_index(op.f('ix_transaction_fee_split_is_deleted'), 'transaction_fee_split', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_transaction_fee_split_organization_id'), 'transaction_fee_split', ['organization_id'], unique=False)
    op.create_index(op.f('ix_transaction_fee_split_public_id'), 'transaction_fee_split', ['public_id'], unique=True)
    op.create_index(op.f('ix_transaction_fee_split_tenant_id'), 'transaction_fee_split', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_transaction_fee_split_transaction_id'), 'transaction_fee_split', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_fee_split_transaction_id'), table_name='transaction_fee_split')
    op.drop_index(op.f('ix_transaction_fee_split_tenant_id'), table_name='transaction_fee_split')
    op.drop_index(op.f('ix_transaction_fee_split_public_id'), table_name='transaction_fee_split')
    op.drop_index(op.f('ix_transaction_fee_split_organization_id'), table_name='transaction_fee_split')
    op.drop_index(op.f('ix_transaction_fee_split_is_deleted'), table_name='transaction_fee_split')
    op.drop_index(op.f('ix_transaction_fee_split_is_active'), table_name='transaction_fee_split')
    op.drop_index(op.f('ix_transaction_fee_split_company_id'), table_name='transaction_fee_split')
    op.drop_table('transaction_fee_split')
    op.drop_index(op.f('ix_settlement_item_transaction_id'), table_name='settlement_item')
    op.drop_index(op.f('ix_settlement_item_tenant_id'), table_name='settlement_item')
    op.drop_index(op.f('ix_settlement_item_public_id'), table_name='settlement_item')
    op.drop_index(op.f('ix_settlement_item_organization_id'), table_name='settlement_item')
    op.drop_index(op.f('ix_settlement_item_is_deleted'), table_name='settlement_item')
    op.drop_index(op.f('ix_settlement_item_is_active'), table_name='settlement_item')
    op.drop_index(op.f('ix_settlement_item_company_id'), table_name='settlement_item')
    op.drop_index(op.f('ix_settlement_item_batch_id'), table_name='settlement_item')
    op.drop_table('settlement_item')
    op.drop_index(op.f('ix_wallet_ledger_tenant_id'), table_name='wallet_ledger')
    op.drop_index(op.f('ix_wallet_ledger_retailer_id'), table_name='wallet_ledger')
    op.drop_index(op.f('ix_wallet_ledger_public_id'), table_name='wallet_ledger')
    op.drop_index(op.f('ix_wallet_ledger_organization_id'), table_name='wallet_ledger')
    op.drop_index(op.f('ix_wallet_ledger_is_deleted'), table_name='wallet_ledger')
    op.drop_index(op.f('ix_wallet_ledger_is_active'), table_name='wallet_ledger')
    op.drop_index(op.f('ix_wallet_ledger_company_id'), table_name='wallet_ledger')
    op.drop_table('wallet_ledger')
    op.drop_index(op.f('ix_transaction_record_transaction_id'), table_name='transaction_record')
    op.drop_index(op.f('ix_transaction_record_tenant_id'), table_name='transaction_record')
    op.drop_index(op.f('ix_transaction_record_status'), table_name='transaction_record')
    op.drop_index(op.f('ix_transaction_record_settlement_status'), table_name='transaction_record')
    op.drop_index(op.f('ix_transaction_record_rrn'), table_name='transaction_record')
    op.drop_index(op.f('ix_transaction_record_public_id'), table_name='transaction_record')
    op.drop_index(op.f('ix_transaction_record_organization_id'), table_name='transaction_record')
    op.drop_index(op.f('ix_transaction_record_mapped_tid'), table_name='transaction_record')
    op.drop_index(op.f('ix_transaction_record_mapped_retailer_id'), table_name='transaction_record')
    op.drop_index(op.f('ix_transaction_record_is_deleted'), table_name='transaction_record')
    op.drop_index(op.f('ix_transaction_record_is_active'), table_name='transaction_record')
    op.drop_index(op.f('ix_transaction_record_company_id'), table_name='transaction_record')
    op.drop_table('transaction_record')
    op.drop_index(op.f('ix_payout_instruction_utr_number'), table_name='payout_instruction')
    op.drop_index(op.f('ix_payout_instruction_tenant_id'), table_name='payout_instruction')
    op.drop_index(op.f('ix_payout_instruction_status'), table_name='payout_instruction')
    op.drop_index(op.f('ix_payout_instruction_retailer_id'), table_name='payout_instruction')
    op.drop_index(op.f('ix_payout_instruction_public_id'), table_name='payout_instruction')
    op.drop_index(op.f('ix_payout_instruction_payout_reference'), table_name='payout_instruction')
    op.drop_index(op.f('ix_payout_instruction_organization_id'), table_name='payout_instruction')
    op.drop_index(op.f('ix_payout_instruction_is_deleted'), table_name='payout_instruction')
    op.drop_index(op.f('ix_payout_instruction_is_active'), table_name='payout_instruction')
    op.drop_index(op.f('ix_payout_instruction_company_id'), table_name='payout_instruction')
    op.drop_table('payout_instruction')
    op.drop_index(op.f('ix_settlement_batch_tenant_id'), table_name='settlement_batch')
    op.drop_index(op.f('ix_settlement_batch_status'), table_name='settlement_batch')
    op.drop_index(op.f('ix_settlement_batch_public_id'), table_name='settlement_batch')
    op.drop_index(op.f('ix_settlement_batch_organization_id'), table_name='settlement_batch')
    op.drop_index(op.f('ix_settlement_batch_is_deleted'), table_name='settlement_batch')
    op.drop_index(op.f('ix_settlement_batch_is_active'), table_name='settlement_batch')
    op.drop_index(op.f('ix_settlement_batch_company_id'), table_name='settlement_batch')
    op.drop_index(op.f('ix_settlement_batch_batch_number'), table_name='settlement_batch')
    op.drop_table('settlement_batch')
    op.drop_index(op.f('ix_reconciliation_report_tenant_id'), table_name='reconciliation_report')
    op.drop_index(op.f('ix_reconciliation_report_report_date'), table_name='reconciliation_report')
    op.drop_index(op.f('ix_reconciliation_report_public_id'), table_name='reconciliation_report')
    op.drop_index(op.f('ix_reconciliation_report_organization_id'), table_name='reconciliation_report')
    op.drop_index(op.f('ix_reconciliation_report_is_deleted'), table_name='reconciliation_report')
    op.drop_index(op.f('ix_reconciliation_report_is_active'), table_name='reconciliation_report')
    op.drop_index(op.f('ix_reconciliation_report_company_id'), table_name='reconciliation_report')
    op.drop_table('reconciliation_report')
    op.drop_index(op.f('ix_mdr_fee_plan_tenant_id'), table_name='mdr_fee_plan')
    op.drop_index(op.f('ix_mdr_fee_plan_public_id'), table_name='mdr_fee_plan')
    op.drop_index(op.f('ix_mdr_fee_plan_payment_mode'), table_name='mdr_fee_plan')
    op.drop_index(op.f('ix_mdr_fee_plan_organization_id'), table_name='mdr_fee_plan')
    op.drop_index(op.f('ix_mdr_fee_plan_is_deleted'), table_name='mdr_fee_plan')
    op.drop_index(op.f('ix_mdr_fee_plan_is_active'), table_name='mdr_fee_plan')
    op.drop_index(op.f('ix_mdr_fee_plan_company_id'), table_name='mdr_fee_plan')
    op.drop_table('mdr_fee_plan')
    # ### end Alembic commands ###
