"""epic_005_machine_schema

Revision ID: 8742dae676d0
Revises: '4b6f649c3409'
Create Date: 2026-07-28 17:34:42.029882

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8742dae676d0'
down_revision: Union[str, None] = '4b6f649c3409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_inventory',
    sa.Column('batch_stock_id', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('model_code', sa.String(length=50), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('warranty_expiry_date', sa.Date(), nullable=True),
    sa.Column('warehouse_location', sa.String(length=150), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_inventory_batch_stock_id'), 'machine_inventory', ['batch_stock_id'], unique=False)
    op.create_index(op.f('ix_machine_inventory_company_id'), 'machine_inventory', ['company_id'], unique=False)
    op.create_index(op.f('ix_machine_inventory_is_active'), 'machine_inventory', ['is_active'], unique=False)
    op.create_index(op.f('ix_machine_inventory_is_deleted'), 'machine_inventory', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_machine_inventory_organization_id'), 'machine_inventory', ['organization_id'], unique=False)
    op.create_index(op.f('ix_machine_inventory_public_id'), 'machine_inventory', ['public_id'], unique=True)
    op.create_index(op.f('ix_machine_inventory_tenant_id'), 'machine_inventory', ['tenant_id'], unique=False)
    op.create_table('machine_replacement',
    sa.Column('old_machine_id', sa.UUID(), nullable=False),
    sa.Column('old_serial_number', sa.String(length=100), nullable=False),
    sa.Column('new_machine_id', sa.UUID(), nullable=True),
    sa.Column('new_serial_number', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_by_email', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_replacement_company_id'), 'machine_replacement', ['company_id'], unique=False)
    op.create_index(op.f('ix_machine_replacement_is_active'), 'machine_replacement', ['is_active'], unique=False)
    op.create_index(op.f('ix_machine_replacement_is_deleted'), 'machine_replacement', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_machine_replacement_old_machine_id'), 'machine_replacement', ['old_machine_id'], unique=False)
    op.create_index(op.f('ix_machine_replacement_organization_id'), 'machine_replacement', ['organization_id'], unique=False)
    op.create_index(op.f('ix_machine_replacement_public_id'), 'machine_replacement', ['public_id'], unique=True)
    op.create_index(op.f('ix_machine_replacement_status'), 'machine_replacement', ['status'], unique=False)
    op.create_index(op.f('ix_machine_replacement_tenant_id'), 'machine_replacement', ['tenant_id'], unique=False)
    op.create_table('swipe_machine',
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('tid', sa.String(length=20), nullable=False),
    sa.Column('mid', sa.String(length=30), nullable=False),
    sa.Column('pos_model', sa.String(length=100), nullable=False),
    sa.Column('machine_type', sa.String(length=50), nullable=False),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('sim_iccid', sa.String(length=50), nullable=True),
    sa.Column('telecom_provider', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mapped_retailer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mapped_retailer_id'], ['retailer.public_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'serial_number', name='uq_machine_tenant_serial'),
    sa.UniqueConstraint('tenant_id', 'tid', name='uq_machine_tenant_tid')
    )
    op.create_index(op.f('ix_swipe_machine_company_id'), 'swipe_machine', ['company_id'], unique=False)
    op.create_index(op.f('ix_swipe_machine_is_active'), 'swipe_machine', ['is_active'], unique=False)
    op.create_index(op.f('ix_swipe_machine_is_deleted'), 'swipe_machine', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_swipe_machine_mapped_retailer_id'), 'swipe_machine', ['mapped_retailer_id'], unique=False)
    op.create_index(op.f('ix_swipe_machine_mid'), 'swipe_machine', ['mid'], unique=False)
    op.create_index(op.f('ix_swipe_machine_organization_id'), 'swipe_machine', ['organization_id'], unique=False)
    op.create_index(op.f('ix_swipe_machine_public_id'), 'swipe_machine', ['public_id'], unique=True)
    op.create_index(op.f('ix_swipe_machine_serial_number'), 'swipe_machine', ['serial_number'], unique=False)
    op.create_index(op.f('ix_swipe_machine_sim_iccid'), 'swipe_machine', ['sim_iccid'], unique=False)
    op.create_index(op.f('ix_swipe_machine_status'), 'swipe_machine', ['status'], unique=False)
    op.create_index(op.f('ix_swipe_machine_tenant_id'), 'swipe_machine', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_swipe_machine_tid'), 'swipe_machine', ['tid'], unique=False)
    op.create_table('machine_assignment',
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('assigned_type', sa.String(length=50), nullable=False),
    sa.Column('assigned_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['swipe_machine.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_assignment_assigned_id'), 'machine_assignment', ['assigned_id'], unique=False)
    op.create_index(op.f('ix_machine_assignment_company_id'), 'machine_assignment', ['company_id'], unique=False)
    op.create_index(op.f('ix_machine_assignment_is_active'), 'machine_assignment', ['is_active'], unique=False)
    op.create_index(op.f('ix_machine_assignment_is_deleted'), 'machine_assignment', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_machine_assignment_machine_id'), 'machine_assignment', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_assignment_organization_id'), 'machine_assignment', ['organization_id'], unique=False)
    op.create_index(op.f('ix_machine_assignment_public_id'), 'machine_assignment', ['public_id'], unique=True)
    op.create_index(op.f('ix_machine_assignment_tenant_id'), 'machine_assignment', ['tenant_id'], unique=False)
    op.create_table('machine_key_profile',
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('dukpt_ksn', sa.String(length=100), nullable=False),
    sa.Column('master_key_alias', sa.String(length=100), nullable=False),
    sa.Column('encryption_standard', sa.String(length=50), nullable=False),
    sa.Column('injected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['swipe_machine.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_key_profile_company_id'), 'machine_key_profile', ['company_id'], unique=False)
    op.create_index(op.f('ix_machine_key_profile_is_active'), 'machine_key_profile', ['is_active'], unique=False)
    op.create_index(op.f('ix_machine_key_profile_is_deleted'), 'machine_key_profile', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_machine_key_profile_machine_id'), 'machine_key_profile', ['machine_id'], unique=True)
    op.create_index(op.f('ix_machine_key_profile_organization_id'), 'machine_key_profile', ['organization_id'], unique=False)
    op.create_index(op.f('ix_machine_key_profile_public_id'), 'machine_key_profile', ['public_id'], unique=True)
    op.create_index(op.f('ix_machine_key_profile_tenant_id'), 'machine_key_profile', ['tenant_id'], unique=False)
    op.create_table('machine_maintenance',
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('technician_email', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['swipe_machine.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_maintenance_company_id'), 'machine_maintenance', ['company_id'], unique=False)
    op.create_index(op.f('ix_machine_maintenance_is_active'), 'machine_maintenance', ['is_active'], unique=False)
    op.create_index(op.f('ix_machine_maintenance_is_deleted'), 'machine_maintenance', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_machine_maintenance_machine_id'), 'machine_maintenance', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_maintenance_organization_id'), 'machine_maintenance', ['organization_id'], unique=False)
    op.create_index(op.f('ix_machine_maintenance_public_id'), 'machine_maintenance', ['public_id'], unique=True)
    op.create_index(op.f('ix_machine_maintenance_tenant_id'), 'machine_maintenance', ['tenant_id'], unique=False)
    op.create_table('machine_status_history',
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=False),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by_email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['swipe_machine.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_status_history_company_id'), 'machine_status_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_machine_status_history_is_active'), 'machine_status_history', ['is_active'], unique=False)
    op.create_index(op.f('ix_machine_status_history_is_deleted'), 'machine_status_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_machine_status_history_machine_id'), 'machine_status_history', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_status_history_organization_id'), 'machine_status_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_machine_status_history_public_id'), 'machine_status_history', ['public_id'], unique=True)
    op.create_index(op.f('ix_machine_status_history_tenant_id'), 'machine_status_history', ['tenant_id'], unique=False)
    op.create_table('machine_telemetry',
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('battery_percentage', sa.Integer(), nullable=False),
    sa.Column('network_type', sa.String(length=20), nullable=False),
    sa.Column('signal_strength', sa.Integer(), nullable=False),
    sa.Column('app_version', sa.String(length=50), nullable=False),
    sa.Column('last_ping_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_txns_processed', sa.Integer(), nullable=False),
    sa.Column('total_volume_processed', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['swipe_machine.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_telemetry_company_id'), 'machine_telemetry', ['company_id'], unique=False)
    op.create_index(op.f('ix_machine_telemetry_is_active'), 'machine_telemetry', ['is_active'], unique=False)
    op.create_index(op.f('ix_machine_telemetry_is_deleted'), 'machine_telemetry', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_machine_telemetry_last_ping_at'), 'machine_telemetry', ['last_ping_at'], unique=False)
    op.create_index(op.f('ix_machine_telemetry_machine_id'), 'machine_telemetry', ['machine_id'], unique=True)
    op.create_index(op.f('ix_machine_telemetry_organization_id'), 'machine_telemetry', ['organization_id'], unique=False)
    op.create_index(op.f('ix_machine_telemetry_public_id'), 'machine_telemetry', ['public_id'], unique=True)
    op.create_index(op.f('ix_machine_telemetry_tenant_id'), 'machine_telemetry', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_telemetry_tenant_id'), table_name='machine_telemetry')
    op.drop_index(op.f('ix_machine_telemetry_public_id'), table_name='machine_telemetry')
    op.drop_index(op.f('ix_machine_telemetry_organization_id'), table_name='machine_telemetry')
    op.drop_index(op.f('ix_machine_telemetry_machine_id'), table_name='machine_telemetry')
    op.drop_index(op.f('ix_machine_telemetry_last_ping_at'), table_name='machine_telemetry')
    op.drop_index(op.f('ix_machine_telemetry_is_deleted'), table_name='machine_telemetry')
    op.drop_index(op.f('ix_machine_telemetry_is_active'), table_name='machine_telemetry')
    op.drop_index(op.f('ix_machine_telemetry_company_id'), table_name='machine_telemetry')
    op.drop_table('machine_telemetry')
    op.drop_index(op.f('ix_machine_status_history_tenant_id'), table_name='machine_status_history')
    op.drop_index(op.f('ix_machine_status_history_public_id'), table_name='machine_status_history')
    op.drop_index(op.f('ix_machine_status_history_organization_id'), table_name='machine_status_history')
    op.drop_index(op.f('ix_machine_status_history_machine_id'), table_name='machine_status_history')
    op.drop_index(op.f('ix_machine_status_history_is_deleted'), table_name='machine_status_history')
    op.drop_index(op.f('ix_machine_status_history_is_active'), table_name='machine_status_history')
    op.drop_index(op.f('ix_machine_status_history_company_id'), table_name='machine_status_history')
    op.drop_table('machine_status_history')
    op.drop_index(op.f('ix_machine_maintenance_tenant_id'), table_name='machine_maintenance')
    op.drop_index(op.f('ix_machine_maintenance_public_id'), table_name='machine_maintenance')
    op.drop_index(op.f('ix_machine_maintenance_organization_id'), table_name='machine_maintenance')
    op.drop_index(op.f('ix_machine_maintenance_machine_id'), table_name='machine_maintenance')
    op.drop_index(op.f('ix_machine_maintenance_is_deleted'), table_name='machine_maintenance')
    op.drop_index(op.f('ix_machine_maintenance_is_active'), table_name='machine_maintenance')
    op.drop_index(op.f('ix_machine_maintenance_company_id'), table_name='machine_maintenance')
    op.drop_table('machine_maintenance')
    op.drop_index(op.f('ix_machine_key_profile_tenant_id'), table_name='machine_key_profile')
    op.drop_index(op.f('ix_machine_key_profile_public_id'), table_name='machine_key_profile')
    op.drop_index(op.f('ix_machine_key_profile_organization_id'), table_name='machine_key_profile')
    op.drop_index(op.f('ix_machine_key_profile_machine_id'), table_name='machine_key_profile')
    op.drop_index(op.f('ix_machine_key_profile_is_deleted'), table_name='machine_key_profile')
    op.drop_index(op.f('ix_machine_key_profile_is_active'), table_name='machine_key_profile')
    op.drop_index(op.f('ix_machine_key_profile_company_id'), table_name='machine_key_profile')
    op.drop_table('machine_key_profile')
    op.drop_index(op.f('ix_machine_assignment_tenant_id'), table_name='machine_assignment')
    op.drop_index(op.f('ix_machine_assignment_public_id'), table_name='machine_assignment')
    op.drop_index(op.f('ix_machine_assignment_organization_id'), table_name='machine_assignment')
    op.drop_index(op.f('ix_machine_assignment_machine_id'), table_name='machine_assignment')
    op.drop_index(op.f('ix_machine_assignment_is_deleted'), table_name='machine_assignment')
    op.drop_index(op.f('ix_machine_assignment_is_active'), table_name='machine_assignment')
    op.drop_index(op.f('ix_machine_assignment_company_id'), table_name='machine_assignment')
    op.drop_index(op.f('ix_machine_assignment_assigned_id'), table_name='machine_assignment')
    op.drop_table('machine_assignment')
    op.drop_index(op.f('ix_swipe_machine_tid'), table_name='swipe_machine')
    op.drop_index(op.f('ix_swipe_machine_tenant_id'), table_name='swipe_machine')
    op.drop_index(op.f('ix_swipe_machine_status'), table_name='swipe_machine')
    op.drop_index(op.f('ix_swipe_machine_sim_iccid'), table_name='swipe_machine')
    op.drop_index(op.f('ix_swipe_machine_serial_number'), table_name='swipe_machine')
    op.drop_index(op.f('ix_swipe_machine_public_id'), table_name='swipe_machine')
    op.drop_index(op.f('ix_swipe_machine_organization_id'), table_name='swipe_machine')
    op.drop_index(op.f('ix_swipe_machine_mid'), table_name='swipe_machine')
    op.drop_index(op.f('ix_swipe_machine_mapped_retailer_id'), table_name='swipe_machine')
    op.drop_index(op.f('ix_swipe_machine_is_deleted'), table_name='swipe_machine')
    op.drop_index(op.f('ix_swipe_machine_is_active'), table_name='swipe_machine')
    op.drop_index(op.f('ix_swipe_machine_company_id'), table_name='swipe_machine')
    op.drop_table('swipe_machine')
    op.drop_index(op.f('ix_machine_replacement_tenant_id'), table_name='machine_replacement')
    op.drop_index(op.f('ix_machine_replacement_status'), table_name='machine_replacement')
    op.drop_index(op.f('ix_machine_replacement_public_id'), table_name='machine_replacement')
    op.drop_index(op.f('ix_machine_replacement_organization_id'), table_name='machine_replacement')
    op.drop_index(op.f('ix_machine_replacement_old_machine_id'), table_name='machine_replacement')
    op.drop_index(op.f('ix_machine_replacement_is_deleted'), table_name='machine_replacement')
    op.drop_index(op.f('ix_machine_replacement_is_active'), table_name='machine_replacement')
    op.drop_index(op.f('ix_machine_replacement_company_id'), table_name='machine_replacement')
    op.drop_table('machine_replacement')
    op.drop_index(op.f('ix_machine_inventory_tenant_id'), table_name='machine_inventory')
    op.drop_index(op.f('ix_machine_inventory_public_id'), table_name='machine_inventory')
    op.drop_index(op.f('ix_machine_inventory_organization_id'), table_name='machine_inventory')
    op.drop_index(op.f('ix_machine_inventory_is_deleted'), table_name='machine_inventory')
    op.drop_index(op.f('ix_machine_inventory_is_active'), table_name='machine_inventory')
    op.drop_index(op.f('ix_machine_inventory_company_id'), table_name='machine_inventory')
    op.drop_index(op.f('ix_machine_inventory_batch_stock_id'), table_name='machine_inventory')
    op.drop_table('machine_inventory')
    # ### end Alembic commands ###
