"""EPIC-022 — Beneficiary Management & Verification Platform Schema

Revision ID: kkk022ll33dd
Revises: jjj021kk22cc
Create Date: 2026-07-30

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'kkk022ll33dd'
down_revision = 'jjj021kk22cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. beneficiary
    op.create_table(
        'beneficiary',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_number', sa.String(length=30), nullable=False),
        sa.Column('customer_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('full_name', sa.String(length=300), nullable=False),
        sa.Column('nickname', sa.String(length=100), nullable=True),
        sa.Column('relationship', sa.String(length=50), nullable=False),
        sa.Column('mobile_number', sa.String(length=20), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('dob', sa.Date(), nullable=True),
        sa.Column('beneficiary_category', sa.String(length=50), nullable=False, server_default='REGULAR'),
        sa.Column('beneficiary_type', sa.String(length=50), nullable=False, server_default='INDIVIDUAL'),
        sa.Column('preferred_language', sa.String(length=10), nullable=True),
        sa.Column('photo_url', sa.String(length=500), nullable=True),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.Column('verification_status', sa.String(length=50), nullable=False, server_default='PENDING'),
        sa.Column('risk_category', sa.String(length=30), nullable=False, server_default='LOW'),
        sa.Column('beneficiary_status', sa.String(length=50), nullable=False, server_default='DRAFT'),
        sa.Column('cooling_period_ends_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_favourite', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('registration_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('activation_date', sa.DateTime(timezone=True), nullable=True),
        # Enterprise Base Mixin
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('week_key', sa.Integer(), nullable=True),
        sa.Column('month_key', sa.Integer(), nullable=True),
        sa.Column('quarter_key', sa.Integer(), nullable=True),
        sa.Column('year_key', sa.Integer(), nullable=True),
        sa.Column('financial_year_key', sa.Integer(), nullable=True),
        sa.Column('financial_quarter_key', sa.Integer(), nullable=True),
        sa.Column('financial_month_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('time_key', sa.Integer(), nullable=True),
        sa.Column('partition_year', sa.Integer(), nullable=True),
        sa.Column('partition_month', sa.Integer(), nullable=True),
        sa.Column('partition_day', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
        sa.UniqueConstraint('tenant_id', 'beneficiary_number', name='uq_beneficiary_tenant_number'),
    )
    op.create_index('ix_beneficiary_public_id', 'beneficiary', ['public_id'])
    op.create_index('ix_beneficiary_customer_id', 'beneficiary', ['customer_id'])
    op.create_index('ix_beneficiary_number', 'beneficiary', ['beneficiary_number'])
    op.create_index('ix_beneficiary_status', 'beneficiary', ['beneficiary_status'])

    # 2. beneficiary_profile
    op.create_table(
        'beneficiary_profile',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('address_line1', sa.String(length=500), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('pin_code', sa.String(length=10), nullable=True),
        sa.Column('country', sa.String(length=50), nullable=True, server_default='INDIA'),
        sa.Column('business_name', sa.String(length=300), nullable=True),
        sa.Column('gstin', sa.String(length=20), nullable=True),
        sa.Column('pan_number', sa.String(length=10), nullable=True),
        sa.Column('profile_notes', sa.Text(), nullable=True),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
        sa.UniqueConstraint('beneficiary_id'),
    )

    # 3. beneficiary_bank_account
    op.create_table(
        'beneficiary_bank_account',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('account_holder_name', sa.String(length=300), nullable=False),
        sa.Column('account_number', sa.String(length=50), nullable=False),
        sa.Column('account_number_masked', sa.String(length=50), nullable=True),
        sa.Column('ifsc_code', sa.String(length=20), nullable=False),
        sa.Column('bank_name', sa.String(length=200), nullable=False),
        sa.Column('branch_name', sa.String(length=200), nullable=True),
        sa.Column('account_type', sa.String(length=30), nullable=False, server_default='SAVINGS'),
        sa.Column('verification_status', sa.String(length=30), nullable=False, server_default='UNVERIFIED'),
        sa.Column('verification_reference', sa.String(length=100), nullable=True),
        sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('penny_drop_status', sa.String(length=30), nullable=True),
        sa.Column('name_match_score', sa.Float(), nullable=True),
        sa.Column('registered_name_in_bank', sa.String(length=300), nullable=True),
        sa.Column('is_primary', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
    )
    op.create_index('ix_beneficiary_bank_account_number', 'beneficiary_bank_account', ['account_number'])
    op.create_index('ix_beneficiary_bank_ifsc', 'beneficiary_bank_account', ['ifsc_code'])

    # 4. beneficiary_upi
    op.create_table(
        'beneficiary_upi',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('upi_id', sa.String(length=100), nullable=False),
        sa.Column('upi_handle', sa.String(length=50), nullable=True),
        sa.Column('provider_app', sa.String(length=50), nullable=True),
        sa.Column('registered_name', sa.String(length=300), nullable=True),
        sa.Column('verification_status', sa.String(length=30), nullable=False, server_default='UNVERIFIED'),
        sa.Column('verification_reference', sa.String(length=100), nullable=True),
        sa.Column('is_primary', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
    )
    op.create_index('ix_beneficiary_upi_id', 'beneficiary_upi', ['upi_id'])

    # 5. beneficiary_verification
    op.create_table(
        'beneficiary_verification',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('verification_type', sa.String(length=50), nullable=False),
        sa.Column('verification_status', sa.String(length=30), nullable=False),
        sa.Column('penny_drop_ref', sa.String(length=100), nullable=True),
        sa.Column('bank_response_code', sa.String(length=50), nullable=True),
        sa.Column('name_returned_by_bank', sa.String(length=300), nullable=True),
        sa.Column('name_match_score', sa.Float(), nullable=True),
        sa.Column('is_name_matched', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('verified_by', sa.String(length=100), nullable=True),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('failure_reason', sa.Text(), nullable=True),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
    )

    # 6. beneficiary_document
    op.create_table(
        'beneficiary_document',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('document_type', sa.String(length=50), nullable=False),
        sa.Column('document_name', sa.String(length=255), nullable=False),
        sa.Column('file_url', sa.String(length=1000), nullable=False),
        sa.Column('document_number', sa.String(length=100), nullable=True),
        sa.Column('expiry_date', sa.Date(), nullable=True),
        sa.Column('verification_status', sa.String(length=30), nullable=False, server_default='PENDING'),
        sa.Column('version_number', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('is_current', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
    )

    # 7. beneficiary_service
    op.create_table(
        'beneficiary_service',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('service_code', sa.String(length=50), nullable=False),
        sa.Column('service_name', sa.String(length=100), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('eligibility_status', sa.String(length=30), nullable=False, server_default='ELIGIBLE'),
        sa.Column('eligibility_reason', sa.Text(), nullable=True),
        sa.Column('cooling_period_ends_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
        sa.UniqueConstraint('beneficiary_id', 'service_code', name='uq_beneficiary_service'),
    )

    # 8. beneficiary_service_configuration
    op.create_table(
        'beneficiary_service_configuration',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('service_code', sa.String(length=50), nullable=False),
        sa.Column('service_name', sa.String(length=100), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('verification_required', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('cooling_period_hours', sa.Integer(), nullable=True, server_default='24'),
        sa.Column('max_transfer_amount', sa.Float(), nullable=True),
        sa.Column('max_monthly_amount', sa.Float(), nullable=True),
        sa.Column('approval_required', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('otp_required', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('risk_validation_enabled', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
        sa.UniqueConstraint('tenant_id', 'service_code', name='uq_ben_service_config_tenant_code'),
    )

    # 9. beneficiary_limit_configuration
    op.create_table(
        'beneficiary_limit_configuration',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('service_code', sa.String(length=50), nullable=False),
        sa.Column('hierarchy_level', sa.String(length=50), nullable=False, server_default='BENEFICIARY'),
        sa.Column('beneficiary_category', sa.String(length=50), nullable=True),
        sa.Column('single_txn_max', sa.Float(), nullable=True),
        sa.Column('daily_count', sa.Integer(), nullable=True),
        sa.Column('daily_amount', sa.Float(), nullable=True),
        sa.Column('weekly_amount', sa.Float(), nullable=True),
        sa.Column('monthly_count', sa.Integer(), nullable=True),
        sa.Column('monthly_amount', sa.Float(), nullable=True),
        sa.Column('yearly_amount', sa.Float(), nullable=True),
        sa.Column('max_failed_attempts', sa.Integer(), nullable=True, server_default='3'),
        sa.Column('cooling_period_hours', sa.Integer(), nullable=True),
        sa.Column('override_allowed', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('effective_from', sa.Date(), nullable=False),
        sa.Column('effective_to', sa.Date(), nullable=True),
        sa.Column('limit_status', sa.String(length=30), nullable=False, server_default='ACTIVE'),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
    )

    # 10. beneficiary_limit_override
    op.create_table(
        'beneficiary_limit_override',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('service_code', sa.String(length=50), nullable=False),
        sa.Column('single_txn_max', sa.Float(), nullable=True),
        sa.Column('daily_amount', sa.Float(), nullable=True),
        sa.Column('monthly_amount', sa.Float(), nullable=True),
        sa.Column('effective_from', sa.Date(), nullable=False),
        sa.Column('effective_to', sa.Date(), nullable=True),
        sa.Column('approved_by', sa.String(length=100), nullable=True),
        sa.Column('approval_reason', sa.Text(), nullable=True),
        sa.Column('override_status', sa.String(length=30), nullable=False, server_default='ACTIVE'),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
    )

    # 11. beneficiary_transaction_counter
    op.create_table(
        'beneficiary_transaction_counter',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('service_code', sa.String(length=50), nullable=False),
        sa.Column('counter_date', sa.Date(), nullable=False),
        sa.Column('txn_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('total_amount', sa.Float(), nullable=False, server_default='0'),
        sa.Column('failed_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
        sa.UniqueConstraint('beneficiary_id', 'service_code', 'counter_date', name='uq_ben_daily_counter'),
    )

    # 12. beneficiary_monthly_counter
    op.create_table(
        'beneficiary_monthly_counter',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('service_code', sa.String(length=50), nullable=False),
        sa.Column('counter_year', sa.Integer(), nullable=False),
        sa.Column('counter_month', sa.Integer(), nullable=False),
        sa.Column('txn_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('total_amount', sa.Float(), nullable=False, server_default='0'),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
        sa.UniqueConstraint('beneficiary_id', 'service_code', 'counter_year', 'counter_month', name='uq_ben_monthly_counter'),
    )

    # 13. beneficiary_yearly_counter
    op.create_table(
        'beneficiary_yearly_counter',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('service_code', sa.String(length=50), nullable=False),
        sa.Column('counter_year', sa.Integer(), nullable=False),
        sa.Column('txn_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('total_amount', sa.Float(), nullable=False, server_default='0'),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
        sa.UniqueConstraint('beneficiary_id', 'service_code', 'counter_year', name='uq_ben_yearly_counter'),
    )

    # 14. beneficiary_risk_profile
    op.create_table(
        'beneficiary_risk_profile',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('risk_score', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('risk_category', sa.String(length=30), nullable=False, server_default='LOW'),
        sa.Column('aml_screening', sa.String(length=30), nullable=True, server_default='CLEAR'),
        sa.Column('pep_screening', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('sanction_match', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('watch_list_match', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('bank_risk_score', sa.Integer(), nullable=True),
        sa.Column('velocity_risk_score', sa.Integer(), nullable=True),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
        sa.UniqueConstraint('beneficiary_id'),
    )

    # 15. beneficiary_status_history
    op.create_table(
        'beneficiary_status_history',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('from_status', sa.String(length=50), nullable=True),
        sa.Column('to_status', sa.String(length=50), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('changed_by', sa.String(length=100), nullable=True),
        sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
    )

    # 16. beneficiary_relationship
    op.create_table(
        'beneficiary_relationship',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('customer_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('relation_type', sa.String(length=50), nullable=False),
        sa.Column('is_active_rel', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
    )

    # 17. beneficiary_timeline
    op.create_table(
        'beneficiary_timeline',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('event_title', sa.String(length=255), nullable=False),
        sa.Column('event_description', sa.Text(), nullable=True),
        sa.Column('performed_by', sa.String(length=100), nullable=True),
        sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
    )

    # 18. beneficiary_preference
    op.create_table(
        'beneficiary_preference',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('notification_sms', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('notification_email', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
        sa.UniqueConstraint('beneficiary_id'),
    )

    # 19. beneficiary_blacklist
    op.create_table(
        'beneficiary_blacklist',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('account_number', sa.String(length=50), nullable=True),
        sa.Column('upi_id', sa.String(length=100), nullable=True),
        sa.Column('mobile_number', sa.String(length=20), nullable=True),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('blacklist_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_permanent', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('blacklist_status', sa.String(length=30), nullable=False, server_default='ACTIVE'),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
    )

    # 20. beneficiary_whitelist
    op.create_table(
        'beneficiary_whitelist',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('service_code', sa.String(length=50), nullable=True),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('effective_from', sa.Date(), nullable=False),
        sa.Column('effective_to', sa.Date(), nullable=True),
        sa.Column('whitelist_status', sa.String(length=30), nullable=False, server_default='ACTIVE'),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
    )

    # 21. beneficiary_audit
    op.create_table(
        'beneficiary_audit',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('performed_by', sa.String(length=100), nullable=False),
        sa.Column('audit_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('audit_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('day_key', sa.Integer(), nullable=True),
        sa.Column('date_key', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(length=100), nullable=False),
        sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
        sa.Column('record_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.public_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
    )


def downgrade() -> None:
    op.drop_table('beneficiary_audit')
    op.drop_table('beneficiary_whitelist')
    op.drop_table('beneficiary_blacklist')
    op.drop_table('beneficiary_preference')
    op.drop_table('beneficiary_timeline')
    op.drop_table('beneficiary_relationship')
    op.drop_table('beneficiary_status_history')
    op.drop_table('beneficiary_risk_profile')
    op.drop_table('beneficiary_yearly_counter')
    op.drop_table('beneficiary_monthly_counter')
    op.drop_table('beneficiary_transaction_counter')
    op.drop_table('beneficiary_limit_override')
    op.drop_table('beneficiary_limit_configuration')
    op.drop_table('beneficiary_service_configuration')
    op.drop_table('beneficiary_service')
    op.drop_table('beneficiary_document')
    op.drop_table('beneficiary_verification')
    op.drop_table('beneficiary_upi')
    op.drop_table('beneficiary_bank_account')
    op.drop_table('beneficiary_profile')
    op.drop_table('beneficiary')
