import asyncio
import csv
import io
import uuid
from datetime import datetime
from sqlalchemy import text, select
from app.core.database import engine, Base, AsyncSessionLocal
import app.infrastructure.db.models
import app.infrastructure.db.bank_master_models
from app.infrastructure.db.bank_master_models import BankMasterModel

CSV_DATA = """BankIFSCRefID,BankID,BankName,ShortCode,IFSC,IMPSStatus,NEFTStatus,CreditCard,Validation,Status,CreatedDate,CreatedBy,UpdatedDate,UpdatedBy
1,NULL,ABHYUDAYA COOPERATIVE BANK LIMITED,NULL,ABHY0065103,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
2,NULL,ABU DHABI COMMERCIAL BANK,NULL,ADCB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
3,NULL,Ahmedabad District Cooperative Bank,NULL,GSCB0ADC001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
4,NULL,AHMEDABAD MERCANTILE COOPERATIVE BANK,NULL,AMCB0660007,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
5,NULL,AHMEDABAN MERCANTILE COOPERATIVE BANK LTD,NULL,AMCB0660016,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
6,NULL,AHMEDNAGAR MERCHANTS CO-OP BANK LTD,NULL,AMDN0000103,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
7,NULL,AIRTEL PAYMENTS BANK LIMITED,NULL,AIRP0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
8,NULL,Akhand Aanand Co-Operative Bank,NULL,HDFC0CAACOB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
9,NULL,AKOLA JANATA COMMERCIAL COOPERATIVE BANK,NULL,AKJB0000009,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
10,NULL,ALLAHABAD BANK,NULL,ALLA0212270,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
11,NULL,Allahabad UP Gramin Bank,NULL,ALLA0AU1002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
12,NULL,Allahabad UP Gramin Bank/Aryavart Gramin Bank,NULL,BKID0ARYAGA,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
13,NULL,ALMORA URBAN COOPERATIVE BANK LIMITED,NULL,AUCB0000031,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
14,NULL,ALORE NAGRIK SAHKARI BANK LIMITED,NULL,HDFC0CJALOR,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
15,NULL,AMAN SAHAKARI BANK LTD ICHALKARANJI,NULL,ICIC00AMSBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
16,NULL,AMBARNATH JAI HIND CO OP BANK LTD,NULL,AJHC0001005,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
17,NULL,"AMBARNATH JAI HIND COOP BANK LTD, ICICI BANK LTD",NULL,ICIC00AJHCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
18,NULL,AMBARNATH JAIHIND COOP BANK LTD AMBARNATH,NULL,AJHC0001002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
19,NULL,ANDHRA BANK,NULL,UBIN0812145,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
20,NULL,Andhra Pradesh Grameena Vikas Bank,NULL,APGV0009909,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
21,NULL,ANDHRA PRAGATHI GRAMEENA BANK,NULL,APGB0002094,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
22,NULL,APNA SAHAKARI BANK LIMITED,NULL,ASBL0000019,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
23,NULL,Arunachal Pradesh Rural Bank,NULL,SBAP0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
24,NULL,ARVIND SAHAKARI BANK LTD,NULL,SVCB0015005,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
25,NULL,Aryavart Gramin Bank,NULL,BKID0ARYAGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
26,NULL,Assam Gramin Vikash Bank,NULL,PUNB0RRBAGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
27,NULL,ASSOCIATE CO OP BANK LTD,NULL,GSCB0ASCB02,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
28,NULL,AU SMALL FINANCE BANK LIMITED,NULL,AUBL0002127,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
29,NULL,AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED,NULL,ANZB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
30,NULL,AXIS BANK,NULL,UTIB0000248,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
31,NULL,AXIS BANK CREDIT,NULL,UTIB0001021,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
32,NULL,B N P PARIBAS,NULL,BNPA0009009,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
33,NULL,Baitarani Gramin Bank,NULL,BKID0BAITGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
34,NULL,Balasore Bhadrak Central co operative bank,NULL,YESBOBBCB04,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
35,NULL,Ballia Etawah Gramin Bank,NULL,CBIN0R30001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
36,NULL,Banaskantha District Central Co Op Bank Ltd,NULL,GSCB0BKD001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
37,NULL,Banda District Co Operative Bank Ltd branch Icici Bank Ltd,NULL,ICIC00BDCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
38,NULL,BANDHAN BANK LIMITED,NULL,BDBL0001750,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
39,NULL,BANGALORE CITY COOP BANK,NULL,INDB0BCCB10,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
40,NULL,Bangiya Gramin Vikash Bank,NULL,PUNB0RRBBGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
41,NULL,BANK OF AMERICA,NULL,BOFA0ND6216,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
42,NULL,BANK OF BAHARAIN AND KUWAIT BSC,NULL,BBKM0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
43,NULL,BANK OF BARODA,NULL,BARB0COLABA,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
44,NULL,BANK OF BARODA UP GRAMIN BANK,NULL,BARB0BUPGBX,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
45,NULL,BANK OF CEYLON,NULL,BCEY0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
46,NULL,BANK OF INDIA,NULL,BKID0000150,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
47,NULL,"BANK OF INDIA, ACHALJAMU",NULL,BKID0005975,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
48,NULL,BANK OF MAHARASHTRA,NULL,MAHB0000343,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
49,NULL,BANK OF TOKYO MITSUBISHI LIMITED,NULL,BOTM0ND3611,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
50,NULL,BARCLAYS BANK,NULL,BARC0INBB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
51,NULL,BARODA GUJARAT GRAMIN BANK,NULL,BARB0BGGBXX,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
52,NULL,BARODA RAJASHTAN GRAMIN BANK,NULL,BARB0BRGBXX,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
53,NULL,Baroda Rajasthan Gramin Bank,NULL,BARB0BRGBXX,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
54,NULL,Baroda Uttar Pradesh Gramin Bank,NULL,BARB0BUPGBX,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
55,NULL,BASSEIN CATHOLIC COOPERATIVE BANK LIMITED,NULL,BACB0000013,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
56,NULL,BHAGINI NIVEDITA SAHAKARI BANK LTD PUNE,NULL,HDFC0CBNBNK,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
57,NULL,BHARAT COOPERATIVE BANK MUMBAI LIMITED,NULL,BCBM0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
58,NULL,BHARATI SAHAKARI BANK,NULL,SVCB0010024,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
59,NULL,Bharatiya Mahila Bank Limited,NULL,BMBL0000053,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
60,NULL,Bhavnagar District Central Co operative Bank,NULL,GSCB0BVN001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
61,NULL,BIHAR GRAMIN BANK,NULL,PUNB0MBGB06,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
62,NULL,Bihar Kshetriya Gramin Bank,NULL,UCBA0RRBBKG,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
63,NULL,BOMBAY MERCANTILE CO OP BANK LTD,NULL,UTIB0SBMCB1,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
64,NULL,Budaun jila sahkari bank limited,NULL,ICIC00ZSBBU,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
65,NULL,Buldhana Urban Bank,NULL,ICIC0000104,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
66,NULL,Burdwan Central Coop Bank,NULL,HDFC0CBCCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
67,NULL,CANARA BANK,NULL,CNRB0000404,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
68,NULL,CAPITAL SMALL FINANCE BANK LIMITED,NULL,CLBL0000058,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
69,NULL,CATHOLIC SYRIAN BANK LIMITED,NULL,CSBK0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
70,NULL,Cauvery Kalpatharu Grameena Bank,NULL,SBMY0RRCKGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
71,NULL,CENTRAL BANK OF INDIA,NULL,CBIN0011102,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
72,NULL,Central Madhya Pradesh Gramin Bank,NULL,CBIN0R20002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
73,NULL,CENTURY COMMERCIAL BANK LIMITED,NULL,SBININBB832,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
74,NULL,Chaitanya Godavari Grameena Bank,NULL,ANDB0007999,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
75,NULL,Chamoli Zila Sahakari Bank Ltd,NULL,IBKL070CZSB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
76,NULL,CHEMBUR NAGARIK SAHAKARI BANK,NULL,SRCB0CNS011,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
77,NULL,CHHATRAPATI RAJASHRI URBAN COOP BANK LT,NULL,CRUB0000016,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
78,NULL,Chhattisgarh Rajya Gramin Bank,NULL,SBIN0RRCHGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
79,NULL,Chickmangalur Kodagu Gramin Bank,NULL,CORP0CK0001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
80,NULL,CHINATRUST COMMERCIAL BANK LIMITED,NULL,CTCB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
81,NULL,CITI BANK,NULL,CITI0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
82,NULL,Citizen Co- Operative Bank,NULL,IBKL01642C2,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
83,NULL,CITIZEN CREDIT COOPERATIVE BANK LIMITED,NULL,CCBL0GOA007,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
84,NULL,City Union Bank,NULL,CIUB0000142,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
85,NULL,CITY UNION BANK LIMITED,NULL,CIUB0000102,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
86,NULL,CITY UNION BANK LTD,NULL,CIUB0000624,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
87,NULL,COASTAL LOCAL AREA BANK LTD,NULL,MAHB000CB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
88,NULL,CONTAI CO OPERATIVE BANK LTD,NULL,ICIC00CCBLT,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
89,NULL,CORPORATION BANK,NULL,CORP0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
90,NULL,CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK CALYON BANK,NULL,CRLY0000002,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
91,NULL,CREDIT CARD - ABN Amro Bank,NULL,ABNA0100328,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
92,NULL,CREDIT CARD - AMERICAN EXPRESS,NULL,SCBL0036020,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
93,NULL,CREDIT CARD - Barclays,NULL,BARC0INBBIR,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
94,NULL,CREDIT CARD - Citibank,NULL,CITI0000003,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
95,NULL,CREDIT CARD - HDFC Bank,NULL,HDFC0000128,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
96,NULL,CREDIT CARD - HSBC,NULL,HSBC0110005,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
97,NULL,CREDIT CARD - ICICI Bank,NULL,ICIC0000103,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
98,NULL,CREDIT CARD - Kotak Mahindra Bank,NULL,KKBK000CCRD,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
99,NULL,CREDIT CARD - SBI,NULL,SBIN00CARDS,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
100,NULL,CREDIT CARD - Standard Chartered,NULL,SCBL0036001,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
101,NULL,CREDIT CARD - UTI/ Axis Bank,NULL,UTIB0000400,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
102,NULL,CREDIT CARD - Vijaya Bank,NULL,VIJB0009020,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
103,NULL,CREDIT CARD BANK OF BARODA,NULL,BARB0COLABA,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
104,NULL,CREDIT SUISEE AG,NULL,CRES0000001,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
105,NULL,CSB BANK LIMITED,NULL,CSBK0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
106,NULL,CTBC BANK CO LTD,NULL,CTCB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
107,NULL,DAKHSHIN BIHAR GRAMIN BANK,NULL,PUNB0MBGB06,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
108,NULL,DAPOLI URBAN CO OP BANK LTD,NULL,IBKL0116DPC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
109,NULL,DAPOLI URBAN CO-OP. BANK LTD,NULL,IBKL0116DPC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
110,NULL,Daund Urban Co- OP Bank Ltd,NULL,HDFC0CDACBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
111,NULL,DBS BANK LTD,NULL,DBSS0IN0820,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
112,NULL,DCB BANK,NULL,DCBL0000148,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
113,NULL,DCB BANK LIMITED,NULL,DCBL0000019,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
114,NULL,DCB BANK LTD,NULL,DCBL0000VAA,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
115,NULL,DECCAN GRAMEENA BANK,NULL,SBIN0RRDCGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
116,NULL,Deendayal Nagari Sahakari Bank Ltd,NULL,ICIC00DDNSB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
117,NULL,DEHRADUN DISTT CO OPRATIVE BANK,NULL,YESB0DZSB17,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
118,NULL,DENA BANK,NULL,BKDN0110011,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
119,NULL,Dena Gujarat Gramin Bank,NULL,BKDN0700000,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
120,NULL,DEOGIRI NAGARI SAHAKARI BANK LTD. AURANGABAD,NULL,DEOB0000003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
121,NULL,DEPOSIT INSURANCE AND CREDIT GUARANTEE CORPORATION,NULL,DICG0000002,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
122,NULL,DEUSTCHE BANK,NULL,DEUT0797BGL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
123,NULL,DEVELOPMENT BANK OF SINGAPORE,NULL,DBSS0IN0811,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
124,NULL,DEVELOPMENT CREDIT BANK LIMITED,NULL,DCBL0000062,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
125,NULL,DHANALAKSHMI BANK,NULL,DLXB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
126,NULL,DHARMAVIR SAMBHAJI URBAN CO OP BANK LTD,NULL,SVCB0004003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
127,NULL,DICGC,NULL,DICG0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
128,NULL,DMK JAOLI BANK,NULL,DMKJ0000004,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
129,NULL,Dnyanradha Multistate Coop Credit Society Ltd,NULL,ICIC0000104,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
130,NULL,DOHA BANK,NULL,DOHB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
131,NULL,DOHA BANK QSC,NULL,DOHB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
132,NULL,DOMBIVLI NAGARI SAHAKARI BANK LIMITED,NULL,DNSB0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
133,NULL,Durg Rajnandgaon Gramin Bank,NULL,BKDN0800000,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
134,NULL,DURGAPUR STEEL PEOPLES CO-OPERATIVE BANK LTD,NULL,IBKL0256DSC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
135,NULL,"ELLAQUAI DEHATI BANK, STATE BANK OF INDIA",NULL,SBIN0RRELGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
136,NULL,Ellaqui Dehati Bank,NULL,SBIN0RRELGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
137,NULL,EMIRATES NBD BANK P J S C,NULL,EBIL0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
138,NULL,EQUITAS SMALL FINANCE BANK LIMITED,NULL,ESFB0016001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
139,NULL,ESAF SMALL FINANCE BANK LIMITED,NULL,ESMF0001134,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
140,NULL,ETAH DISTRICT COOPERATIVE BANK LTD,NULL,ICIC00ETDCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
141,NULL,Etawah district co operative bank ltd,NULL,ICIC00ETAWH,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
142,NULL,Excellent Co Op Bank Ltd,NULL,HDFC0CECBL2,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
143,NULL,EXPORT IMPORT BANK OF INDIA,NULL,EIBI0HO0001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
144,NULL,Faizabad Sahkari Zila Bank Ltd,NULL,ICIC00FDCCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
145,NULL,FEDERAL BANK,NULL,FDRL0000035,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
146,NULL,Fincare small finance Bank,NULL,FSFB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
147,NULL,FINCARE SMALL FINANCE BANK LTD,NULL,FSFB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
148,NULL,FINO PAYMENTS BANK,NULL,FINO0001118,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
149,NULL,FIRST ABU DHABI BANK PJSC,NULL,NBAD0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
150,NULL,FIRSTRAND BANK LIMITED,NULL,FIRN0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
151,NULL,G P PARSIK BANK,NULL,PJSB0000045,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
152,NULL,Godavari Urban Co-Operative Bank,NULL,YESB0GUCB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
153,NULL,"GS Mahanagar Co-operative Bank Limited, Mumbai",NULL,MCBL0960003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
154,NULL,GUJARAT STATE COOP BANK THE BAPUNAGAR MAHILA CO OPERATIVE BANK LTD,NULL,GSCB0UBMCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
155,NULL,Gurgaon Gramin Bank,NULL,GGBK0001148,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
156,NULL,Hadoti Kshetriya Gramin Bank,NULL,CBIN0R70036,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
157,NULL,HAMIRPUR DISTRICT CO OPERATIVE BANK LTD,NULL,ICIC00HDCCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
158,NULL,Haryana Gramin Bank,NULL,PUNB0HGB001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
159,NULL,HARYANA STATE COOPERATIVE BANK,NULL,UTIB0HSCB02,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
160,NULL,HDFC BANK,NULL,HDFC0000240,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
161,NULL,HDFC BANK LTD THE PATAN URBAN COOP BANK LTD PATAN,NULL,HDFC0CPUBLP,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
162,NULL,HDFC BANK LTD VASAI JANATA SAHKARI BANK LTD,NULL,HDFC0CVJSBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
163,NULL,HDFC BANK NIDHI CO OPERATIVE BANK LTD,NULL,HDFC0CNIDHI,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
164,NULL,HDFC BANK SANMITRA SAHAKARI BANK LTD,NULL,HDFC0CSSB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
165,NULL,HDFC BANK8802,NULL,HDFC00004788,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
166,NULL,Himachal Gramin Bank,NULL,PUNB0HPGB04,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
167,NULL,HIMACHAL PRADESH STATE COOPERATIVE BANK LTD,NULL,HPSC0000051,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
168,NULL,HIMACHEL PRADESH GRAMIN BANK,NULL,PUNB0HPGB04,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
169,NULL,Hindusthan CO OP Bank LTD,NULL,SVCB0001004,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
170,NULL,HSBC BANK,NULL,HSBC0110002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
171,NULL,HUTAMA SAHAKARI BANK LTD WALWA,NULL,ICIC00HSBLW,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
172,NULL,ICICI BANK CREDIT,NULL,ICIC0000323,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
173,NULL,ICICI BANK DISTRICT COOPERATIVE BANK LTD SAHARANPUR,NULL,ICIC00DCBLS,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
174,NULL,ICICI BANK LIMITED,NULL,ICIC0000004,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
175,NULL,ICICI BANK LTD RAE BARELI DISTRICT COOPERATIVE BANK LTD,NULL,ICIC00RBDCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
176,NULL,ICICI BANK LTD SHRI ARIHANT COOP BANK LTD,NULL,ICIC00ARIHT,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
177,NULL,ICICI BANK LTD URBAN COOP BANK LTD SIDDHARTHANAGAR,NULL,ICIC00SIDRH,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
178,NULL,"ICICI BANK LTD, ZILA SAHKARI BANK LTD",NULL,ICIC00MUZAF,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
179,NULL,IDBI BANK,NULL,IBKL0000039,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
180,NULL,IDBI BANK LTD LOKMANGAL CO OPERATIVE BANK LTD,NULL,IBKL0478LOK,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
181,NULL,IDBI BANK LTD SARVODAYA CO-OP BANK,NULL,IBKL0443SCC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
182,NULL,IDBI NAVI MUMBAI CO-OP BANK LTD,NULL,IBKL0123NMC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
183,NULL,IDFC Credit Card,NULL,IDFB0010224,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
184,NULL,IDFC First Bank Ltd,NULL,IDFB0010209,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
185,NULL,IDUKKI DISTRICT CO OPERATIVE BANK LTD,NULL,UTIB0SIDB99,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
186,NULL,INDIA POST PAYMENT BANK,NULL,IPOS0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
187,NULL,INDIA POST PAYMENTS BANK,NULL,IPOS0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
188,NULL,INDIAN BANK,NULL,IDIB000N120,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
189,NULL,Indian Bank Allahabad,NULL,ALLA0212216,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
190,NULL,INDIAN BANK CREDIT,NULL,IDIB000N615,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
191,NULL,INDIAN BANK SGB CHITTOOR,NULL,IDIB000C602,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
192,NULL,INDIAN OVERSEAS BANK,NULL,IOBA0009072,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
193,NULL,Indore Paraspar Sahakari Bank LTD,NULL,ICIC00INPRS,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
194,NULL,Indrayani Cooperative Bank Limited,NULL,HDFC0CICBLP,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
195,NULL,INDUSIND BANK,NULL,INDB0000033,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
196,NULL,Indusind Bank Credit Card,NULL,INDB0000018,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
197,NULL,INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED,NULL,ICBK0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
198,NULL,INDUSTRIAL BANK OF KOREA,NULL,IBKO0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
199,NULL,ING VYSYA BANK,NULL,VYSA0005030,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
200,NULL,INNOVATIVE COOP URBAN BANK LTD,NULL,YESB0ICUBL1,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
201,NULL,INTEGRAL URBAN CO-OP BANK LTD,NULL,HDFC0CIUCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
202,NULL,Irinjalakuda Town Co-Operative Bank Ltd,NULL,ITBL0000101,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
203,NULL,J And K Grameen Bank,NULL,JAKA0GRAMEN,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
204,NULL,Jaipur That Gramin Bank,NULL,UCBA0RRBJTG,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
205,NULL,JALGAON JANATA SAHAKARI BANK LIMITED,NULL,JJSB0000029,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
206,NULL,JAMIA COOPERATIVE BANK LIMITED,NULL,UTIB0SJCB03,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
207,NULL,JAMMU AND KASHMIR BANK LIMITED,NULL,JAKA0CIRCUS,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
208,NULL,Jana Small Finance Bank,NULL,JSFB0004528,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
209,NULL,JANA SMALL FINANCE BANK LTD,NULL,JSFB0004597,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
210,NULL,JANAKALYAN SAHAKARI BANK LIMITED,NULL,JSBL0000012,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
211,NULL,JANASEVA SAHAKARI BANK BORIVLI LIMITED,NULL,JASB0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
212,NULL,JANASEVA SAHAKARI BANK LIMITED,NULL,JANA0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
213,NULL,JANATA CO-OP BANK LTD,NULL,HDFC0CJBMLG,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
214,NULL,JANATA SAHAKARI BANK LIMITED,NULL,JSBP0000050,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
215,NULL,janata sahakari bank ltd pune,NULL,JSBP0000011,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
216,NULL,Jhabua Dhar Kshetriya Gramin Bank,NULL,BARB0JDKGBX,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
217,NULL,Jharkhand Garmin Bank,NULL,SBINORRVCGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
218,NULL,JHARKHAND STATE COOPERATIVE BANK LIMITED,NULL,IBKL063JS05,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
219,NULL,JIJAMATA MAHILA NAG SAH BANK Ltd,NULL,HDFC0CJMNSB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
220,NULL,Jila sahakari bank faizabad,NULL,ICIC00FZSBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
221,NULL,JILA SAHAKARI KENDRIYA BANK MARYADIT JAGDALPUR,NULL,UTIB0SJSJ01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
222,NULL,JILA SAHAKARI KENDRIYA BANK MARYADIT RAJNANDGAON,NULL,UTIB0SJSN01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
223,NULL,Jila Sahakari Kendriya Bank Mydt Durg,NULL,UTIB0SJSD01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
224,NULL,Jila Sahakari Kendriya Bank Mydt Jhabua,NULL,CBIN0MPDCAQ,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
225,NULL,Jila Sahakari Kendriya Bank Mydt Tikamgarh,NULL,CBIN0MPDCBK,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
226,NULL,JIO PAYMENTS BANK LIMITED,NULL,JIOP0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
227,NULL,JP MORGAN BANK,NULL,CHAS0INBX01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
228,NULL,KALAPANA AWADE ICHALKARNJI JANTA SAHAKARI BANK LTD,NULL,KAIJ0000009,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
229,NULL,Kalinga Gramya Bank,NULL,UCBA0RRBKGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
230,NULL,KALUPUR COMMERCIAL COOPERATIVE BANK,NULL,KCCB0KMD002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
231,NULL,KALYAN JANATA SAHAKARI BANK,NULL,KJSB0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
232,NULL,KANGRA CENTRAL CO-OP BANK LIMITED (THE),NULL,KACE0000104,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
233,NULL,Kannur District Co-Operative Bank,NULL,UTIB0SKDC01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
234,NULL,KAPOLE CO OP BANK,NULL,KCBL0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
235,NULL,KARNALA NAGARI SAHAKARI BANK LIMITED,NULL,UTIB0SKNSB1,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
236,NULL,Karnataka Apex Bank Tumkur Dcc Bank Ltd,NULL,KSCB0006011,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
237,NULL,KARNATAKA BANK LIMITED,NULL,KARB0000369,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
238,NULL,KARNATAKA BANK LTD,NULL,KARB0000695,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
239,NULL,KARNATAKA GRAMIN BANK,NULL,PKGB0012539,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
240,NULL,KARNATAKA STATE COOP APEX BANK GULBARGA YADAGIR CO OP BANK LTD,NULL,KSCB0017001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
241,NULL,KARNATAKA VIKAS GRAMEENA BANK,NULL,KVGB0006301,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
242,NULL,KARUR VYSYA BANK,NULL,KVBL0001254,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
243,NULL,Kashi Gomati Samyut Gramin Bank,NULL,UBIN0RRBKGS,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
244,NULL,Kaveri Grameena Bank,NULL,SBIN0RRCKGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
245,NULL,KEB Hana Bank,NULL,KOEX0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
246,NULL,KERALA GRAMIN BANK,NULL,KLGB0040444,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
247,NULL,Kerala State co-operative bank,NULL,UBIN0DCBEDC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
248,NULL,KHALILABAD NAGAR SAHKARI BANK LTD,NULL,YESB0KHBKSN,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
249,NULL,KOKAN MERCANTILE COOPERATIVE BANK LTD,NULL,KKBK0KMCB12,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
250,NULL,Kolar Chikkaballapur Co Op Bank,NULL,KSCB0003001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
251,NULL,Kolhapur District Central Cooperative Bank Ltd,NULL,IBKL0463KDC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
252,NULL,KOOKMIN BANK,NULL,HDFC0CKB001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
253,NULL,KOTAK MAHINDRA BANK LIMITED,NULL,KKBK0000958,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
254,NULL,KOTAK MAHINDRA BANK THE KARNAVATI CO OP BANK LTD,NULL,KKBK0TKCB05,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
255,NULL,KOTTAYAM URBAN CO OPERATIVE BANK LTD,NULL,lBKL0027K01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
256,NULL,KOZHIKODE DISTRICT COOPERATIAVE BANK LTD,NULL,IBKL0114K01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
257,NULL,Krishna Bhima Samruddhi local area bank,NULL,HDFC0CKBS01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
258,NULL,Krishna Gramin Bank,NULL,PKGB0010630,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
259,NULL,krishna sahakari banl ltd,NULL,IBKL0470KRS,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
260,NULL,KRUNG THAI BANK PCL,NULL,KRTH0INBB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
261,NULL,Langpi Dehangi Rural Bank,NULL,UTBI0RRBLDB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
262,NULL,LAXMI VILAS BANK,NULL,LAVB0000101,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
263,NULL,Madhya Bharat Gramin Bank,NULL,SBIN0RRMBGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
264,NULL,Madhya Pradesh Gramin Bank,NULL,BKID0NAMRGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
265,NULL,Madhyanchal Gramin Bank,NULL,SBIN0RRMBGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
266,NULL,Maha Sarvajan Savings Bank,NULL,MAHB0000780,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
267,NULL,Mahakaushal Kshetriya Gramin Bank,NULL,UCBA0RRBMKG,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
268,NULL,MAHANAGAR COOP BANK LTD,NULL,MCBL0960020,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
269,NULL,MAHANAGAR COOP BANK LTD SHIKRAPUR,NULL,MCBL0960073,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
270,NULL,"MAHANAGAR CO-OP BANK LTD, KHANDA COLONY PANVEL",NULL,MCBL0960032,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
271,NULL,MAHANAGAR COOPERATIVE BANK,NULL,MCBL0960052,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
272,NULL,Maharashtra Gramin Bank,NULL,MAHG0004501,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
273,NULL,MAHARASHTRA GRAMIN BANK - RRB,NULL,MAHB0RRBMGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
274,NULL,MAHARASHTRA STATE COOPERATIVE BANK,NULL,MSCI0082031,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
275,NULL,MAHESH SAHAKARI BANK,NULL,MSBL0000006,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
276,NULL,Mahesh Sahakari Bank Ltd Pune,NULL,HDFC0CMASBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
277,NULL,Mahesh urbun co-op bank ltd parbhani,NULL,UTIB0SMUCB1,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
278,NULL,MALAD SAHKARI BANK LTD,NULL,HDFC0CMALAD,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
279,NULL,Malappuram District Co-operative Bank,NULL,IBKL0209M01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
280,NULL,MALVIYA URBAN CO-OP BANK LIMITED,NULL,HDFC0CMUCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
281,NULL,MALWA GARMIN BANK,NULL,SBIN0RRMLGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
282,NULL,Manipur Rural ank,NULL,UTBG0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
283,NULL,MANTHA URBAN CO OP BANK LTD,NULL,KKBK0MUCB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
284,NULL,MASHREQBANK PSC,NULL,MSHQ0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
285,NULL,MATHYA BIHAR GRAMIN BANK,NULL,PUNB0MBGB06,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
286,NULL,Meghalaya Rural Bank,NULL,SMEG0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
287,NULL,Mewar Anchalik Gramin Bank,NULL,ICIC00MEWAR,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
288,NULL,MG Baroda Gramin Bank,NULL,BARB0BUPGBY,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
289,NULL,MGB GRAMIN BANK,NULL,RMGB0000052,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
290,NULL,MIZORAM RURAL BANK,NULL,SBIN0RRMIGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
291,NULL,MIZUHO BANK LTD,NULL,MHCB0000793,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
292,NULL,MIZUHO CORPORATE BANK LTD,NULL,MHCB0000793,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
293,NULL,MODEL CO OP BANK LTD,NULL,HDFC0CMODEL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
294,NULL,MODEL COOPERATIVE BANK LTD,NULL,HDFC0CMODEL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
295,NULL,"MUFG BANK, LTD",NULL,BOTM0ND3611,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
296,NULL,MUMBAI DISTRICT CENTRAL CO-OP BANK LTD,NULL,MDCB0680016,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
297,NULL,MURSHIDABAD DISTRICT CENTRAL CO OPERATIVE BANK LTD,NULL,WBSC0MCCB22,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
298,NULL,NAGALAND RURAL BANK RRB,NULL,SBIN0RRNLGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
299,NULL,Nagar Sahkari Bank Ltd,NULL,YESB0NSB011,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
300,NULL,NAGAR URBAN CO OPERATIVE BANK,NULL,NUCB0000134,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
301,NULL,NAGPUR NAGARIK SAHAKARI BANK LIMITED,NULL,NGSB0000006,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
302,NULL,NALANDA CENTRAL CO-OPERATIVE BANK LTD,NULL,IBKL0780NCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
303,NULL,Narmada Jhabua Gramin Bank,NULL,BKID0NAMRGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
304,NULL,NATIONAL AUSTRALIA BANK LIMITED,NULL,NATA0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
305,NULL,NATIONAL BANK FOR AGRICULTURE AND RURAL DEVELOPMENT,NULL,NBRD0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
306,NULL,NATIONAL BANK OF ABU DHABI PJSC,NULL,HDFC0CNBADM,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
307,NULL,NATIONAL URBAN COOPERATIVE BANK LIMITED,NULL,UTIB0SNUC01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
308,NULL,NAV JEEVAN CO OP BANK LTD,NULL,ICIC00NVJVN,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
309,NULL,Neelachal Gramya Bank,NULL,IOBA0NGB001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
310,NULL,NEFT MALWA GRAMIN BANK,NULL,STBP0RRMLGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
311,NULL,NEW INDIA COOPERATIVE BANK LIMITED,NULL,NICB0000004,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
312,NULL,Nilambur Co-operative Urban Bank,NULL,FDRL0NCUB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
313,NULL,NKGSB COOPERATIVE BANK LIMITED,NULL,NKGS0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
314,NULL,NORTH EAST SMALL FINANCE BANK,NULL,NESF0000009,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
315,NULL,NORTH EAST SMALL FINANCE BANK LIMITED,NULL,NESF0000073,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
316,NULL,North Malabar Gramin Bank,NULL,UTIB0000198,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
317,NULL,Nsdl Payments Bank,NULL,NSPB0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
318,NULL,NSDL Payments Bank Limited,NULL,NSPB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
319,NULL,NUTAN NAGARIK SAHAKARI BANK LIMITED,NULL,NNSB0128022,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
320,NULL,Odisha Gramin Bank,NULL,IOBA0ROGB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
321,NULL,OMAN INTERNATIONAL BANK SAOG,NULL,OIBA0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
322,NULL,ORIENTAL BANK OF COMMERCE,NULL,PUNB0138810,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
323,NULL,PADMAVATHI COOP URBAN BANK LTD,NULL,HDFC0CPADMA,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
324,NULL,Palakkad District Co Op Bank Ltd,NULL,UTIB0SPKD21,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
325,NULL,Pallavan Grama Bank,NULL,IDIB0PLB001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
326,NULL,Panchmahal District Cooperative Bank,NULL,GSCB0PDC001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
327,NULL,Pandyan grama bank,NULL,IOBA0PGB001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
328,NULL,Panipat Urban Coop Banks,NULL,YESB0PUCB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
329,NULL,PARSHWANATH COOP BANK LTD VASHI,NULL,HDFC0CPCB12,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
330,NULL,PARSIK JANATA SAHAKARI BANK LTD,NULL,PJSB0000037,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
331,NULL,Parvatiya Gramin Bank,NULL,SBIN0RRPRGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
332,NULL,Paschim Banga Gramin Bank,NULL,UCBA0RRBPBG,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
333,NULL,PATAN NAGARIK SAHAKARI BANK LTD,NULL,GSCB0UPATAN,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
334,NULL,Patliputra Central Cooperative Bank Ltd,NULL,IBKL0140PCC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
335,NULL,PAYTM PAYMENTS BANK LTD,NULL,PYTM0123456,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
336,NULL,Pilibhit District Co Operative Bank Ltd branch Icici Bank Ltd,NULL,ICIC00PDCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
337,NULL,Pimpri Chinchwad Sahakari bank Maryadit Pimpri,NULL,IBKL0087PCS,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
338,NULL,Poornawati Nagrik Sahakari Bank Ltd,NULL,HDFCDCPNSBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
339,NULL,PRAGATHI KRISHNA GRAMIN BANK,NULL,PKGB0011016,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
340,NULL,PRATHAMA BANK,NULL,PRTH0034070,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
341,NULL,PRIME COOPERATIVE BANK LIMITED,NULL,PMEC0101313,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
342,NULL,PRIYADARSHANI NAGARI SAHAKARI BANK JALANA BRANCH,NULL,KKBK0PNSB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
343,NULL,PROGRESSIVE CO-OP BANK,NULL,KKBK0PCBL03,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
344,NULL,PT BANK MAYBANK INDONESIA TBK,NULL,IBBK0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
345,NULL,Puduvai Bharathiar Grama Bank,NULL,IDIB0PBG001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
346,NULL,Pune Cantonment Sahakari Bank,NULL,HDFC0CPCSBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
347,NULL,PUNE DISTRICT CENTRAL CO OP BANK,NULL,HDFC0CPDCCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
348,NULL,PUNE MERCHANTS CO-OPERATIVE BANK LTD,NULL,IBKL0548PMC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
349,NULL,Pune Peoples Cooperative Bank,NULL,IBKL0548PPC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
350,NULL,Punjab and Maharashtra Co Op Bank,NULL,PMCB0000247,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
351,NULL,PUNJAB AND MAHARSHTRA COOPERATIVE BANK,NULL,PMCB0000247,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
352,NULL,PUNJAB AND SIND BANK,NULL,PSIB0000388,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
353,NULL,Punjab Gramin Bank,NULL,PUNB0PGB003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
354,NULL,PUNJAB NATIONAL BANK,NULL,PUNB0012000,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
355,NULL,PUNJAB NATIONAL GRAMIN BANK,NULL,PUNB0PGB003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
356,NULL,Purnea District Central Coop Bank,NULL,YESB0PDCCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
357,NULL,PURVANCHAL GRAMIN BANK,NULL,BARB0BUPGBX,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
358,NULL,QATAR NATIONAL BANK SAQ,NULL,QNBA0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
359,NULL,RABOBANK INTERNATIONAL,NULL,RABO0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
360,NULL,RAJAPUR URBAN COOP BANK LTD,NULL,ICIC00RUCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
361,NULL,RAJARAMBAPU SAHAKARI BANK LIMITED,NULL,RRBP0000004,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
362,NULL,RAJARSHI SHAHU SAH BANK LTD,NULL,HDFC0CRSSBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
363,NULL,RAJARSHI SHAHU SAHAKARI BANK LTD PUNE,NULL,HDFC0CRSSBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
364,NULL,Rajasthan Gramin Bank,NULL,BARB0BRGBXX,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
365,NULL,Rajasthan marudhara Garmin bank,NULL,RMGB0000139,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
366,NULL,RAJASTHAN MARUDHARA GRAMIN BANK,NULL,RMGB0000036,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
367,NULL,RAJGURUNAGAR SAHAKARI BANK LIMITED,NULL,RSBL0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
368,NULL,Rajkot District Central Co Op Bank Ltd,NULL,GSCB0RJT001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
369,NULL,RAJKOT NAGRIK SAHAKARI BANK LIMITED,NULL,RNSB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
370,NULL,RAJKOT PEOPLES CO-OP BANK LTD,NULL,IBKL01642RP,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
371,NULL,RAJLAXMI URBAN CO-OPERATIVE BANK LTD,NULL,YESB0RLB003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
372,NULL,Ratnagiri District Central Co Op Bank,NULL,IBKL0574RDC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
373,NULL,RBL Bank Credit Card,NULL,RATN0CRCARD,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
374,NULL,RBL Bank Limited,NULL,RATN0000192,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
375,NULL,"RESERVE BANK OF INDIA, PAD",NULL,RBIS0MBPA04,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
376,NULL,Rewa-Sidhi Gramin Bank,NULL,UBIN0RRBRSG,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
377,NULL,Rushikulya Gramin Bank,NULL,ANDB0008999,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
378,NULL,SAHEBRAO DESHMUKH COOPERATIVE BANK LIMITED,NULL,SAHE0000003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
379,NULL,Sahyadri sahakari bank,NULL,SVCB0013003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
380,NULL,Saibaba Nagari Sahakari Bank Ltd,NULL,UTIB0SSNS01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
381,NULL,SAMARTH SAHAKARI BANK LTD,NULL,SBLS0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
382,NULL,Samastipur Kshetriya GB,NULL,SBIN0RRSMGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
383,NULL,SAMATA SAHAKARI BANK LIMITED,NULL,SRCB0SAM001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
384,NULL,SAMPADA SAHAKARI BANK LTD,NULL,IBKL0459SBS,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
385,NULL,SANGALI SAHKARI BANK LTD,NULL,UTIB0SSSB02,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
386,NULL,SANGLI DISTRICT CENTRAL CO OP BANK LTD,NULL,IBKL0487SDC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
387,NULL,Sanmati Sahakari Bank Ichalkaranji,NULL,UTIB0SSSBL1,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
388,NULL,SANT SOPANKAKA SAHAKARI BANK LTD,NULL,SANT0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
389,NULL,Saptagiri Grameena Bank,NULL,IDIB0SGB001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
390,NULL,SARASPUR NAGARIK CO.OP.BANK LTD,NULL,GSCB0USNCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
391,NULL,Saraspur Nagrik Co operative Bank Ltd Saraspur,NULL,SNBK0000009,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
392,NULL,Saraspur Nagrik CoOperative Bank Ltd,NULL,SNBK0000003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
393,NULL,SARASWAT COOPERATIVE BANK LIMITED,NULL,SRCB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
394,NULL,SARVA HARYANA GRAMIN BANK,NULL,PUNB0HGB001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
395,NULL,Sarva UP Gramin Bank,NULL,PUNB0SUPGB5,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
396,NULL,satara District central Coop Bank,NULL,IBKL0485SDC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
397,NULL,Saurashtra Gramin Bank,NULL,SBIN0RRSRGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
398,NULL,SBER BANK,NULL,SABR0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
399,NULL,SBM BANK INDIA LIMITED,NULL,STCB0000065,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
400,NULL,SBM BANK MAURITIUS LIMITED,NULL,STCB0000065,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
401,NULL,SHANKAR NAGARI SAHKARI BK NANDED,NULL,SVCB0023002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
402,NULL,SHARAD SAHAKARI BANK LTD MANCHAR,NULL,HDFC0CSHSBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
403,NULL,Sharda Gramin Bank,NULL,ALLA0SG5058,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
404,NULL,SHIKSHAK SAHAKARI BANK LIMITED,NULL,SKSB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
405,NULL,SHINHAN BANK,NULL,SHBK0000004,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
406,NULL,SHIVALIK MERCANTILE CO OPERATIVE BANK LTD,NULL,IBKL0236SMB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
407,NULL,Shree Kadi Nagarik Sahakari Bank Ltd,NULL,YESB0KNB006,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
408,NULL,SHREE TALAJA NAGARIK SAHA BANK LTD,NULL,KKBK0TNSB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
409,NULL,Shreyas Gramin Bank,NULL,CNRB000SGB7,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
410,NULL,SHRI ADINATH CO OP BANK LTD,NULL,HDFC0CSACBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
411,NULL,Shri Basaveshwar Sahakari Bank,NULL,ICIC00SBSBN,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
412,NULL,SHRI CHHATRAPATI RAJASHRI SHAHU URBAN COOPERATIVE BANK LIMITED,NULL,CRUB0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
413,NULL,Shri Shiveshwar Nagri Sahakari Bank,NULL,UTIB0SSSN01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
414,NULL,Shri Veershaiv Co Op Bank Ltd,NULL,SVSH0000027,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
415,NULL,Shrikrishna Cooperative Bank Ltd Umrer,NULL,SVCB0037002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
416,NULL,SINDHUDURG DISTRICT CENTRAL COOP BANK LTD,NULL,SIDC0001106,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
417,NULL,SIR M VISVESVARAYA CO OPERATIVE BANK LTD,NULL,INDB0VCB003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
418,NULL,SOCIETE GENERALE,NULL,SOGE0INBB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
419,NULL,SOLAPUR JANATA SAHAKARI BANK LIMITED,NULL,SJSB0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
420,NULL,SOUTH INDIAN BANK,NULL,SIBL0000153,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
421,NULL,South Malabar Gramin Bank,NULL,CNRB00SMGB4,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
422,NULL,Sree Narayana Guru Co-operative bank limited,NULL,SVCB0020002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
423,NULL,STANDARD CHARTERED BANK,NULL,SCBL0036086,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
424,NULL,STATE BANK OF BIKANER AND JAIPUR,NULL,SBIN0031001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
425,NULL,STATE BANK OF HYDERABAD,NULL,SBIN0020001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
426,NULL,STATE BANK OF INDIA,NULL,SBIN0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
427,NULL,STATE BANK OF INDIA1132,NULL,SBIN0014461,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
428,NULL,STATE BANK OF MAURITIUS LTD,NULL,STCB0000065,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
429,NULL,STATE BANK OF MYSORE,NULL,SBIN0040001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
430,NULL,STATE BANK OF PATIALA,NULL,SBIN0050001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
431,NULL,STATE BANK OF TRAVANCORE,NULL,SBIN0070001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
432,NULL,STERLING URBAN CO-OP BANK LTD,NULL,HDFC0CSTUCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
433,NULL,Subhadra Local Area Bank Ltd branch Hdfc Bank Ltd,NULL,HDFC0CSLABK,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
434,NULL,SUCO SOUHARDA SAHAKARI BANK LTD,NULL,HDFC0CSUCOB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
435,NULL,SUMITOMO MITSUI BANKING CORPORATION,NULL,SMBC0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
436,NULL,Sundarlal Sawji Urban Co Op Bank Ltd,NULL,SRCB0SSB019,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
437,NULL,Surat District Co-op bank,NULL,SDCB0000099,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
438,NULL,SURAT MERC COOP BANK KAPODARA YES BANK LTD,NULL,YESB0SMCB09,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
439,NULL,SURAT NATIONAL COOPERATIVE BANK LIMITED,NULL,SUNB0000010,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
440,NULL,Surguja Kshetriya Gramin Bank,NULL,CBIN0R60051,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
441,NULL,SURYODAY SMALL FINANCE BANK LIMITED,NULL,SURY0000017,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
442,NULL,SUSHMA GAJANAN CHOPDEKAR,NULL,YESB0GSCB53,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
443,NULL,SUTEX COOPERATIVE BANK LIMITED,NULL,SUTB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
444,NULL,Sutlej Gramin Bank,NULL,PSIB0SGB002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
445,NULL,SVC CO OPERATIVE BANK LTD,NULL,SVCB0000062,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
446,NULL,SWARNA BHARAT TRUST CYBER GRAMEEN,NULL,ANDB0001538,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
447,NULL,Swarnayug Sehkari Bank,NULL,HDFC0CSUVRN,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
448,NULL,SYNDICATE BANK,NULL,SYNB0009001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
449,NULL,TAMILNAD MERCANTILE BANK LIMITED,NULL,TMBL0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
450,NULL,Tamilnad Mercantile Bank Ltd,NULL,TMBL0000429,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
451,NULL,TAMILNADU Grama Bank,NULL,IOBA0PGB001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
452,NULL,Tamluk Ghatal Central Cooperative Bank Limited,NULL,WBSC0TCCB14,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
453,NULL,TEHRI GARHWAL ZILA SAHKARI BANK LIMITED,NULL,IBKL0070T32,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
454,NULL,Telangana Grameena Bank,NULL,SBHY0RRDCGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
455,NULL,TELANGANA STATE COOP APEX BANK,NULL,TSAB0014014,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
456,NULL,TEXTILE TRADERS CO OPERATIVE BANK LTD,NULL,HDFC0CTTCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
457,NULL,TEXTILE TRADERS CO-OPERATIVE BANK LIMITED,NULL,HDFC0CTTCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
458,NULL,Thane Janta Sahkari Bank Ltd,NULL,TJSB0000113,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
459,NULL,THE A.P. MAHESH COOPERATIVE URBAN BANK LIMITED,NULL,APMC0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
460,NULL,The Abhinav sahakari bank ltd,NULL,SVCB0007002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
461,NULL,The Adarsh Cooperative Urban Bank Ltd,NULL,ICIC00ADRSH,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
462,NULL,THE ADILABAD DCCB LTD,NULL,TSAB0019034,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
463,NULL,THE AHMEDABAD MERCANTILE CO-OPERATIVE BANK LTD,NULL,AMCB0660019,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
464,NULL,The Ajara Urban Co op Bank Ltd Ajara,NULL,AJAR0000005,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
465,NULL,The Ajara Urban Co-Op Bank Ltd,NULL,IBKL0116AUC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
466,NULL,THE AKOLA DISTRICT CENTRAL COOPERATIVE BANK,NULL,ADCC0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
467,NULL,The amistar central co oprative bank,NULL,UTIB0SASR01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
468,NULL,THE ANDHRA PRADESH STATE COOPERATIVE BANK LIMITED,NULL,APBL0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
469,NULL,The Annasaheb Savant Cooperative Urban Bank,NULL,HDFC0CMAHAD,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
470,NULL,The Assam Coop Apex Bank Ltd,NULL,HDFC0CACABL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
471,NULL,The Babasaheb Deshmukh Sahakari Bank Ltd,NULL,IBKL0467BDS,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
472,NULL,THE BANK OF NOVA SCOTIA,NULL,NOSC0000DEL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
473,NULL,THE BANK OF RAJASTHAN LTD,NULL,BRAJ0002120,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
474,NULL,THE BANKI CENTRAL COOPERATIVE BANK LTD,NULL,YESB0BNKCCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
475,NULL,THE BARAMATI SAHAKARI BANK LTD,NULL,BARA0000100,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
476,NULL,The barmer central co-operative bank ltd,NULL,RSCB0014028,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
477,NULL,The Baroda Central Co-Op Bank LTD,NULL,GSCB0BRD001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
478,NULL,The Begusarai District Central Co Operative Bank,NULL,IBKL01077BD,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
479,NULL,The Bhagalpur Central CoOperative Bank,NULL,IBKL0721BCC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
480,NULL,THE BHARAT CO-OPERATIVE BANK (MUMBAI) LTD,NULL,BCBM0000009,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
481,NULL,THE BHAVANIPATNA CENTRAL COOPERATIVE BANK LTD,NULL,ICIC00BHCCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
482,NULL,The Bhuj Mercentile bank,NULL,HDFC0CBMCBJ,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
483,NULL,THE BORAL UNION COOPERATIVE BANK LTD,NULL,HDFC0CTBUCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
484,NULL,The Bundi Central Cooperative Bank,NULL,RSCB0018001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
485,NULL,The Catholic Syrian Bank Ltd,NULL,CSBK0000283,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
486,NULL,The Chitnavispura Sahakari Bank Ltd,NULL,ICIC00TCSBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
487,NULL,The Citizen Co Operative Bank ltd,NULL,UTIB0STCCB1,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
488,NULL,THE COSMOS CO OPERATIVE BANK LIMITED,NULL,COSB0000019,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
489,NULL,THE COSMOS CO-OPERATIVE BANK LTD.,NULL,COSB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
490,NULL,The Dahod Mercantile Coop Bank Ltd,NULL,HDFC0CDMCBD,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
491,NULL,The Deccan merchants co operative bank ltd,NULL,IBKL0501DMC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
492,NULL,THE DELHI STATE COOPERATIVE BANK LIMITED,NULL,DLSC0000038,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
493,NULL,THE DISTRICT COOP CENTRAL BANK LTD BIDAR,NULL,KSCB0018001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
494,NULL,THE DISTRICT COOPERATIVE BANK LTD,NULL,ICIC00PRDCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
495,NULL,THE DISTRICT COOPERATIVE CENTRAL BANK LTD ELURU,NULL,APBL0005034,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
496,NULL,THE FEDERAL BANK LTD,NULL,FDRL0001820,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
497,NULL,THE GADCHIROLI DISTRICT CENTRAL COOPERATIVE BANK LIMITED,NULL,GDCB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
498,NULL,The Gandhinagar Nagarik Co-Operative Bank Limited,NULL,HDFC0CGNCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
499,NULL,THE GAYATRI CO OPERATIVE URBAN BANK LTD,NULL,HDFC0CTGCUB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
500,NULL,THE GOPALGANJ CENTRAL CO OPERATIVE BANK LTD,NULL,IBKL01011GC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
501,NULL,THE GREATER BOMBAY COOPERATIVE BANK LIMITED,NULL,GBCB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
502,NULL,THE GUJARAT STATE CO OPERATIVE BANK LTD AMRELI JILLA SAHAKARI BANK LTD,NULL,GSCB0AMR001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
503,NULL,THE GUJARAT STATE CO OPERATIVE BANK LTD KODINAR TALUKA CO OP BANKING UNION LTD,NULL,GSCB0KDT001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
504,NULL,THE GUJARAT STATE COOPERATIVE BANK LIMITED,NULL,GSCB0ASCB02,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
505,NULL,THE GUJARAT STATE CO-OPERATIVE BANK LTD KATCH DISTRICT CENTRAL COOP BANK LTD,NULL,GSCB0KTC001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
506,NULL,The Guntur Co-operative Urban Bank Ltd,NULL,UTIB0SGUB02,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
507,NULL,THE GURDASPUR CENTRAL COOPERATIVE BANK LTD,NULL,UTIB0SGDS01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
508,NULL,The Haryana State Co op Apex Bank LTD,NULL,HARC0000013,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
509,NULL,THE HASTI COOP BANK LTD,NULL,HCBL0000102,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
510,NULL,The Hyderabad District Co Operative Central Bank Ltd Tandur,NULL,TSAB0015018,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
511,NULL,THE JAIPUR CENTRAL CO-OPERATIVE BANK LTD,NULL,RSCB0022003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
512,NULL,THE JALGAON PEOPELS COOPERATIVE BANK LIMITED,NULL,JPCB0000013,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
513,NULL,THE JAMMU AND KASHMIR BANK LTD,NULL,JAKA0CIRCUS,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
514,NULL,THE JAMNAGAR DISTRICT CO OP BANK LTD,NULL,GSCB0JMN001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
515,NULL,The Janatha Co-operative Bank,NULL,HDFC0CTJCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
516,NULL,THE JHAJJAR CENTRAL COOPERATIVE BANK LTD,NULL,UTIB0JCCB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
517,NULL,The Jhalod Urban Cooperative Bank Ltd,NULL,GSCB0UJALOD,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
518,NULL,THE JIND CENTRAL COOPERATIVE BANK LTD,NULL,UTIB0JIND01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
519,NULL,The Kalol Nagarik Sahakari Bank LTD,NULL,IBKL01282KB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
520,NULL,THE KALUPUR COMMERCIAL CO OP BANK LTD,NULL,KCCB0GHA046,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
521,NULL,The Kalupur commercial co-operative bank Ltd,NULL,KCCB0VSR015,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
522,NULL,THE KALYAN JANATA SAHAKARI BANK LTD,NULL,KJSB0000006,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
523,NULL,THE KANGRA CENTRAL COOPERATIVE BANK LIMITED,NULL,KANG0000003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
524,NULL,THE KANGRA COOPERATIVE BANK LIMITED,NULL,KANG0000003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
525,NULL,THE KANYAKUMARI DISTRICT CENTRAL COOPERATIVE BANK LTD,NULL,TNSC0010300,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
526,NULL,THE KARAD URBAN COOPERATIVE BANK LIMITED,NULL,KUCB0488006,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
527,NULL,THE KARANATAKA STATE COOPERATIVE APEX BANK LIMITED,NULL,KSCB0001028,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
528,NULL,THE KARIMNAGAR DISTRICT CO OPERATIVE CENTRAL BANK LTD,NULL,TSAB0020049,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
529,NULL,THE KARNATAKA STATE APEX COOP BANK,NULL,KSCB0001049,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
530,NULL,THE KASARAGOD DISTRICT COOPERATIVE BANK LTDTHE KASARAGOD DISTRICT COOPERATIVE BANK LTD,NULL,IBKL0450TKD,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
531,NULL,The Kerala State Co Operative Bank Ltd,NULL,KSBK0000101,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
532,NULL,THE KOLHAPUR URBAN COOP BANK,NULL,HDFC0CKUCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
533,NULL,THE KOLLAM DISTRICT COOP BANK LTD,NULL,YESB0KLMDCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
534,NULL,THE KRISHNA DISTRICT CO-OPERATIVE CENTRAL BANK LTD,NULL,APBL0006035,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
535,NULL,The Kurla Nagarik Sahakari Bank Ltd,NULL,ICIC00KURLA,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
536,NULL,THE KURMANCHAL NAGAR SAHAKARI BANK LIMITED,NULL,KNSB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
537,NULL,THE LAKSHMI VILAS BANK LTD,NULL,LAVB0000999,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
538,NULL,THE LATUR URBAN CO OP BANK LTD,NULL,IBKL0497LUC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
539,NULL,The Limdi Urban Coop Bank Ltd,NULL,GSCB0UTLUCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
540,NULL,THE MAGADH CENTRAL COOPERATIVE BANK LTD,NULL,IBKL0414MCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
541,NULL,The Mahendragarh Central Coop Bank Ltd,NULL,UTIB0SMCCB1,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
542,NULL,The Malegaon Merchant S Co Operative Bank Ltd,NULL,IBKl0533MMC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
543,NULL,The Malkapur Urban Co Operative Bank Ltd Malkapur,NULL,MKPB0000110,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
544,NULL,The Malkapur Urban Coop Bank Ltd,NULL,MKPB0000109,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
545,NULL,The Mandya District Cooperative Central Bank Ltd,NULL,KSCB0008001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
546,NULL,THE MANGALORE CATHOLIC CO OPERATIVE BANK LTD,NULL,IBKL0078MCC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
547,NULL,the meghalaya co-operative apex bank ltd,NULL,YESB0MCA015,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
548,NULL,THE MEHSANA URBAN COOPERATIVE BANK,NULL,MSNU0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
549,NULL,The Mogaveera Co operative Bank Ltd,NULL,IBKL0452MCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
550,NULL,THE MUMBAI DISTRICT CENTRAL COOPERATIVE BANK LIMITED,NULL,MDCB0680004,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
551,NULL,THE MUNICIPAL COOPERATIVE BANK LIMITED,NULL,MUBL0000013,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
552,NULL,THE MUSLIM CO OP BANK LTD PUNE,NULL,HDFC0CMUSLM,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
553,NULL,The Muslim Co-operative Bank Ltd,NULL,MSLM0000003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
554,NULL,THE MUZAFFARPUR CENTRAL CO-OPERATIVE BANK LTD,NULL,IBKL0294MCC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
555,NULL,THE NABADWIP CO OPERATIVE CREDIT BANK LTD,NULL,HDFC0CNCCBL,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
556,NULL,THE NAINITAL BANK LIMITED,NULL,NTBL0RAN004,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
557,NULL,THE NASIK MERCHANTS COOPERATIVE BANK LIMITED,NULL,NMCB0000039,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
558,NULL,THE NATIONAL COOP BANK LTD,NULL,YESB0NBL002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
559,NULL,The Navjeevan Coop Bank Ltd,NULL,ICIC00NVJVN,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
560,NULL,THE NAVNIRMAN CO-OPERATIVE BANK LIMITED,NULL,NVNM0000007,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
561,NULL,The New Urban Co Op Bank Ltd Rampur,NULL,HDFC0CNUCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
562,NULL,THE NILAMBUR CO OPERATIVE URBAN BANK LTD NILAMBUR,NULL,NCUB0000023,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
563,NULL,THE ODISHA STATE COOPERATIVE BANK LTD,NULL,ORCB0001014,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
564,NULL,The Ottapalam Co Operative Bank Ltd,NULL,IBKL07630CB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
565,NULL,THE PANDHARPUR URBAN COOP BANK LTD,NULL,PUCB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
566,NULL,THE PANIPAT CENTRAL COOPERATIVE BANK LTD,NULL,UTIB0PCCB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
567,NULL,The Panipat Urban Co-Operative Bank Ltd,NULL,YESB0PUCB15,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
568,NULL,The parbhani district central co-op bank,NULL,YESB0PDBH01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
569,NULL,THE PATHANAMTHITTA DISTRICT CO-OPERATIVE BANK,NULL,IBKL0339PDC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
570,NULL,The Pochampally Coop Urban Bank Ltd,NULL,HDFC0CPCUBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
571,NULL,THE PUNJAB STATE COOPERATIVE BANK LTD,NULL,UTIB0PSCB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
572,NULL,The Pusad Urban Cooperative Bank Ltd Pusad,NULL,PUSD0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
573,NULL,THE RAIGAD DISTRICT CENTRAL COOPERATIVE BANK LIMITED,NULL,IBKL0299RDC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
574,NULL,THE RAJASTHAN STATE COOPERATIVE BANK LIMITED,NULL,RSCB0012002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
575,NULL,THE RAJASTHAN STATE COOPERATIVE BANK LIMITED,NULL,RSCB0012002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
576,NULL,THE RATNAKAR BANK LTD,NULL,RATN0000182,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
577,NULL,The Rohika Central Cooperative Bank Ltd,NULL,IBKL01066RC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
578,NULL,The Ropar Central Cooperative Bank Ltd,NULL,UTIB0SRCB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
579,NULL,THE ROYAL BANK OF SCOTLAND N V,NULL,ABNA0100310,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
580,NULL,The SABARKANTHA DISTRICT CENTRAL COOP BANK LTD,NULL,GSCB0SKB001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
581,NULL,THE SARASWAT CO OPERATIVE BANK LTD F C ROAD,NULL,SRCB0000035,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
582,NULL,The Saraswat Co operative Bank Ltd KURLA N S BANK STATION ROAD,NULL,SRCB0KNS003,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
583,NULL,THE SARASWAT CO-OPERATIVE BANK LTD,NULL,SRCB0000358,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
584,NULL,The Sarvodaya co-op bank Ltd,NULL,HDFC0CSCBL1,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
585,NULL,THE SATARA SAHAKARI BANK LTD,NULL,TSSB0000006,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
586,NULL,The saurashtra co optative bank ltd,NULL,GSCB0USAURA,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
587,NULL,THE SEVA VIKAS COOPERATIVE BANK LIMITED,NULL,SVBL0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
588,NULL,THE SHAMRAO VITHAL COOPERATIVE BANK,NULL,SVCB0001002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
589,NULL,THE SHIVAMOGA DISTRICT COOPERATIVE CENTRAL BANK LIMITED,NULL,KSCB0005001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
590,NULL,THE SINDHUDURG DISTRICT CENTRAL COOP BANK LTD,NULL,SIDC0001022,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
591,NULL,THE SITAMARHI CENTRAL CO-OPERATIVE BANK,NULL,IBKL0719SCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
592,NULL,THE SIWAN CNETRAL CO OPERATIVE BANK LTD,NULL,IBKL01076SB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
593,NULL,THE SOLAPUR DISTRICT CENTRAL COOPERATIVE BANK LTD,NULL,ICIC00SDCCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
594,NULL,The Sonipat central cooperative bank ltd,NULL,UTIB0SONE01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
595,NULL,THE SOUTH CANARA DISTRICT CENTRAL,NULL,IBKL078SCDC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
596,NULL,THE SURAT DISTRICT COOPERATIVE BANK LIMITED,NULL,SDCB0000019,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
597,NULL,THE SURATH PEOPLES COOPERATIVE BANK LIMITED,NULL,SPCB0251011,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
598,NULL,The Surendranagar District Co-Op. Bank Ltd,NULL,GSCB0SNR001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
599,NULL,THE TAMIL NADU STATE APEX COOPERATIVE BANK,NULL,TNSC0015000,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
600,NULL,THE TASGAON URBAN CO OP BANK LTD,NULL,IBKL0608TUC,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
601,NULL,THE THANE BHARAT SAHAKARI BANK LIMITED,NULL,TBSB0000005,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
602,NULL,THE THANE DISTRICT CENTRAL COOPERATIVE BANK LIMITED,NULL,TDCB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
603,NULL,THE THANE JANATA SAHAKARI BANK LTD,NULL,TJSB0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
604,NULL,THE UDAIPUR URBAN CO OPERATIVE BANK LTD,NULL,UUCB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
605,NULL,The Udupi town cooperative Bank ltd,NULL,UTIB0SUCTBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
606,NULL,The Urban Co Operative Bank Ltd,NULL,HDFC0CTUCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
607,NULL,THE URBAN CO OPERATIVE BANK Ltd No ONE SEVEN FIVE EIGHT PERINTHALMANNA,NULL,URBN00000B6,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
608,NULL,THE VAISH CO-OPERATIVE NEW BANK LIMITED,NULL,YESB0VNB001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
609,NULL,THE VARACHHA COOPERATIVE BANK LIMITED,NULL,VARA0289010,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
610,NULL,The Vijay Co Operative Bank Limited,NULL,VCOB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
611,NULL,THE VILLUPURAM DISTRICT CENTRAL CO OP BANK LTD,NULL,TNSC0012200,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
612,NULL,THE VISHWESHWAR SAHAKARI BANK LIMITED,NULL,VSBL0000016,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
613,NULL,THE WEST BENGAL STATE COOPERATIVE BANK,NULL,WBSC0000021,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
614,NULL,The Yamuna Nagar Central Co-op. Bank Ltd,NULL,UTIB0YCCB01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
615,NULL,The Yavatmal District Central Co.Op. Bank Ltd,NULL,YESB0YDC001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
616,NULL,THE ZOROASTRIAN COOPERATIVE BANK LIMITED,NULL,ZCBL0000008,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
617,NULL,Thiruvananthapuram District Coperative Bank Ltd,NULL,IBKL0046T01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
618,NULL,"THIRUVANANTHAPURAM MAIN, SOUTH INDIAN BANK",NULL,SIBL0000119,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
619,NULL,THRISSUR DISTRICT CO-OPERATIVE BANK LTD,NULL,THRS0000031,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
620,NULL,TJSB SAHAKARI BANK LTD,NULL,TJSB0000107,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
621,NULL,Tripura Gramin Bank,NULL,PUNB0RRBTGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
622,NULL,TRIPURA STATE CO-OPERATIVE BANK LIMITED,NULL,ICIC00TSCBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
623,NULL,Triveni Kshetriya Gramin Bank,NULL,ALLA0AU1194,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
624,NULL,Tumkur district co-operative Central bank ltd,NULL,UTIB0STDCCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
625,NULL,TUMKUR GRAIN MERCHANTS COOPERATIVE BANK LIMITED,NULL,TGMB0000019,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
626,NULL,UBS AG,NULL,UBSW0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
627,NULL,UCO BANK,NULL,UCBA0001735,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
628,NULL,Ujjivan Small Finance Bank,NULL,UJVN0002201,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
629,NULL,Ujjivan Small Finance Bank Limited,NULL,UJVN0002204,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
630,NULL,UJJIVAN SMALL FINANCE BANK LTD,NULL,UJVN0004513,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
631,NULL,UNION BANK OF BANK,NULL,UBIN0820300,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
632,NULL,UNION BANK OF INDIA,NULL,UBIN0551945,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
633,NULL,UNITED BANK OF INDIA,NULL,UTBI0CON702,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
634,NULL,UNITED OVERSEAS BANK LIMITED,NULL,UOVB0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
635,NULL,Universal Co-Operative Urban Bank Ltd,NULL,HDFC0CUCUB9,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
636,NULL,Urban Co operative Bank Ltd,NULL,YESB0ICBL01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
637,NULL,URBAN COOPERATIVE BANK LTD BASTI,NULL,YESB0URBAN1,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
638,NULL,Utkal Gramya Bank,NULL,SBIN0RRUKGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
639,NULL,UTKARSH SMALL FINANCE BANK,NULL,UTKS0001356,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
640,NULL,Uttar Banga Kshetriya Gramin Bank,NULL,CBIN0R40012,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
641,NULL,Uttar Bihar Gramin Bank,NULL,CBIN0R10001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
642,NULL,UTTAR PRADESH COOPERATIVE BANK LTD,NULL,ICIC00UPSCB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
643,NULL,Uttarakhand Gramin Bank,NULL,SBIN0RRUTGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
644,NULL,Uttaranchal Gramin Bank,NULL,SBIN0RRUTGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
645,NULL,Vaishya Nagari Sahakari Bank Ltd Branch Axis Bank,NULL,UTIB0SVNS01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
646,NULL,Valsad District Central Co - Operative Bank,NULL,GSCB0VDC001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
647,NULL,Vananchal Gramin Bank,NULL,SBIN0RRVCGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
648,NULL,Vardhaman Mahila Co-op. Urban Bank Ltd,NULL,HDFC0CVB222,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
649,NULL,VASAI JANATA SAHAKARI BANK LTD,NULL,VASJ0000013,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
650,NULL,VASAI VIKAS SAHAKARI BANK LIMITED,NULL,VVSB0000002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
651,NULL,VASAI VIKAS SAHAKARI BANK LTD,NULL,VVSB0000018,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
652,NULL,Veraval Mercantile Co Operative Bank,NULL,HDFC0CVMCBA,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
653,NULL,VIDHARBHA KONKAN GRAMIN BANK,NULL,BKID0WAINGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
654,NULL,Vidharbha Kshetriya Gramin Bank,NULL,CBIN0R50002,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
655,NULL,Vidisha Bhopal Kshetriya Gramin Bank,NULL,SBIN0RRVDGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
656,NULL,VIJAYA BANK,NULL,VIJB0006071,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
657,NULL,Visveshwaraya Gramin Bank,NULL,SBMY0RRCKGB,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
658,NULL,VYAVSAYIK SAHKARI BANK LTD,NULL,YESBOVSBL04,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
659,NULL,Wainganga Krishna Gramin Bank,NULL,PKGB0010588,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
660,NULL,WEST BENGAL STATE CO-OPERATIVE BANK,NULL,WBSC0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
661,NULL,WESTPAC BANKING CORPORATION,NULL,WPAC0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
662,NULL,WOORI BANK,NULL,HVBK0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
663,NULL,YADAGIRI LAKSHIM NARASIMHA SWAMY CO- OP URBAN BANK,NULL,YESB0YLNS01,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
664,NULL,Yashwant Nagari Sahakari Bank Ltd,NULL,HDFC0CYNSBL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
665,NULL,YES BANK,NULL,YESB0000004,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
666,NULL,Yes Bank Credit Card,NULL,YESB0CMSNOC,NULL,NULL,1,NULL,1,NULL,NULL,NULL,NULL
667,NULL,YES BANK LTD KHALILABAD NAGAR SAH BANK SEMARIAWA,NULL,YESB0KHBKSN,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
668,NULL,YES BANK LTD SARVODAYA SAH BANK PUNA KUMBHARIA,NULL,YESB0SSBL05,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
669,NULL,YES BANK LTD UCB LAKHIMPUR PALIA KALAN,NULL,YESB0LUBPAL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
670,NULL,"YES BANK LTD, FINANCIAL COOP BANK KOHINOOR MKT",NULL,YESB0FINCO4,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
671,NULL,ZILA SAHAKARI BANK LTD,NULL,ICIC00KHIRI,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
672,NULL,ZILA SAHAKARI BANK LTD GARHWAL KOTDWARA,NULL,ICIC00ZSKTW,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
673,NULL,ZILA SAHKARI BANK LIMITED GHAZIABAD,NULL,ZSBL0000001,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
674,NULL,Zila Sahkari Bank Ltd,NULL,ICIC00BIJNR,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
675,NULL,ZILA SAHKARI BANK LTD LUCKNOW,NULL,ICIC00ZSBLL,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL
676,NULL,OD Right 2 Pay,NULL,0,NULL,NULL,0,NULL,1,NULL,NULL,NULL,NULL"""

async def seed_bank_master():
    print("Ensuring bank_master table exists...", flush=True)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    reader = csv.DictReader(io.StringIO(CSV_DATA))
    count = 0
    
    async with AsyncSessionLocal() as session:
        # Check existing count
        stmt_count = select(BankMasterModel)
        res_existing = await session.execute(stmt_count)
        existing_rows = res_existing.scalars().all()
        existing_ref_ids = {b.bank_ifsc_ref_id for b in existing_rows}

        for row in reader:
            ref_id = int(row["BankIFSCRefID"].strip())
            if ref_id in existing_ref_ids:
                continue

            bank_name = row["BankName"].strip()
            ifsc = row["IFSC"].strip().upper()
            ifsc_prefix = ifsc[:4] if len(ifsc) >= 4 else ifsc
            is_cc = True if row["CreditCard"].strip() == "1" else False
            status_val = int(row["Status"].strip()) if row["Status"].strip().isdigit() else 1

            bank_id_val = int(row["BankID"].strip()) if row["BankID"] and row["BankID"].strip().isdigit() else None
            short_code_val = row["ShortCode"].strip() if row["ShortCode"] and row["ShortCode"].strip() != "NULL" else None
            imps_val = row["IMPSStatus"].strip() if row["IMPSStatus"] and row["IMPSStatus"].strip() != "NULL" else "ACTIVE"
            neft_val = row["NEFTStatus"].strip() if row["NEFTStatus"] and row["NEFTStatus"].strip() != "NULL" else "ACTIVE"

            dummy_tenant_id = uuid.UUID("00000000-0000-0000-0000-000000000001")

            record = BankMasterModel(
                public_id=uuid.uuid4(),
                tenant_id=dummy_tenant_id,
                created_by="SYSTEM_SEED",
                bank_ifsc_ref_id=ref_id,
                bank_id=bank_id_val,
                bank_name=bank_name,
                short_code=short_code_val,
                ifsc=ifsc,
                ifsc_prefix=ifsc_prefix,
                imps_status=imps_val,
                neft_status=neft_val,
                is_credit_card=is_cc,
                status=status_val
            )
            session.add(record)
            count += 1

        await session.commit()
        print(f"Successfully seeded {count} bank master records into bank_master table!", flush=True)

if __name__ == "__main__":
    asyncio.run(seed_bank_master())
