"""epic_007_developer_schema

Revision ID: 444a26cc85da
Revises: '402ca8d1a0be'
Create Date: 2026-07-28 17:45:19.672285

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444a26cc85da'
down_revision: Union[str, None] = '402ca8d1a0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer_api_key',
    sa.Column('key_name', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('hashed_secret', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developer_api_key_client_id'), 'developer_api_key', ['client_id'], unique=True)
    op.create_index(op.f('ix_developer_api_key_company_id'), 'developer_api_key', ['company_id'], unique=False)
    op.create_index(op.f('ix_developer_api_key_is_active'), 'developer_api_key', ['is_active'], unique=False)
    op.create_index(op.f('ix_developer_api_key_is_deleted'), 'developer_api_key', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_developer_api_key_organization_id'), 'developer_api_key', ['organization_id'], unique=False)
    op.create_index(op.f('ix_developer_api_key_public_id'), 'developer_api_key', ['public_id'], unique=True)
    op.create_index(op.f('ix_developer_api_key_tenant_id'), 'developer_api_key', ['tenant_id'], unique=False)
    op.create_table('fraud_alert',
    sa.Column('transaction_ref', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_alert_company_id'), 'fraud_alert', ['company_id'], unique=False)
    op.create_index(op.f('ix_fraud_alert_is_active'), 'fraud_alert', ['is_active'], unique=False)
    op.create_index(op.f('ix_fraud_alert_is_deleted'), 'fraud_alert', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_fraud_alert_organization_id'), 'fraud_alert', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fraud_alert_public_id'), 'fraud_alert', ['public_id'], unique=True)
    op.create_index(op.f('ix_fraud_alert_risk_level'), 'fraud_alert', ['risk_level'], unique=False)
    op.create_index(op.f('ix_fraud_alert_status'), 'fraud_alert', ['status'], unique=False)
    op.create_index(op.f('ix_fraud_alert_tenant_id'), 'fraud_alert', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_fraud_alert_transaction_ref'), 'fraud_alert', ['transaction_ref'], unique=False)
    op.create_table('risk_rule',
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('threshold_amount', sa.Float(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_rule_company_id'), 'risk_rule', ['company_id'], unique=False)
    op.create_index(op.f('ix_risk_rule_is_active'), 'risk_rule', ['is_active'], unique=False)
    op.create_index(op.f('ix_risk_rule_is_deleted'), 'risk_rule', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_risk_rule_organization_id'), 'risk_rule', ['organization_id'], unique=False)
    op.create_index(op.f('ix_risk_rule_public_id'), 'risk_rule', ['public_id'], unique=True)
    op.create_index(op.f('ix_risk_rule_rule_code'), 'risk_rule', ['rule_code'], unique=True)
    op.create_index(op.f('ix_risk_rule_tenant_id'), 'risk_rule', ['tenant_id'], unique=False)
    op.create_table('webhook_subscription',
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('secret_key', sa.String(length=100), nullable=False),
    sa.Column('events', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_subscription_company_id'), 'webhook_subscription', ['company_id'], unique=False)
    op.create_index(op.f('ix_webhook_subscription_is_active'), 'webhook_subscription', ['is_active'], unique=False)
    op.create_index(op.f('ix_webhook_subscription_is_deleted'), 'webhook_subscription', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_webhook_subscription_organization_id'), 'webhook_subscription', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhook_subscription_public_id'), 'webhook_subscription', ['public_id'], unique=True)
    op.create_index(op.f('ix_webhook_subscription_tenant_id'), 'webhook_subscription', ['tenant_id'], unique=False)
    op.create_table('webhook_event_log',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscription.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_event_log_company_id'), 'webhook_event_log', ['company_id'], unique=False)
    op.create_index(op.f('ix_webhook_event_log_event_type'), 'webhook_event_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_event_log_is_active'), 'webhook_event_log', ['is_active'], unique=False)
    op.create_index(op.f('ix_webhook_event_log_is_deleted'), 'webhook_event_log', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_webhook_event_log_organization_id'), 'webhook_event_log', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhook_event_log_public_id'), 'webhook_event_log', ['public_id'], unique=True)
    op.create_index(op.f('ix_webhook_event_log_status'), 'webhook_event_log', ['status'], unique=False)
    op.create_index(op.f('ix_webhook_event_log_subscription_id'), 'webhook_event_log', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_webhook_event_log_tenant_id'), 'webhook_event_log', ['tenant_id'], unique=False)
    op.create_table('chargeback_case',
    sa.Column('case_reference', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('retailer_id', sa.UUID(), nullable=False),
    sa.Column('dispute_amount', sa.Float(), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'case_reference', name='uq_cb_tenant_ref')
    )
    op.create_index(op.f('ix_chargeback_case_case_reference'), 'chargeback_case', ['case_reference'], unique=False)
    op.create_index(op.f('ix_chargeback_case_company_id'), 'chargeback_case', ['company_id'], unique=False)
    op.create_index(op.f('ix_chargeback_case_is_active'), 'chargeback_case', ['is_active'], unique=False)
    op.create_index(op.f('ix_chargeback_case_is_deleted'), 'chargeback_case', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_chargeback_case_organization_id'), 'chargeback_case', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chargeback_case_public_id'), 'chargeback_case', ['public_id'], unique=True)
    op.create_index(op.f('ix_chargeback_case_retailer_id'), 'chargeback_case', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_chargeback_case_status'), 'chargeback_case', ['status'], unique=False)
    op.create_index(op.f('ix_chargeback_case_tenant_id'), 'chargeback_case', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chargeback_case_transaction_id'), 'chargeback_case', ['transaction_id'], unique=False)
    op.create_table('chargeback_evidence',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['chargeback_case.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chargeback_evidence_case_id'), 'chargeback_evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_chargeback_evidence_company_id'), 'chargeback_evidence', ['company_id'], unique=False)
    op.create_index(op.f('ix_chargeback_evidence_is_active'), 'chargeback_evidence', ['is_active'], unique=False)
    op.create_index(op.f('ix_chargeback_evidence_is_deleted'), 'chargeback_evidence', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_chargeback_evidence_organization_id'), 'chargeback_evidence', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chargeback_evidence_public_id'), 'chargeback_evidence', ['public_id'], unique=True)
    op.create_index(op.f('ix_chargeback_evidence_tenant_id'), 'chargeback_evidence', ['tenant_id'], unique=False)
    op.create_table('dispute_status_history',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=False),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by_email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('day_key', sa.Integer(), nullable=True),
    sa.Column('week_key', sa.Integer(), nullable=True),
    sa.Column('month_key', sa.Integer(), nullable=True),
    sa.Column('quarter_key', sa.Integer(), nullable=True),
    sa.Column('year_key', sa.Integer(), nullable=True),
    sa.Column('financial_year_key', sa.String(length=20), nullable=True),
    sa.Column('financial_quarter_key', sa.String(length=20), nullable=True),
    sa.Column('financial_month_key', sa.String(length=20), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('time_key', sa.Integer(), nullable=True),
    sa.Column('partition_year', sa.Integer(), nullable=True),
    sa.Column('partition_month', sa.Integer(), nullable=True),
    sa.Column('partition_day', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('record_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['chargeback_case.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_status_history_case_id'), 'dispute_status_history', ['case_id'], unique=False)
    op.create_index(op.f('ix_dispute_status_history_company_id'), 'dispute_status_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_dispute_status_history_is_active'), 'dispute_status_history', ['is_active'], unique=False)
    op.create_index(op.f('ix_dispute_status_history_is_deleted'), 'dispute_status_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dispute_status_history_organization_id'), 'dispute_status_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dispute_status_history_public_id'), 'dispute_status_history', ['public_id'], unique=True)
    op.create_index(op.f('ix_dispute_status_history_tenant_id'), 'dispute_status_history', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispute_status_history_tenant_id'), table_name='dispute_status_history')
    op.drop_index(op.f('ix_dispute_status_history_public_id'), table_name='dispute_status_history')
    op.drop_index(op.f('ix_dispute_status_history_organization_id'), table_name='dispute_status_history')
    op.drop_index(op.f('ix_dispute_status_history_is_deleted'), table_name='dispute_status_history')
    op.drop_index(op.f('ix_dispute_status_history_is_active'), table_name='dispute_status_history')
    op.drop_index(op.f('ix_dispute_status_history_company_id'), table_name='dispute_status_history')
    op.drop_index(op.f('ix_dispute_status_history_case_id'), table_name='dispute_status_history')
    op.drop_table('dispute_status_history')
    op.drop_index(op.f('ix_chargeback_evidence_tenant_id'), table_name='chargeback_evidence')
    op.drop_index(op.f('ix_chargeback_evidence_public_id'), table_name='chargeback_evidence')
    op.drop_index(op.f('ix_chargeback_evidence_organization_id'), table_name='chargeback_evidence')
    op.drop_index(op.f('ix_chargeback_evidence_is_deleted'), table_name='chargeback_evidence')
    op.drop_index(op.f('ix_chargeback_evidence_is_active'), table_name='chargeback_evidence')
    op.drop_index(op.f('ix_chargeback_evidence_company_id'), table_name='chargeback_evidence')
    op.drop_index(op.f('ix_chargeback_evidence_case_id'), table_name='chargeback_evidence')
    op.drop_table('chargeback_evidence')
    op.drop_index(op.f('ix_chargeback_case_transaction_id'), table_name='chargeback_case')
    op.drop_index(op.f('ix_chargeback_case_tenant_id'), table_name='chargeback_case')
    op.drop_index(op.f('ix_chargeback_case_status'), table_name='chargeback_case')
    op.drop_index(op.f('ix_chargeback_case_retailer_id'), table_name='chargeback_case')
    op.drop_index(op.f('ix_chargeback_case_public_id'), table_name='chargeback_case')
    op.drop_index(op.f('ix_chargeback_case_organization_id'), table_name='chargeback_case')
    op.drop_index(op.f('ix_chargeback_case_is_deleted'), table_name='chargeback_case')
    op.drop_index(op.f('ix_chargeback_case_is_active'), table_name='chargeback_case')
    op.drop_index(op.f('ix_chargeback_case_company_id'), table_name='chargeback_case')
    op.drop_index(op.f('ix_chargeback_case_case_reference'), table_name='chargeback_case')
    op.drop_table('chargeback_case')
    op.drop_index(op.f('ix_webhook_event_log_tenant_id'), table_name='webhook_event_log')
    op.drop_index(op.f('ix_webhook_event_log_subscription_id'), table_name='webhook_event_log')
    op.drop_index(op.f('ix_webhook_event_log_status'), table_name='webhook_event_log')
    op.drop_index(op.f('ix_webhook_event_log_public_id'), table_name='webhook_event_log')
    op.drop_index(op.f('ix_webhook_event_log_organization_id'), table_name='webhook_event_log')
    op.drop_index(op.f('ix_webhook_event_log_is_deleted'), table_name='webhook_event_log')
    op.drop_index(op.f('ix_webhook_event_log_is_active'), table_name='webhook_event_log')
    op.drop_index(op.f('ix_webhook_event_log_event_type'), table_name='webhook_event_log')
    op.drop_index(op.f('ix_webhook_event_log_company_id'), table_name='webhook_event_log')
    op.drop_table('webhook_event_log')
    op.drop_index(op.f('ix_webhook_subscription_tenant_id'), table_name='webhook_subscription')
    op.drop_index(op.f('ix_webhook_subscription_public_id'), table_name='webhook_subscription')
    op.drop_index(op.f('ix_webhook_subscription_organization_id'), table_name='webhook_subscription')
    op.drop_index(op.f('ix_webhook_subscription_is_deleted'), table_name='webhook_subscription')
    op.drop_index(op.f('ix_webhook_subscription_is_active'), table_name='webhook_subscription')
    op.drop_index(op.f('ix_webhook_subscription_company_id'), table_name='webhook_subscription')
    op.drop_table('webhook_subscription')
    op.drop_index(op.f('ix_risk_rule_tenant_id'), table_name='risk_rule')
    op.drop_index(op.f('ix_risk_rule_rule_code'), table_name='risk_rule')
    op.drop_index(op.f('ix_risk_rule_public_id'), table_name='risk_rule')
    op.drop_index(op.f('ix_risk_rule_organization_id'), table_name='risk_rule')
    op.drop_index(op.f('ix_risk_rule_is_deleted'), table_name='risk_rule')
    op.drop_index(op.f('ix_risk_rule_is_active'), table_name='risk_rule')
    op.drop_index(op.f('ix_risk_rule_company_id'), table_name='risk_rule')
    op.drop_table('risk_rule')
    op.drop_index(op.f('ix_fraud_alert_transaction_ref'), table_name='fraud_alert')
    op.drop_index(op.f('ix_fraud_alert_tenant_id'), table_name='fraud_alert')
    op.drop_index(op.f('ix_fraud_alert_status'), table_name='fraud_alert')
    op.drop_index(op.f('ix_fraud_alert_risk_level'), table_name='fraud_alert')
    op.drop_index(op.f('ix_fraud_alert_public_id'), table_name='fraud_alert')
    op.drop_index(op.f('ix_fraud_alert_organization_id'), table_name='fraud_alert')
    op.drop_index(op.f('ix_fraud_alert_is_deleted'), table_name='fraud_alert')
    op.drop_index(op.f('ix_fraud_alert_is_active'), table_name='fraud_alert')
    op.drop_index(op.f('ix_fraud_alert_company_id'), table_name='fraud_alert')
    op.drop_table('fraud_alert')
    op.drop_index(op.f('ix_developer_api_key_tenant_id'), table_name='developer_api_key')
    op.drop_index(op.f('ix_developer_api_key_public_id'), table_name='developer_api_key')
    op.drop_index(op.f('ix_developer_api_key_organization_id'), table_name='developer_api_key')
    op.drop_index(op.f('ix_developer_api_key_is_deleted'), table_name='developer_api_key')
    op.drop_index(op.f('ix_developer_api_key_is_active'), table_name='developer_api_key')
    op.drop_index(op.f('ix_developer_api_key_company_id'), table_name='developer_api_key')
    op.drop_index(op.f('ix_developer_api_key_client_id'), table_name='developer_api_key')
    op.drop_table('developer_api_key')
    # ### end Alembic commands ###
