"""initial_foundational_schema

Revision ID: b1d57278aafc
Revises: None
Create Date: 2026-07-28 08:49:49.512216

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1d57278aafc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_admin_user_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_admin_user_tenant_username')
    )
    op.create_index(op.f('ix_admin_user_company_id'), 'admin_user', ['company_id'], unique=False)
    op.create_index(op.f('ix_admin_user_email'), 'admin_user', ['email'], unique=False)
    op.create_index(op.f('ix_admin_user_is_deleted'), 'admin_user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_admin_user_public_id'), 'admin_user', ['public_id'], unique=True)
    op.create_index(op.f('ix_admin_user_tenant_id'), 'admin_user', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_admin_user_username'), 'admin_user', ['username'], unique=False)
    op.create_table('audit_log',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_company_id'), 'audit_log', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_public_id'), 'audit_log', ['public_id'], unique=True)
    op.create_index(op.f('ix_audit_log_resource_type'), 'audit_log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('entity',
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_company_id'), 'entity', ['company_id'], unique=False)
    op.create_index(op.f('ix_entity_is_deleted'), 'entity', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_entity_public_id'), 'entity', ['public_id'], unique=True)
    op.create_index(op.f('ix_entity_tenant_id'), 'entity', ['tenant_id'], unique=False)
    op.create_table('permission',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_code'), 'permission', ['code'], unique=True)
    op.create_index(op.f('ix_permission_module'), 'permission', ['module'], unique=False)
    op.create_index(op.f('ix_permission_public_id'), 'permission', ['public_id'], unique=True)
    op.create_table('role',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_role_tenant_code')
    )
    op.create_index(op.f('ix_role_code'), 'role', ['code'], unique=False)
    op.create_index(op.f('ix_role_is_deleted'), 'role', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_role_public_id'), 'role', ['public_id'], unique=True)
    op.create_index(op.f('ix_role_tenant_id'), 'role', ['tenant_id'], unique=False)
    op.create_table('system_configuration',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_system_config_tenant_key')
    )
    op.create_index(op.f('ix_system_configuration_key'), 'system_configuration', ['key'], unique=False)
    op.create_index(op.f('ix_system_configuration_public_id'), 'system_configuration', ['public_id'], unique=True)
    op.create_index(op.f('ix_system_configuration_tenant_id'), 'system_configuration', ['tenant_id'], unique=False)
    op.create_table('tenant',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_code'), 'tenant', ['code'], unique=True)
    op.create_index(op.f('ix_tenant_is_deleted'), 'tenant', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tenant_public_id'), 'tenant', ['public_id'], unique=True)
    op.create_table('api_key',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_company_id'), 'api_key', ['company_id'], unique=False)
    op.create_index(op.f('ix_api_key_is_deleted'), 'api_key', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_api_key_key_prefix'), 'api_key', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_key_public_id'), 'api_key', ['public_id'], unique=True)
    op.create_index(op.f('ix_api_key_tenant_id'), 'api_key', ['tenant_id'], unique=False)
    op.create_table('company',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_company_tenant_code')
    )
    op.create_index(op.f('ix_company_code'), 'company', ['code'], unique=False)
    op.create_index(op.f('ix_company_is_deleted'), 'company', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_public_id'), 'company', ['public_id'], unique=True)
    op.create_index(op.f('ix_company_tenant_id'), 'company', ['tenant_id'], unique=False)
    op.create_table('password_reset_token',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_token_public_id'), 'password_reset_token', ['public_id'], unique=True)
    op.create_index(op.f('ix_password_reset_token_token_hash'), 'password_reset_token', ['token_hash'], unique=True)
    op.create_table('role_permission',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permission_public_id'), 'role_permission', ['public_id'], unique=True)
    op.create_index(op.f('ix_role_permission_tenant_id'), 'role_permission', ['tenant_id'], unique=False)
    op.create_table('user_role',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_role_public_id'), 'user_role', ['public_id'], unique=True)
    op.create_index(op.f('ix_user_role_tenant_id'), 'user_role', ['tenant_id'], unique=False)
    op.create_table('user_session',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('token_jti', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_session_is_revoked'), 'user_session', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_user_session_public_id'), 'user_session', ['public_id'], unique=True)
    op.create_index(op.f('ix_user_session_tenant_id'), 'user_session', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_session_token_jti'), 'user_session', ['token_jti'], unique=True)


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_suggestions',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('suggested_topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('suggested_title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('suggested_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('suggested_day', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('suggested_hashtags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('90.0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('content_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('business_objective', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('campaign_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_accepted', sa.VARCHAR(length=50), server_default=sa.text("'0'::character varying"), autoincrement=False, nullable=True),
    sa.Column('accepted_content_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('content_suggestions_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('content_suggestions_pkey'))
    )
    op.create_table('profiles',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('authentication_provider', sa.VARCHAR(length=50), server_default=sa.text("'EMAIL'::character varying"), autoincrement=False, nullable=True),
    sa.Column('google_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('profile_image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'Admin'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('profiles_pkey')),
    sa.UniqueConstraint('email', name=op.f('profiles_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('workspace_members',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'Owner'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('workspace_members_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('workspace_members_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_members_pkey'))
    )
    op.create_table('ai_provider_configs',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('topic_provider', sa.VARCHAR(length=100), server_default=sa.text("'OpenAI'::character varying"), autoincrement=False, nullable=True),
    sa.Column('topic_model', sa.VARCHAR(length=100), server_default=sa.text("'gpt-4o'::character varying"), autoincrement=False, nullable=True),
    sa.Column('image_provider', sa.VARCHAR(length=100), server_default=sa.text("'OpenAI Images'::character varying"), autoincrement=False, nullable=True),
    sa.Column('image_model', sa.VARCHAR(length=100), server_default=sa.text("'dall-e-3'::character varying"), autoincrement=False, nullable=True),
    sa.Column('vision_provider', sa.VARCHAR(length=100), server_default=sa.text("'OpenAI'::character varying"), autoincrement=False, nullable=True),
    sa.Column('vision_model', sa.VARCHAR(length=100), server_default=sa.text("'gpt-4o-vision'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('ai_provider_configs_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_provider_configs_pkey'))
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey'))
    )
    op.create_table('ai_execution_logs',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=100), server_default=sa.text("'Ollama'::character varying"), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), server_default=sa.text("'qwen3:8b'::character varying"), autoincrement=False, nullable=True),
    sa.Column('pipeline_stage', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('latency', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.5'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'SUCCESS'::character varying"), autoincrement=False, nullable=True),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('ai_execution_logs_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_execution_logs_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('google_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('authentication_provider', sa.VARCHAR(length=50), server_default=sa.text("'EMAIL'::character varying"), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('profile_image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'Admin'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('visual_intelligence_reports',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_classification', sa.VARCHAR(length=150), server_default=sa.text("'Architecture Design'::character varying"), autoincrement=False, nullable=False),
    sa.Column('visual_scene', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=True),
    sa.Column('visual_style', sa.VARCHAR(length=150), server_default=sa.text("'Enterprise Architecture Diagram'::character varying"), autoincrement=False, nullable=True),
    sa.Column('generated_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('negative_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('topic_match_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('95.0'), autoincrement=False, nullable=True),
    sa.Column('is_accepted', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('visual_intelligence_reports_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('visual_intelligence_reports_pkey'))
    )
    op.create_table('validation_reports',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('validation_type', sa.VARCHAR(length=100), server_default=sa.text("'POST'::character varying"), autoincrement=False, nullable=True),
    sa.Column('validation_result', sa.VARCHAR(length=50), server_default=sa.text("'PASS'::character varying"), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('95.0'), autoincrement=False, nullable=True),
    sa.Column('errors', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('warnings', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('suggestions', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('validated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('validated_by', sa.VARCHAR(length=100), server_default=sa.text("'AI_VALIDATION_ENGINE'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('validation_reports_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('validation_reports_pkey'))
    )
    op.create_table('posting_schedule',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=100), server_default=sa.text("'linkedin'::character varying"), autoincrement=False, nullable=True),
    sa.Column('scheduled_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scheduled_time', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=50), server_default=sa.text("'Asia/Kolkata'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'QUEUED'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('recurrence_type', sa.VARCHAR(length=50), server_default=sa.text("'one_time'::character varying"), autoincrement=False, nullable=True),
    sa.Column('cron_expression', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('planner_run_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('scheduled_day', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('slot_number', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_posts.id'], name=op.f('posting_schedule_content_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('posting_schedule_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('posting_schedule_pkey'))
    )
    op.create_table('brand_prompt_templates',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=50), server_default=sa.text("'LinkedIn'::character varying"), autoincrement=False, nullable=False),
    sa.Column('prompt_type', sa.VARCHAR(length=50), server_default=sa.text("'content'::character varying"), autoincrement=False, nullable=False),
    sa.Column('prompt_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('prompt_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('active', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('brand_prompt_templates_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_prompt_templates_pkey')),
    sa.UniqueConstraint('workspace_id', 'platform', 'prompt_type', name=op.f('uq_ws_platform_ptype'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('brand_profiles',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('brand_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tagline', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tone', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('primary_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('secondary_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('brand_profiles_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_profiles_pkey'))
    )
    op.create_table('content_versions',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('editor', sa.VARCHAR(length=255), server_default=sa.text("'AI Content Engine'::character varying"), autoincrement=False, nullable=True),
    sa.Column('ai_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('change_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hashtags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_posts.id'], name=op.f('content_versions_content_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('content_versions_pkey'))
    )
    op.create_table('media_library',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('visual_style', sa.VARCHAR(length=50), server_default=sa.text("'Enterprise'::character varying"), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=100), server_default=sa.text("'AI Engine'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('media_library_pkey'))
    )
    op.create_table('content_posts',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('campaign_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=100), server_default=sa.text("'linkedin'::character varying"), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('subtitle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hook', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), server_default=sa.text("'Educational'::character varying"), autoincrement=False, nullable=True),
    sa.Column('pillar', sa.VARCHAR(length=100), server_default=sa.text("'Thought Leadership'::character varying"), autoincrement=False, nullable=True),
    sa.Column('objective', sa.VARCHAR(length=100), server_default=sa.text("'Brand Awareness'::character varying"), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hashtags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('alt_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('85.0'), autoincrement=False, nullable=True),
    sa.Column('brand_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('90.0'), autoincrement=False, nullable=True),
    sa.Column('grammar_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('95.0'), autoincrement=False, nullable=True),
    sa.Column('readability_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('88.0'), autoincrement=False, nullable=True),
    sa.Column('seo_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('80.0'), autoincrement=False, nullable=True),
    sa.Column('ai_confidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.9'), autoincrement=False, nullable=True),
    sa.Column('estimated_reach', sa.INTEGER(), server_default=sa.text('1500'), autoincrement=False, nullable=True),
    sa.Column('estimated_engagement', sa.INTEGER(), server_default=sa.text('120'), autoincrement=False, nullable=True),
    sa.Column('suggested_post_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=True),
    sa.Column('approval_status', sa.VARCHAR(length=50), server_default=sa.text("'APPROVED'::character varying"), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('generated_by', sa.VARCHAR(length=255), server_default=sa.text("'Svora AI Engine'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('ai_reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seo_keywords', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('emoji_suggestions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reading_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('character_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_pillar', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('final_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scheduled_day', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('scheduled_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('scheduled_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('planner_type', sa.VARCHAR(length=50), server_default=sa.text("'weekly'::character varying"), autoincrement=False, nullable=True),
    sa.Column('planner_run_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active_plan', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('paused_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('workflow_status', sa.VARCHAR(length=50), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('content_posts_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('content_posts_pkey'))
    )
    op.create_table('daily_post_schedules',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('post_slot', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('slot_time', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('target_account', sa.VARCHAR(length=100), server_default=sa.text("'Personal LinkedIn Profile'::character varying"), autoincrement=False, nullable=True),
    sa.Column('topic_category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('headline', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('first_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hashtags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('visual_style', sa.VARCHAR(length=50), server_default=sa.text("'Professional'::character varying"), autoincrement=False, nullable=True),
    sa.Column('content_score', sa.INTEGER(), server_default=sa.text('92'), autoincrement=False, nullable=True),
    sa.Column('reading_time_mins', sa.INTEGER(), server_default=sa.text('2'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'SCHEDULED'::character varying"), autoincrement=False, nullable=True),
    sa.Column('auto_approve', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('scheduled_for_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('share_urn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('post_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_post_schedules_pkey'))
    )
    op.create_table('linkedin_accounts',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('linkedin_member_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('linkedin_urn', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('account_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('headline', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('profile_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profile_image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('scope', sa.TEXT(), server_default=sa.text("'w_member_social openid profile email'::text"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'CONNECTED'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('last_sync', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('linkedin_accounts_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('linkedin_accounts_pkey'))
    )
    op.create_table('brand_templates',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('template_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), server_default=sa.text("'General'::character varying"), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=100), server_default=sa.text("'LinkedIn'::character varying"), autoincrement=False, nullable=True),
    sa.Column('file_format', sa.VARCHAR(length=50), server_default=sa.text("'Markdown'::character varying"), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(length=50), server_default=sa.text("'1.0'::character varying"), autoincrement=False, nullable=True),
    sa.Column('ai_category', sa.VARCHAR(length=100), server_default=sa.text("'Thought Leadership'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('brand_templates_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_templates_pkey'))
    )
    op.create_table('brand_prompts',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('daily_ai_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('campaign_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hashtag_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('daily_linkedin_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('daily_facebook_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('daily_instagram_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('daily_twitter_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('daily_threads_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('daily_youtube_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('brand_prompts_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_prompts_pkey'))
    )
    op.create_table('workspace_ai_prompts',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('master_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('linkedin_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('facebook_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('instagram_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('threads_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('twitter_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('youtube_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pinterest_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('campaign_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('video_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('comment_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hashtag_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=50), server_default=sa.text("'English'::character varying"), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('workspace_ai_prompts_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_ai_prompts_pkey'))
    )
    op.create_table('schedule_conflicts',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('existing_post_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('new_post_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('resolution', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('schedule_conflicts_pkey'))
    )
    op.create_table('user_settings',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('theme', sa.VARCHAR(length=50), server_default=sa.text("'dark'::character varying"), autoincrement=False, nullable=True),
    sa.Column('notifications', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('user_settings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_settings_pkey'))
    )
    op.create_table('email_verifications',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('otp_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('resend_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('email_verifications_pkey')),
    sa.UniqueConstraint('email', name=op.f('email_verifications_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('manual_posts',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), server_default=sa.text("'LinkedIn'::character varying"), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('hashtags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mentions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('media_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_thumbnail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('media_size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('schedule_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=100), server_default=sa.text("'Asia/Kolkata'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('share_urn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('post_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('manual_posts_pkey'))
    )
    op.create_table('ai_topic_analysis',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('primary_topic', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('secondary_topics', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=150), server_default=sa.text("'Technology'::character varying"), autoincrement=False, nullable=True),
    sa.Column('audience', sa.VARCHAR(length=150), server_default=sa.text("'Executive CTO & Architects'::character varying"), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('visual_style', sa.VARCHAR(length=150), server_default=sa.text("'Enterprise Architecture Diagram'::character varying"), autoincrement=False, nullable=True),
    sa.Column('generated_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('95.0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('ai_topic_analysis_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_topic_analysis_pkey'))
    )
    op.create_table('brand_template_usage',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('template_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('module', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('used_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('generated_content_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('brand_template_usage_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_template_usage_pkey'))
    )
    op.create_table('brand_ai_content_settings',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=50), server_default=sa.text("'LinkedIn'::character varying"), autoincrement=False, nullable=False),
    sa.Column('minimum_characters', sa.INTEGER(), server_default=sa.text('300'), autoincrement=False, nullable=True),
    sa.Column('maximum_characters', sa.INTEGER(), server_default=sa.text('3000'), autoincrement=False, nullable=True),
    sa.Column('recommended_characters', sa.INTEGER(), server_default=sa.text('1200'), autoincrement=False, nullable=True),
    sa.Column('maximum_paragraphs', sa.INTEGER(), server_default=sa.text('15'), autoincrement=False, nullable=True),
    sa.Column('maximum_empty_lines', sa.INTEGER(), server_default=sa.text('20'), autoincrement=False, nullable=True),
    sa.Column('maximum_hashtags', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=True),
    sa.Column('maximum_mentions', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True),
    sa.Column('maximum_emojis', sa.INTEGER(), server_default=sa.text('6'), autoincrement=False, nullable=True),
    sa.Column('default_cta', sa.TEXT(), server_default=sa.text("'👇 Share your thoughts below!'::text"), autoincrement=False, nullable=True),
    sa.Column('default_signature', sa.TEXT(), server_default=sa.text("'— Powered by Svora AI'::text"), autoincrement=False, nullable=True),
    sa.Column('allow_markdown', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('allow_bullet_lists', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('content_depth', sa.VARCHAR(length=50), server_default=sa.text("'Medium'::character varying"), autoincrement=False, nullable=True),
    sa.Column('topic_expansion', sa.VARCHAR(length=50), server_default=sa.text("'Related Topics'::character varying"), autoincrement=False, nullable=True),
    sa.Column('knowledge_source', sa.VARCHAR(length=50), server_default=sa.text("'Hybrid'::character varying"), autoincrement=False, nullable=True),
    sa.Column('writing_style', sa.VARCHAR(length=50), server_default=sa.text("'Thought Leadership'::character varying"), autoincrement=False, nullable=True),
    sa.Column('creativity_level', sa.INTEGER(), server_default=sa.text('70'), autoincrement=False, nullable=True),
    sa.Column('allow_storytelling', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('allow_statistics', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('allow_examples', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('allow_analogies', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('allow_case_studies', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('allow_industry_trends', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('allow_opinions', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('allow_personal_tone', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('allow_marketing_language', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('allow_technical_content', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('allow_ai_suggestions', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('minimum_ai_score', sa.INTEGER(), server_default=sa.text('80'), autoincrement=False, nullable=True),
    sa.Column('grammar_check', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('brand_voice_check', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('duplicate_check', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('readability_check', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('cta_validation', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('hashtag_validation', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('emoji_validation', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('length_validation', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('approval_required', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('auto_publish', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('generate_image', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('regenerate_until_score', sa.INTEGER(), server_default=sa.text('85'), autoincrement=False, nullable=True),
    sa.Column('maximum_retry_count', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True),
    sa.Column('default_publish_time', sa.VARCHAR(length=50), server_default=sa.text("'09:00 AM IST'::character varying"), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), server_default=sa.text("'Asia/Kolkata'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('brand_ai_content_settings_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_ai_content_settings_pkey')),
    sa.UniqueConstraint('workspace_id', 'platform', name=op.f('uq_ws_platform'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('image_generation_logs',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=100), server_default=sa.text("'OpenAI Images'::character varying"), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.04'), autoincrement=False, nullable=True),
    sa.Column('latency', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.2'), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('95.0'), autoincrement=False, nullable=True),
    sa.Column('validation_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('96.0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('image_generation_logs_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('image_generation_logs_pkey'))
    )
    op.create_table('brand_daily_prompts',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('posting_time', sa.VARCHAR(length=50), server_default=sa.text("'09:00 AM IST'::character varying"), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('brand_daily_prompts_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_daily_prompts_pkey'))
    )
    op.create_table('brand_prompt_library',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('prompt_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('prompt_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('brand_prompt_library_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_prompt_library_pkey'))
    )
    op.create_table('workspaces',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('plan', sa.VARCHAR(length=50), server_default=sa.text("'enterprise'::character varying"), autoincrement=False, nullable=True),
    sa.Column('workspace_type', sa.VARCHAR(length=50), server_default=sa.text("'BUSINESS'::character varying"), autoincrement=False, nullable=True),
    sa.Column('workspace_category', sa.VARCHAR(length=50), server_default=sa.text("'Startup'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('workspaces_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspaces_pkey'))
    )
    op.create_table('brand_content_templates',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('template_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), server_default=sa.text("'General'::character varying"), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=100), server_default=sa.text("'LinkedIn'::character varying"), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), server_default=sa.text("'Markdown'::character varying"), autoincrement=False, nullable=True),
    sa.Column('template_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('brand_content_templates_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_content_templates_pkey'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_table('brand_centers',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('account_type', sa.VARCHAR(length=50), server_default=sa.text("'Company'::character varying"), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tagline', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mission', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vision', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('business_type', sa.VARCHAR(length=100), server_default=sa.text("'BUSINESS'::character varying"), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=100), server_default=sa.text("'Technology'::character varying"), autoincrement=False, nullable=True),
    sa.Column('website', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mobile_no', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logo_position', sa.VARCHAR(length=50), server_default=sa.text("'top-left'::character varying"), autoincrement=False, nullable=True),
    sa.Column('logo_opacity', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('logo_margin', sa.INTEGER(), server_default=sa.text('20'), autoincrement=False, nullable=True),
    sa.Column('logo_scale', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('primary_color', sa.VARCHAR(length=50), server_default=sa.text("'#07111F'::character varying"), autoincrement=False, nullable=True),
    sa.Column('secondary_color', sa.VARCHAR(length=50), server_default=sa.text("'#8E123C'::character varying"), autoincrement=False, nullable=True),
    sa.Column('accent_color', sa.VARCHAR(length=50), server_default=sa.text("'#D4AF37'::character varying"), autoincrement=False, nullable=True),
    sa.Column('success_color', sa.VARCHAR(length=50), server_default=sa.text("'#10B981'::character varying"), autoincrement=False, nullable=True),
    sa.Column('warning_color', sa.VARCHAR(length=50), server_default=sa.text("'#F59E0B'::character varying"), autoincrement=False, nullable=True),
    sa.Column('danger_color', sa.VARCHAR(length=50), server_default=sa.text("'#EF4444'::character varying"), autoincrement=False, nullable=True),
    sa.Column('heading_font', sa.VARCHAR(length=100), server_default=sa.text("'Outfit'::character varying"), autoincrement=False, nullable=True),
    sa.Column('body_font', sa.VARCHAR(length=100), server_default=sa.text("'Inter'::character varying"), autoincrement=False, nullable=True),
    sa.Column('tone', sa.VARCHAR(length=100), server_default=sa.text("'Professional'::character varying"), autoincrement=False, nullable=True),
    sa.Column('audience_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_industry', sa.VARCHAR(length=100), server_default=sa.text("'Technology'::character varying"), autoincrement=False, nullable=True),
    sa.Column('target_profession', sa.VARCHAR(length=100), server_default=sa.text("'Software Engineer'::character varying"), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), server_default=sa.text("'Global'::character varying"), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=50), server_default=sa.text("'English'::character varying"), autoincrement=False, nullable=True),
    sa.Column('default_llm', sa.VARCHAR(length=100), server_default=sa.text("'gpt-4o'::character varying"), autoincrement=False, nullable=True),
    sa.Column('image_model', sa.VARCHAR(length=100), server_default=sa.text("'svora-diffusion-v3'::character varying"), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.7'), autoincrement=False, nullable=True),
    sa.Column('creativity', sa.VARCHAR(length=50), server_default=sa.text("'Balanced'::character varying"), autoincrement=False, nullable=True),
    sa.Column('writing_style', sa.VARCHAR(length=100), server_default=sa.text("'Thought Leadership'::character varying"), autoincrement=False, nullable=True),
    sa.Column('image_style', sa.VARCHAR(length=100), server_default=sa.text("'3D Glassmorphism'::character varying"), autoincrement=False, nullable=True),
    sa.Column('daily_posting_enabled', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('posting_time', sa.VARCHAR(length=50), server_default=sa.text("'09:00 AM IST'::character varying"), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), server_default=sa.text("'Asia/Kolkata'::character varying"), autoincrement=False, nullable=True),
    sa.Column('default_hashtags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('default_cta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_centers_pkey')),
    sa.UniqueConstraint('workspace_id', name=op.f('brand_centers_workspace_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('campaigns',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=True),
    sa.Column('target_audience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('channels', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('posts_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('campaigns_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('campaigns_pkey'))
    )
    op.create_table('workflow_history',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('from_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('to_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('performed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_posts.id'], name=op.f('workflow_history_content_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_history_pkey'))
    )
    op.create_table('visual_knowledge_library',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('aliases', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=150), server_default=sa.text("'Technology'::character varying"), autoincrement=False, nullable=True),
    sa.Column('visual_objects', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('preferred_styles', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('forbidden_objects', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('example_prompts', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('visual_knowledge_library_pkey'))
    )
    op.create_table('brand_image_templates',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('template_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_format', sa.VARCHAR(length=50), server_default=sa.text("'PNG'::character varying"), autoincrement=False, nullable=True),
    sa.Column('template_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preview_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolution', sa.VARCHAR(length=50), server_default=sa.text("'1080x1350'::character varying"), autoincrement=False, nullable=True),
    sa.Column('aspect_ratio', sa.VARCHAR(length=50), server_default=sa.text("'4:5'::character varying"), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), server_default=sa.text("'Poster'::character varying"), autoincrement=False, nullable=True),
    sa.Column('ai_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brand_colors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logo_position', sa.VARCHAR(length=50), server_default=sa.text("'top-left'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('brand_image_templates_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_image_templates_pkey'))
    )
    op.drop_index(op.f('ix_user_session_token_jti'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_tenant_id'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_public_id'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_is_revoked'), table_name='user_session')
    op.drop_table('user_session')
    op.drop_index(op.f('ix_user_role_tenant_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_public_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_role_permission_tenant_id'), table_name='role_permission')
    op.drop_index(op.f('ix_role_permission_public_id'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_password_reset_token_token_hash'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_public_id'), table_name='password_reset_token')
    op.drop_table('password_reset_token')
    op.drop_index(op.f('ix_company_tenant_id'), table_name='company')
    op.drop_index(op.f('ix_company_public_id'), table_name='company')
    op.drop_index(op.f('ix_company_is_deleted'), table_name='company')
    op.drop_index(op.f('ix_company_code'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_api_key_tenant_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_public_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_key_prefix'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_is_deleted'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_company_id'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_index(op.f('ix_tenant_public_id'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_is_deleted'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_code'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_system_configuration_tenant_id'), table_name='system_configuration')
    op.drop_index(op.f('ix_system_configuration_public_id'), table_name='system_configuration')
    op.drop_index(op.f('ix_system_configuration_key'), table_name='system_configuration')
    op.drop_table('system_configuration')
    op.drop_index(op.f('ix_role_tenant_id'), table_name='role')
    op.drop_index(op.f('ix_role_public_id'), table_name='role')
    op.drop_index(op.f('ix_role_is_deleted'), table_name='role')
    op.drop_index(op.f('ix_role_code'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_public_id'), table_name='permission')
    op.drop_index(op.f('ix_permission_module'), table_name='permission')
    op.drop_index(op.f('ix_permission_code'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_entity_tenant_id'), table_name='entity')
    op.drop_index(op.f('ix_entity_public_id'), table_name='entity')
    op.drop_index(op.f('ix_entity_is_deleted'), table_name='entity')
    op.drop_index(op.f('ix_entity_company_id'), table_name='entity')
    op.drop_table('entity')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_resource_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_public_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_company_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_admin_user_username'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_tenant_id'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_public_id'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_is_deleted'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_email'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_company_id'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
